// scjio_agilex.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module scjio_agilex #(
		parameter CONTROL = "host"
	) (
		input  wire  jtag_clock_clk,       //   jtag_clock.clk,    Clock Input
		input  wire  jtag_signals_tms,     // jtag_signals.tms
		input  wire  jtag_signals_tdi,     //             .tdi
		output wire  jtag_signals_tdo,     //             .tdo
		input  wire  jtag_signals_tck_ena  //             .tck_ena
	);

	scjio_agilex_intel_soft_core_jtag_io_10_nlyl3tq #(
		.CONTROL          (CONTROL),
		.NAME             ("soft_jtag"),
		.HOST_PRIORITY    (200),
		.USE_TCK_ENA      (1),
		.CLOCK_RATE_CLOCK (0)
	) intel_soft_core_jtag_io_0 (
		.jtag_clock_clk       (jtag_clock_clk),       //   input,  width = 1,   jtag_clock.clk
		.jtag_signals_tms     (jtag_signals_tms),     //   input,  width = 1, jtag_signals.tms
		.jtag_signals_tdi     (jtag_signals_tdi),     //   input,  width = 1,             .tdi
		.jtag_signals_tdo     (jtag_signals_tdo),     //  output,  width = 1,             .tdo
		.jtag_signals_tck_ena (jtag_signals_tck_ena)  //   input,  width = 1,             .tck_ena
	);

endmodule
