##
## Generated by OFS script ofs_ip_cfg_db.tcl
##

# Search paths for include files generated by ip_gen_sv_wrapper.tcl
set_global_assignment -name SEARCH_PATH "../../../../ipss/pcie/qip/sv_wrapper"
set_global_assignment -name SYSTEMVERILOG_FILE "../../../../ipss/pcie/qip/sv_wrapper/pcie_ss_param_pkg.sv"
set_global_assignment -name SYSTEMVERILOG_FILE "../../../../ipss/pcie/qip/sv_wrapper/pcie_ss_sv.sv"
set_global_assignment -name SEARCH_PATH "../../../../ofs-common/src/fpga_family/agilex/sys_pll/sv_wrapper"
set_global_assignment -name SYSTEMVERILOG_FILE "../../../../ofs-common/src/fpga_family/agilex/sys_pll/sv_wrapper/sys_pll_param_pkg.sv"
set_global_assignment -name SYSTEMVERILOG_FILE "../../../../ofs-common/src/fpga_family/agilex/sys_pll/sv_wrapper/sys_pll_sv.sv"
set_global_assignment -name SEARCH_PATH "../../../../ipss/mem/qip/mem_ss/sv_wrapper"
set_global_assignment -name SYSTEMVERILOG_FILE "../../../../ipss/mem/qip/mem_ss/sv_wrapper/mem_ss_param_pkg.sv"
set_global_assignment -name SYSTEMVERILOG_FILE "../../../../ipss/mem/qip/mem_ss/sv_wrapper/mem_ss_sv.sv"
