//
// Generated by OFS script mem_ss_get_cfg.tcl using qsys-script
//

`ifndef __OFS_FIM_IP_CFG_LOCAL_MEM__
`define __OFS_FIM_IP_CFG_LOCAL_MEM__ 1


//
// Flags to enable memory channel instantiation/configuration 
//
`define OFS_FIM_IP_CFG_LOCAL_MEM_ENTITY mem_ss

`endif // `ifndef __OFS_FIM_IP_CFG_LOCAL_MEM__
