//
// Generated by OFS script ofs_ip_cfg_db.tcl
//

// Include all generated configuration files
`include "pcie_ss_if_info.vh"    // In ipss/pcie/qip/sv_wrapper
`include "pcie_ss_ip_params.vh"
`include "ofs_ip_cfg_pcie_ss.vh"
`include "sys_pll_if_info.vh"    // In ofs-common/src/fpga_family/agilex/sys_pll/sv_wrapper
`include "sys_pll_ip_params.vh"
`include "mem_ss_if_info.vh"    // In ipss/mem/qip/mem_ss/sv_wrapper
`include "mem_ss_ip_params.vh"
`include "ofs_ip_cfg_local_mem.vh"
