//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_ahls_afu_fim_01/awp/afu_with_pim/afu/hw/ahls_qual_vec_op.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "ahls_qual_vec_op"
`define AFU_ACCEL_NAME0 "ahls_qual_vec_op"
`define AFU_ACCEL_UUID 128'h67bc266a_56f7_440a_bb75_12b5f446d842
`define AFU_ACCEL_UUID0 128'h67bc266a_56f7_440a_bb75_12b5f446d842
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
