# (C) 2001-2025 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# (C) 2001-2024 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.
# This is an auto-generated file. Do not edit this file.

# 
# altera_sld_host_endpoint "altera_sld_host_endpoint" v1.0
# 

# request TCL package from ACDS 24.3
# 
package require -exact qsys 20.1

# 
# module altera_sld_host_endpoint
# 
set_module_property NAME altera_sld_host_endpoint
set_module_property AUTHOR "Intel Corporation"
set_module_property GROUP "Verification/Debug & Performance"
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME "Intel FPGA SLD Host Endpoint"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK true
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property ELABORATION_CALLBACK elaborate
set_module_assignment debug.virtualInterface.link {debug.fabricLink {fabric sld} }
set_module_assignment debug.isTransparent true

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_sld_host_endpoint_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_sld_host_endpoint_wrapper.sv system_verilog path altera_sld_host_endpoint_wrapper.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_sld_host_endpoint_wrapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_sld_host_endpoint_wrapper.sv system_verilog path altera_sld_host_endpoint_wrapper.sv

add_fileset CDC CDC "" ""
set_fileset_property CDC TOP_LEVEL altera_sld_host_endpoint_wrapper
set_fileset_property CDC ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_sld_host_endpoint_wrapper.sv system_verilog path altera_sld_host_endpoint_wrapper.sv

# 
# parameters
# 
add_parameter ENABLE_JTAG_IO_SELECTION INTEGER 0
set_parameter_property ENABLE_JTAG_IO_SELECTION AFFECTS_ELABORATION true
set_parameter_property ENABLE_JTAG_IO_SELECTION AFFECTS_GENERATION false
set_parameter_property ENABLE_JTAG_IO_SELECTION HDL_PARAMETER true

add_parameter CONTROL STRING host
set_parameter_property CONTROL ALLOWED_RANGES {host hubctrl}
set_parameter_property CONTROL AFFECTS_ELABORATION false
set_parameter_property CONTROL AFFECTS_GENERATION false
set_parameter_property CONTROL HDL_PARAMETER true

add_parameter NAME STRING {}
set_parameter_property NAME AFFECTS_ELABORATION false
set_parameter_property NAME AFFECTS_GENERATION false
set_parameter_property NAME HDL_PARAMETER true

add_parameter HOST_PRIORITY INTEGER 0
set_parameter_property HOST_PRIORITY AFFECTS_ELABORATION false
set_parameter_property HOST_PRIORITY AFFECTS_GENERATION false
set_parameter_property HOST_PRIORITY HDL_PARAMETER true

add_parameter BRIDGE_HOST INTEGER 0
set_parameter_property BRIDGE_HOST AFFECTS_ELABORATION true
set_parameter_property BRIDGE_HOST AFFECTS_GENERATION false
set_parameter_property BRIDGE_HOST HDL_PARAMETER true

add_parameter USE_TCK_ENA INTEGER 0
set_parameter_property USE_TCK_ENA AFFECTS_ELABORATION true
set_parameter_property USE_TCK_ENA AFFECTS_GENERATION false
set_parameter_property USE_TCK_ENA HDL_PARAMETER true

add_parameter NEGEDGE_TDO_LATCH INTEGER 0
set_parameter_property NEGEDGE_TDO_LATCH AFFECTS_ELABORATION false
set_parameter_property NEGEDGE_TDO_LATCH AFFECTS_GENERATION false
set_parameter_property NEGEDGE_TDO_LATCH HDL_PARAMETER true

add_parameter TYPE_NAME INTEGER 0
set_parameter_property TYPE_NAME AFFECTS_ELABORATION false
set_parameter_property TYPE_NAME AFFECTS_GENERATION false
set_parameter_property TYPE_NAME HDL_PARAMETER true

add_parameter INSTANCE_NAME INTEGER 0
set_parameter_property INSTANCE_NAME AFFECTS_ELABORATION false
set_parameter_property INSTANCE_NAME AFFECTS_GENERATION false
set_parameter_property INSTANCE_NAME HDL_PARAMETER true

add_parameter CLOCK_RATE_CLOCK INTEGER 0
set_parameter_property CLOCK_RATE_CLOCK SYSTEM_INFO {CLOCK_RATE clock}
set_parameter_property CLOCK_RATE_CLOCK AFFECTS_ELABORATION false
set_parameter_property CLOCK_RATE_CLOCK AFFECTS_GENERATION false
set_parameter_property CLOCK_RATE_CLOCK HDL_PARAMETER true


# 
# display items
# 

#
# connection point clock
#
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock tck clk Input 1


#
# connection point node
#
add_interface node conduit end
set_interface_property node associatedClock clock
set_interface_property node ENABLED true
set_interface_assignment node debug.controlledBy {link}
add_interface_port node tms tms Input 1
add_interface_port node tdi tdi Input 1
add_interface_port node ena ena Input 1
set_port_property ena termination true
add_interface_port node vir_tdi vir_tdi Input 1
set_port_property vir_tdi termination true
add_interface_port node tck_ena tck_ena Input 1
set_port_property tck_ena termination true
add_interface_port node tdo tdo Output 1
add_interface_port node select_this select_this Input 1
set_port_property select_this termination true


#
# Elaboration callback
#
proc elaborate {} {
    set ENABLE_JTAG_IO_SELECTION [get_parameter_value ENABLE_JTAG_IO_SELECTION]
    set BRIDGE_HOST [get_parameter_value BRIDGE_HOST]
    set USE_TCK_ENA [get_parameter_value USE_TCK_ENA]

    if {$BRIDGE_HOST != 0} {
        set_port_property ena termination false
        set_port_property vir_tdi termination false
    }

    if {$USE_TCK_ENA != 0} {
        set_port_property tck_ena termination false
    }

    if {$ENABLE_JTAG_IO_SELECTION != 0} {
        set_port_property select_this termination false
    }
}

proc log2 x {expr {int(ceil(log($x) / log(2)))}}
