// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// This is an auto-generated file. Do not edit this file.
// altera_avalon_st_debug_host_endpoint.sv

`timescale 1 ns / 1 ns

package altera_avalon_st_debug_host_endpoint_wpackage;

function integer nonzero;
input integer value;
begin
	nonzero = (value > 0) ? value : 1;
end
endfunction

endpackage

module altera_avalon_st_debug_host_endpoint_wrapper
    import altera_avalon_st_debug_host_endpoint_wpackage::nonzero;
#(
    parameter DATA_WIDTH           = 8,
    parameter CHANNEL_WIDTH        = 8,
    parameter NAME                 = "",
    parameter HOST_PRIORITY        = 100,
    parameter TYPE_NAME            = 0,
    parameter INSTANCE_NAME        = 0,
    parameter CLOCK_RATE_CLK       = 0
) (
    input         clk,
    input         reset,
    output        h2t_ready,
    input         h2t_valid,
    input  [DATA_WIDTH-1:0] h2t_data,
    input         h2t_startofpacket,
    input         h2t_endofpacket,
    input  [nonzero($clog2(DATA_WIDTH) - 3)-1:0] h2t_empty,
    input  [CHANNEL_WIDTH-1:0] h2t_channel,
    input         t2h_ready,
    output        t2h_valid,
    output [DATA_WIDTH-1:0] t2h_data,
    output        t2h_startofpacket,
    output        t2h_endofpacket,
    output [nonzero($clog2(DATA_WIDTH) - 3)-1:0] t2h_empty,
    output [CHANNEL_WIDTH-1:0] t2h_channel,
    input         mgmt_valid,
    input         mgmt_data,
    input  [CHANNEL_WIDTH-1:0] mgmt_channel
);

	altera_avalon_st_debug_host_endpoint #(
        .DATA_WIDTH           (DATA_WIDTH),
        .CHANNEL_WIDTH        (CHANNEL_WIDTH),
        .NAME                 (NAME),
        .HOST_PRIORITY        (HOST_PRIORITY),
        .TYPE_NAME            (TYPE_NAME),
        .INSTANCE_NAME        (INSTANCE_NAME),
        .CLOCK_RATE_CLK       (CLOCK_RATE_CLK)
) inst (
        .clk                  (clk),
        .reset                (reset),
        .h2t_ready            (h2t_ready),
        .h2t_valid            (h2t_valid),
        .h2t_data             (h2t_data),
        .h2t_startofpacket    (h2t_startofpacket),
        .h2t_endofpacket      (h2t_endofpacket),
        .h2t_empty            (h2t_empty),
        .h2t_channel          (h2t_channel),
        .t2h_ready            (t2h_ready),
        .t2h_valid            (t2h_valid),
        .t2h_data             (t2h_data),
        .t2h_startofpacket    (t2h_startofpacket),
        .t2h_endofpacket      (t2h_endofpacket),
        .t2h_empty            (t2h_empty),
        .t2h_channel          (t2h_channel),
        .mgmt_valid           (mgmt_valid),
        .mgmt_data            (mgmt_data),
        .mgmt_channel         (mgmt_channel)
	
	);

endmodule

// synthesis translate_off
// Empty module definition to allow simulation compilation.
module altera_avalon_st_debug_host_endpoint
    import altera_avalon_st_debug_host_endpoint_wpackage::nonzero;
#(
    parameter DATA_WIDTH           = 8,
    parameter CHANNEL_WIDTH        = 8,
    parameter NAME                 = "",
    parameter HOST_PRIORITY        = 100,
    parameter TYPE_NAME            = 0,
    parameter INSTANCE_NAME        = 0,
    parameter CLOCK_RATE_CLK       = 0
) (
    input         clk,
    input         reset,
    output        h2t_ready,
    input         h2t_valid,
    input  [DATA_WIDTH-1:0] h2t_data,
    input         h2t_startofpacket,
    input         h2t_endofpacket,
    input  [nonzero($clog2(DATA_WIDTH) - 3)-1:0] h2t_empty,
    input  [CHANNEL_WIDTH-1:0] h2t_channel,
    input         t2h_ready,
    output        t2h_valid,
    output [DATA_WIDTH-1:0] t2h_data,
    output        t2h_startofpacket,
    output        t2h_endofpacket,
    output [nonzero($clog2(DATA_WIDTH) - 3)-1:0] t2h_empty,
    output [CHANNEL_WIDTH-1:0] t2h_channel,
    input         mgmt_valid,
    input         mgmt_data,
    input  [CHANNEL_WIDTH-1:0] mgmt_channel
);
endmodule
// synthesis translate_on

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "KaCcZ9W53ZG+KOUC3MpOxTkG8JzVU+FMIR8JyDs33NK1wcErIABMqJM+BlBnaEf20FCKJ7ToOlAha/ltC5u0ZbClu2TybZQciMInF+iFoiagt+B91BK4dyi6GJUCXUDuBK9YH6nNlwSkR01tHuzzS5ZEiJtw78iQaS7cFEmJNjv/muideRZVdy13EnGEeyFpK62Cg4KcVOZTCHinGABXbAtq/uBBjPG6GClkBmeTng1wNsmaF0S2ngN4mihZdkQTPMyoc8Vyb/neWnO/hZ0g5emqYz0kjx+Ss5ZZRQhHtWhff/6EicYNTfzCaRSChyDzTyubg5iTeIW6w/8lGqmhF1CN41u2boSSLPibsG8tdyMpzRJIOk9oHHVmb81SRQ0aH9KrRwcpjNETzAtCZyMIUDm0YPqmdPQhZ5Kc7JY8g2hPDkvGxlXqNoYmuZd+TnCc/Da3EAG2XT+eYgKzrkMHcsCvjsNkA1053/Ha3aSNoLCm4kbTZt6yrr+0lQ2FjhHaV4qdNvsLJWURG5rzo8o/X1+RKXM/jAIFaQJILWwvmTIguPbFoVj21Dh33RnLs5rkO+h8vYZAF6ZjLmLwlGorqDRoE3h2D47WxB10JsNBlXMfIMwcDnKn9isZqnp6OCE2q5HCh8aQUh+xubWuLBdcawCyEW0OoEAYoSHe80B30n1+4jAqShUgSaj0g63kLYX4MzLEB2c79+V39150xrYassuL/eA5aT6vxwerlUYyMm7AjuqbxV97gAobHxi8V6pTqcONnDAw7dUglFFLoEohRr2QHEMSEKScMqHFdXXcejCgXK7a1sBSOsY22K62ownJK17E3tHZU6xrthNh6qgAqQHbytS24Ku4CdnqUzPO7L/T+A86tESamWI10ReSi3fFw1rURfetcEASWtuoMPNRZeMOU0lrHVLZA21iPD+4FG5KefBwxJsZElSZf1wxsJVVyqdBDJXJQ3SYCbiJbuvvx2hvxrfX3AdKyS0YJlRZ6ard85RG9Y4qNZKQB+FC4199"
`endif