// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// This is an auto-generated file. Do not edit this file.
// altera_sld_host_endpoint.sv

`timescale 1 ns / 1 ns

package altera_sld_host_endpoint_wpackage;

function integer nonzero;
input integer value;
begin
	nonzero = (value > 0) ? value : 1;
end
endfunction

endpackage

module altera_sld_host_endpoint_wrapper
    import altera_sld_host_endpoint_wpackage::nonzero;
#(
    parameter ENABLE_JTAG_IO_SELECTION = 0,
    parameter CONTROL        = "host",
    parameter NAME           = "",
    parameter HOST_PRIORITY  = 0,
    parameter BRIDGE_HOST    = 0,
    parameter USE_TCK_ENA    = 0,
    parameter NEGEDGE_TDO_LATCH = 0,
    parameter TYPE_NAME      = 0,
    parameter INSTANCE_NAME  = 0,
    parameter CLOCK_RATE_CLOCK = 0
) (
    input         tck,
    input         tms,
    input         tdi,
    input         ena,
    input         vir_tdi,
    input         tck_ena,
    output        tdo,
    input         select_this
);

	altera_sld_host_endpoint #(
        .ENABLE_JTAG_IO_SELECTION (ENABLE_JTAG_IO_SELECTION),
        .CONTROL        (CONTROL),
        .NAME           (NAME),
        .HOST_PRIORITY  (HOST_PRIORITY),
        .BRIDGE_HOST    (BRIDGE_HOST),
        .USE_TCK_ENA    (USE_TCK_ENA),
        .NEGEDGE_TDO_LATCH (NEGEDGE_TDO_LATCH),
        .TYPE_NAME      (TYPE_NAME),
        .INSTANCE_NAME  (INSTANCE_NAME),
        .CLOCK_RATE_CLOCK (CLOCK_RATE_CLOCK)
) inst (
        .tck            (tck),
        .tms            (tms),
        .tdi            (tdi),
        .ena            (ena),
        .vir_tdi        (vir_tdi),
        .tck_ena        (tck_ena),
        .tdo            (tdo),
        .select_this    (select_this)
	
	);

endmodule

// synthesis translate_off
// Empty module definition to allow simulation compilation.
module altera_sld_host_endpoint
    import altera_sld_host_endpoint_wpackage::nonzero;
#(
    parameter ENABLE_JTAG_IO_SELECTION = 0,
    parameter CONTROL        = "host",
    parameter NAME           = "",
    parameter HOST_PRIORITY  = 0,
    parameter BRIDGE_HOST    = 0,
    parameter USE_TCK_ENA    = 0,
    parameter NEGEDGE_TDO_LATCH = 0,
    parameter TYPE_NAME      = 0,
    parameter INSTANCE_NAME  = 0,
    parameter CLOCK_RATE_CLOCK = 0
) (
    input         tck,
    input         tms,
    input         tdi,
    input         ena,
    input         vir_tdi,
    input         tck_ena,
    output        tdo,
    input         select_this
);
endmodule
// synthesis translate_on

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "KaCcZ9W53ZG+KOUC3MpOxTkG8JzVU+FMIR8JyDs33NK1wcErIABMqJM+BlBnaEf20FCKJ7ToOlAha/ltC5u0ZbClu2TybZQciMInF+iFoiagt+B91BK4dyi6GJUCXUDuBK9YH6nNlwSkR01tHuzzS5ZEiJtw78iQaS7cFEmJNjv/muideRZVdy13EnGEeyFpK62Cg4KcVOZTCHinGABXbAtq/uBBjPG6GClkBmeTng05JnTvsMHIibZsYCwkcMuFo93aMaNPfl4tzSJz9wXXnHV1vuW5h8kpt2b+i8Lv/5d9RtZ9Y1AM5gQ07IYWlJI8/sfkL/Rm0/OWta9g+h1Jp5YfBKvD+EYO7mBB8prEc0cCUIdVnzp6Z9PsD9rPrTcW+ow25k3fsCBayoAPqpFioFT4z8so5Ofs6vVwWJaEmWfS0se2W4l2MoMoK2fysylDf+zy/nI70Arp4luhMxgAcxx0DfJHMzXFCeLGETsYPcbJbcu/thbVN6o2+XxL96Qfv1jS2E5+HdcLpzgOmNSKbzYdaL92/W6twWsBcFX3tqaE67tTPVW4NEc+C1tJzdRHDHbAgNUNMqlnryS3B0gIEor05QSeHF2Taem4od2V4fdfBm8xuWUZCBJyOpONBimfK/qibMAVJBGy15N10HsyQeWVxD1OR813W64rSubkwjOH4inKMHI45B0NSRTiwe5BNYJ/erKTHpNLpoObS9Cyc+IBBAz9dPJ1xWMjC+bq6FIp4fVZh0OuZp/A0XcvexSAWT9d5TEOd4/HSUleW1A5qR/DlNpxHeoZv1st5e82q2U0i6CevTEUAEhPWkn7OvYsyIgRByWyuGLcBlfzk96CTf5wHUPx8ATmEVJXIHXCBzBrOakWYY9BxuHlqvesH+DtaoR3TcSgZUCUg+66UyQ+0mVbS71ntNTurE6zSmn5+LXDp3X2PbTcoD+M9g3MXq+MV7okQfqBh6LgCD991HkjrQmhzrvBXShONM8VJLr6ZcY88q+FcDA0ewEQFkbSKtZp"
`endif