// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// This is an auto-generated file. Do not edit this file.
// hs_st_dbg_host_endpoint.sv

`timescale 1 ns / 1 ns

package hs_st_dbg_host_endpoint_wpackage;

function integer nonzero;
input integer value;
begin
	nonzero = (value > 0) ? value : 1;
end
endfunction

endpackage

module hs_st_dbg_host_endpoint_wrapper
    import hs_st_dbg_host_endpoint_wpackage::nonzero;
#(
    parameter DATA_WIDTH                 = 8,
    parameter NAME                       = "",
    parameter HOST_TYPE                  = "\"MANAGED_BY_ST_SERVER\"",
    parameter CLOCK_PRIORITY             = 0,
    parameter TYPE_NAME                  = 0,
    parameter INSTANCE_NAME              = 0,
    parameter CLOCK_RATE_HOST_CLK        = 0
) (
    input         clk,
    input         reset,
    output        h2t_ready,
    input         h2t_valid,
    input  [DATA_WIDTH-1:0] h2t_data,
    input         h2t_startofpacket,
    input         h2t_endofpacket,
    input  [nonzero($clog2(DATA_WIDTH) - 3)-1:0] h2t_empty,
    input  [11-1:0] h2t_channel,
    input  [8-1:0] h2t_connection_id,
    input         t2h_ready,
    output        t2h_valid,
    output [DATA_WIDTH-1:0] t2h_data,
    output        t2h_startofpacket,
    output        t2h_endofpacket,
    output [nonzero($clog2(DATA_WIDTH) - 3)-1:0] t2h_empty,
    output [11-1:0] t2h_channel,
    output [8-1:0] t2h_connection_id,
    output        mgmt_ready,
    input         mgmt_valid,
    input         mgmt_data,
    input         mgmt_startofpacket,
    input         mgmt_endofpacket,
    input  [4-1:0] mgmt_channel,
    input         mgmt_resp_ready,
    output        mgmt_resp_valid,
    output        mgmt_resp_data,
    output        mgmt_resp_startofpacket,
    output        mgmt_resp_endofpacket,
    output [4-1:0] mgmt_resp_channel
);

	hs_st_dbg_host_endpoint #(
        .DATA_WIDTH                 (DATA_WIDTH),
        .NAME                       (NAME),
        .HOST_TYPE                  (HOST_TYPE),
        .CLOCK_PRIORITY             (CLOCK_PRIORITY),
        .TYPE_NAME                  (TYPE_NAME),
        .INSTANCE_NAME              (INSTANCE_NAME),
        .CLOCK_RATE_HOST_CLK        (CLOCK_RATE_HOST_CLK)
) inst (
        .clk                        (clk),
        .reset                      (reset),
        .h2t_ready                  (h2t_ready),
        .h2t_valid                  (h2t_valid),
        .h2t_data                   (h2t_data),
        .h2t_startofpacket          (h2t_startofpacket),
        .h2t_endofpacket            (h2t_endofpacket),
        .h2t_empty                  (h2t_empty),
        .h2t_channel                (h2t_channel),
        .h2t_connection_id          (h2t_connection_id),
        .t2h_ready                  (t2h_ready),
        .t2h_valid                  (t2h_valid),
        .t2h_data                   (t2h_data),
        .t2h_startofpacket          (t2h_startofpacket),
        .t2h_endofpacket            (t2h_endofpacket),
        .t2h_empty                  (t2h_empty),
        .t2h_channel                (t2h_channel),
        .t2h_connection_id          (t2h_connection_id),
        .mgmt_ready                 (mgmt_ready),
        .mgmt_valid                 (mgmt_valid),
        .mgmt_data                  (mgmt_data),
        .mgmt_startofpacket         (mgmt_startofpacket),
        .mgmt_endofpacket           (mgmt_endofpacket),
        .mgmt_channel               (mgmt_channel),
        .mgmt_resp_ready            (mgmt_resp_ready),
        .mgmt_resp_valid            (mgmt_resp_valid),
        .mgmt_resp_data             (mgmt_resp_data),
        .mgmt_resp_startofpacket    (mgmt_resp_startofpacket),
        .mgmt_resp_endofpacket      (mgmt_resp_endofpacket),
        .mgmt_resp_channel          (mgmt_resp_channel)
	
	);

endmodule

// synthesis translate_off
// Empty module definition to allow simulation compilation.
module hs_st_dbg_host_endpoint
    import hs_st_dbg_host_endpoint_wpackage::nonzero;
#(
    parameter DATA_WIDTH                 = 8,
    parameter NAME                       = "",
    parameter HOST_TYPE                  = "\"MANAGED_BY_ST_SERVER\"",
    parameter CLOCK_PRIORITY             = 0,
    parameter TYPE_NAME                  = 0,
    parameter INSTANCE_NAME              = 0,
    parameter CLOCK_RATE_HOST_CLK        = 0
) (
    input         clk,
    input         reset,
    output        h2t_ready,
    input         h2t_valid,
    input  [DATA_WIDTH-1:0] h2t_data,
    input         h2t_startofpacket,
    input         h2t_endofpacket,
    input  [nonzero($clog2(DATA_WIDTH) - 3)-1:0] h2t_empty,
    input  [11-1:0] h2t_channel,
    input  [8-1:0] h2t_connection_id,
    input         t2h_ready,
    output        t2h_valid,
    output [DATA_WIDTH-1:0] t2h_data,
    output        t2h_startofpacket,
    output        t2h_endofpacket,
    output [nonzero($clog2(DATA_WIDTH) - 3)-1:0] t2h_empty,
    output [11-1:0] t2h_channel,
    output [8-1:0] t2h_connection_id,
    output        mgmt_ready,
    input         mgmt_valid,
    input         mgmt_data,
    input         mgmt_startofpacket,
    input         mgmt_endofpacket,
    input  [4-1:0] mgmt_channel,
    input         mgmt_resp_ready,
    output        mgmt_resp_valid,
    output        mgmt_resp_data,
    output        mgmt_resp_startofpacket,
    output        mgmt_resp_endofpacket,
    output [4-1:0] mgmt_resp_channel
);
endmodule
// synthesis translate_on

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "KaCcZ9W53ZG+KOUC3MpOxTkG8JzVU+FMIR8JyDs33NK1wcErIABMqJM+BlBnaEf20FCKJ7ToOlAha/ltC5u0ZbClu2TybZQciMInF+iFoiagt+B91BK4dyi6GJUCXUDuBK9YH6nNlwSkR01tHuzzS5ZEiJtw78iQaS7cFEmJNjv/muideRZVdy13EnGEeyFpK62Cg4KcVOZTCHinGABXbAtq/uBBjPG6GClkBmeTng0rIZERAGH70nfvIrNWLeAuOaTn9n32wI0VojbxZHxfQUa/JFkZE02Jx3hN35ToiuLwMq72mXmRhzXT5yIGRniRnSsOhIceMv1+tSrqDByYJMNs9VXDp+U1BQKfZpT/eFdnbXfCJ3zaPTQ/vdiXmYOjI9QXa+y4c34jaQeuOpifi8EZ9YU3FPoYY5b0DlHaQbvkIuzc//OdKhaKV6sGPT6/LxW9SUVSsq3RPiEcVQwQoYUSyoGgHh/ghHXrkeb+UP7c6z+D2lmutqUehKRRS1ElHXa1oZOYhqEPjbRL4b2Zqw63wSvZzTj2gFVMkDvSjsviDwXI/AEu2DS2Vhu6+JEp+OwP3QJ4znBI8/fv8XA88pMPaLGoKDmXmdzjzlHIpsXlAJu/uQzfF6j0Z+40zQYiPxhPbhjz1X6+SG+B/KSqfefA/NWZV83t4Hw/u+tamVT2ANYnYy/qPACHggy5N8B6yi6qecaKnuHMk+pxjU0f9CcIn635hUXutZHPZimRTR2ALmQBTluZqnkXCn588cu/U9VJpawQ6TrkROIrxK7QUqpfQ2QB4+3JzSJ5FwZHwd/SCGR3iy57xsSKRxvoMLviw5RbwsiCWFgmZe5I5mVFOoTTZjFMFc3X/ryZKxm7JJE2W3FOl7lRRZsj8pUvZJ4QtQylXwSzuDogiYxOaPEycf1tge8BDNjF/srZyXIdL/09SKDcooN6XL8eNIRAuAsJqGXSUHd/I4elVzelpzIy7KBkghnU1BUg+FdaC/rE028qCX4qkCzhPl7+mlwix3AS"
`endif