# (C) 2001-2025 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# (C) 2001-2025 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.
# This is an auto-generated file. Do not edit this file.

# 
# hs_st_dbg_host_endpoint "hs_st_dbg_host_endpoint" v1.0
# 

# request TCL package from ACDS 24.3
# 
package require -exact qsys 20.1

# 
# module hs_st_dbg_host_endpoint
# 
set_module_property NAME hs_st_dbg_host_endpoint
set_module_property AUTHOR "Intel Corporation"
set_module_property GROUP "Verification/Debug & Performance"
set_module_property VERSION 19.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME hs_st_dbg_host_endpoint
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK true
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property ELABORATION_CALLBACK elaborate
set_module_assignment debug.virtualInterface.link {debug.fabricLink {fabric credit_stream} }
set_module_assignment debug.isTransparent true

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hs_st_dbg_host_endpoint_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file hs_st_dbg_host_endpoint_wrapper.sv system_verilog path hs_st_dbg_host_endpoint_wrapper.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hs_st_dbg_host_endpoint_wrapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file hs_st_dbg_host_endpoint_wrapper.sv system_verilog path hs_st_dbg_host_endpoint_wrapper.sv

add_fileset CDC CDC "" ""
set_fileset_property CDC TOP_LEVEL hs_st_dbg_host_endpoint_wrapper
set_fileset_property CDC ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file hs_st_dbg_host_endpoint_wrapper.sv system_verilog path hs_st_dbg_host_endpoint_wrapper.sv

# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32 64 128 256 512 1024}
set_parameter_property DATA_WIDTH AFFECTS_ELABORATION true
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true

add_parameter NAME STRING {}
set_parameter_property NAME AFFECTS_ELABORATION true
set_parameter_property NAME AFFECTS_GENERATION false
set_parameter_property NAME HDL_PARAMETER true

add_parameter HOST_TYPE STRING MANAGED_BY_ST_SERVER
set_parameter_property HOST_TYPE AFFECTS_ELABORATION false
set_parameter_property HOST_TYPE AFFECTS_GENERATION false
set_parameter_property HOST_TYPE HDL_PARAMETER true

add_parameter CLOCK_PRIORITY INTEGER 0
set_parameter_property CLOCK_PRIORITY AFFECTS_ELABORATION false
set_parameter_property CLOCK_PRIORITY AFFECTS_GENERATION false
set_parameter_property CLOCK_PRIORITY HDL_PARAMETER true

add_parameter TYPE_NAME STRING 0
set_parameter_property TYPE_NAME AFFECTS_ELABORATION false
set_parameter_property TYPE_NAME AFFECTS_GENERATION false
set_parameter_property TYPE_NAME HDL_PARAMETER true

add_parameter INSTANCE_NAME STRING 0
set_parameter_property INSTANCE_NAME AFFECTS_ELABORATION false
set_parameter_property INSTANCE_NAME AFFECTS_GENERATION false
set_parameter_property INSTANCE_NAME HDL_PARAMETER true

add_parameter CLOCK_RATE_HOST_CLK INTEGER 0
set_parameter_property CLOCK_RATE_HOST_CLK SYSTEM_INFO {CLOCK_RATE host_clk}
set_parameter_property CLOCK_RATE_HOST_CLK AFFECTS_ELABORATION false
set_parameter_property CLOCK_RATE_HOST_CLK AFFECTS_GENERATION false
set_parameter_property CLOCK_RATE_HOST_CLK HDL_PARAMETER true


# 
# display items
# 

#
# connection point host_clk
#
add_interface host_clk clock end
set_interface_property host_clk ENABLED true
add_interface_port host_clk clk clk Input 1


#
# connection point host_reset
#
add_interface host_reset reset end
set_interface_property host_reset associatedClock host_clk
set_interface_property host_reset ENABLED true
add_interface_port host_reset reset reset Input 1


#
# connection point host_h2t_snk
#
add_interface host_h2t_snk avalon_streaming end
set_interface_property host_h2t_snk beatsPerCycle 1
set_interface_property host_h2t_snk dataBitsPerSymbol 8
set_interface_property host_h2t_snk firstSymbolInHighOrderBits 0
set_interface_property host_h2t_snk maxChannel 2047
set_interface_property host_h2t_snk prSafe 0
set_interface_property host_h2t_snk readyAllowance 0
set_interface_property host_h2t_snk readyLatency 0
set_interface_property host_h2t_snk associatedClock host_clk
set_interface_property host_h2t_snk associatedReset host_reset
set_interface_property host_h2t_snk ENABLED true
set_interface_assignment host_h2t_snk debug.controlledBy {link}
set_interface_assignment host_h2t_snk debug.hostConnection {type remote}
set_interface_assignment host_h2t_snk debug.providesServices {deviceConn}
add_interface_port host_h2t_snk h2t_ready ready Output 1
add_interface_port host_h2t_snk h2t_valid valid Input 1
add_interface_port host_h2t_snk h2t_data data Input DATA_WIDTH
add_interface_port host_h2t_snk h2t_startofpacket startofpacket Input 1
add_interface_port host_h2t_snk h2t_endofpacket endofpacket Input 1
add_interface_port host_h2t_snk h2t_empty empty Input 1
set_port_property h2t_empty termination true
add_interface_port host_h2t_snk h2t_channel channel Input 11


#
# connection point host_h2t_snk_connection_id
#
add_interface host_h2t_snk_connection_id conduit end
set_interface_property host_h2t_snk_connection_id associatedClock host_clk
set_interface_property host_h2t_snk_connection_id associatedReset host_reset
set_interface_property host_h2t_snk_connection_id ENABLED true
add_interface_port host_h2t_snk_connection_id h2t_connection_id conn_id Input 8


#
# connection point host_t2h_src
#
add_interface host_t2h_src avalon_streaming start
set_interface_property host_t2h_src beatsPerCycle 1
set_interface_property host_t2h_src dataBitsPerSymbol 8
set_interface_property host_t2h_src firstSymbolInHighOrderBits 0
set_interface_property host_t2h_src maxChannel 2047
set_interface_property host_t2h_src prSafe 0
set_interface_property host_t2h_src readyAllowance 0
set_interface_property host_t2h_src readyLatency 0
set_interface_property host_t2h_src associatedClock host_clk
set_interface_property host_t2h_src associatedReset host_reset
set_interface_property host_t2h_src ENABLED true
add_interface_port host_t2h_src t2h_ready ready Input 1
add_interface_port host_t2h_src t2h_valid valid Output 1
add_interface_port host_t2h_src t2h_data data Output DATA_WIDTH
add_interface_port host_t2h_src t2h_startofpacket startofpacket Output 1
add_interface_port host_t2h_src t2h_endofpacket endofpacket Output 1
add_interface_port host_t2h_src t2h_empty empty Output 1
set_port_property t2h_empty termination true
add_interface_port host_t2h_src t2h_channel channel Output 11


#
# connection point host_t2h_src_connection_id
#
add_interface host_t2h_src_connection_id conduit start
set_interface_property host_t2h_src_connection_id associatedClock host_clk
set_interface_property host_t2h_src_connection_id associatedReset host_reset
set_interface_property host_t2h_src_connection_id ENABLED true
add_interface_port host_t2h_src_connection_id t2h_connection_id conn_id Output 8


#
# connection point mgmt_snk
#
add_interface mgmt_snk avalon_streaming end
set_interface_property mgmt_snk beatsPerCycle 1
set_interface_property mgmt_snk dataBitsPerSymbol 1
set_interface_property mgmt_snk firstSymbolInHighOrderBits 1
set_interface_property mgmt_snk maxChannel 15
set_interface_property mgmt_snk prSafe 0
set_interface_property mgmt_snk readyAllowance 0
set_interface_property mgmt_snk readyLatency 0
set_interface_property mgmt_snk associatedClock host_clk
set_interface_property mgmt_snk associatedReset host_reset
set_interface_property mgmt_snk ENABLED true
add_interface_port mgmt_snk mgmt_ready ready Output 1
add_interface_port mgmt_snk mgmt_valid valid Input 1
add_interface_port mgmt_snk mgmt_data data Input 1
add_interface_port mgmt_snk mgmt_startofpacket startofpacket Input 1
add_interface_port mgmt_snk mgmt_endofpacket endofpacket Input 1
add_interface_port mgmt_snk mgmt_channel channel Input 4


#
# connection point mgmt_resp_src
#
add_interface mgmt_resp_src avalon_streaming start
set_interface_property mgmt_resp_src beatsPerCycle 1
set_interface_property mgmt_resp_src dataBitsPerSymbol 1
set_interface_property mgmt_resp_src firstSymbolInHighOrderBits 1
set_interface_property mgmt_resp_src maxChannel 15
set_interface_property mgmt_resp_src prSafe 0
set_interface_property mgmt_resp_src readyAllowance 0
set_interface_property mgmt_resp_src readyLatency 0
set_interface_property mgmt_resp_src associatedClock host_clk
set_interface_property mgmt_resp_src associatedReset host_reset
set_interface_property mgmt_resp_src ENABLED true
add_interface_port mgmt_resp_src mgmt_resp_ready ready Input 1
add_interface_port mgmt_resp_src mgmt_resp_valid valid Output 1
add_interface_port mgmt_resp_src mgmt_resp_data data Output 1
add_interface_port mgmt_resp_src mgmt_resp_startofpacket startofpacket Output 1
add_interface_port mgmt_resp_src mgmt_resp_endofpacket endofpacket Output 1
add_interface_port mgmt_resp_src mgmt_resp_channel channel Output 4


#
# Elaboration callback
#
proc elaborate {} {
    set DATA_WIDTH [get_parameter_value DATA_WIDTH]
    set NAME [get_parameter_value NAME]

    if {!($NAME != {})} {
        send_message {error text} {NAME must be specified}
    }

    if {$DATA_WIDTH > 8} {
        set_port_property h2t_empty width_expr [expr {[log2 $DATA_WIDTH] - 3} ]
        set_port_property h2t_empty termination false
        set_port_property t2h_empty width_expr [expr {[log2 $DATA_WIDTH] - 3} ]
        set_port_property t2h_empty termination false
    }
}

proc log2 x {expr {int(ceil(log($x) / log(2)))}}
