// qual_test_rst.v

// Generated using ACDS version 26.1.1 130

`timescale 1 ps / 1 ps
module qual_test_rst (
		input  wire  clk,         //       clk.clk,     Clock Input
		input  wire  in_reset_n,  //  in_reset.reset_n, Reset Input
		output wire  out_reset_n  // out_reset.reset_n, Reset Output
	);

	assign out_reset_n = in_reset_n;

endmodule
