// Copyright 2001-2023 Intel Corporation
// SPDX-License-Identifier: MIT


`timescale 1ps/1ps

// DESCRIPTION
// 14 input XOR gate.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module alt_e2550_xor14t1_hn #(
//    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [13:0] din,
    output dout
);

wire [2:0] leaf;

alt_e2550_xor5t1_hn c0 (
    .clk(clk),
    .din(din[4:0]),
    .dout(leaf[0])
);
//defparam c0 .SIM_EMULATE = SIM_EMULATE;

alt_e2550_xor5t1_hn c1 (
    .clk(clk),
    .din(din[9:5]),
    .dout(leaf[1])
);
//defparam c1 .SIM_EMULATE = SIM_EMULATE;

alt_e2550_xor4t1_hn c2 (
    .clk(clk),
    .din(din[13:10]),
    .dout(leaf[2])
);
//defparam c2 .SIM_EMULATE = SIM_EMULATE;

alt_e2550_xor3t0_hn c3 (
    .din(leaf),
    .dout(dout)
);
//defparam c3 .SIM_EMULATE = SIM_EMULATE;

endmodule

