//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_examples_afu01/sources/clocks/hw/rtl/clock_freq_uClk_auto.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "clock_freq_test"
`define AFU_ACCEL_NAME0 "clock_freq_test"
`define AFU_ACCEL_UUID 128'hbd9ccef3_0b2c_4bb2_901f_6c7486821188
`define AFU_ACCEL_UUID0 128'hbd9ccef3_0b2c_4bb2_901f_6c7486821188
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
