// mem_ss_mem_ss_501_qm5zaka_msa_1.v

// Generated using ACDS version 26.1.1 130

`timescale 1 ps / 1 ps
module mem_ss_mem_ss_501_qm5zaka_msa_1 (
		input  wire         s_clk,                   //               s_clk.clk
		input  wire         s_reset_n,               //             s_reset.reset_n
		input  wire         m_clk,                   //               m_clk.clk
		input  wire         m_reset_n,               //             m_reset.reset_n
		output wire         s_axi4_awready,          //              s_axi4.awready
		input  wire         s_axi4_awvalid,          //                    .awvalid
		input  wire [8:0]   s_axi4_awid,             //                    .awid
		input  wire [33:0]  s_axi4_awaddr,           //                    .awaddr
		input  wire [7:0]   s_axi4_awlen,            //                    .awlen
		input  wire [2:0]   s_axi4_awsize,           //                    .awsize
		input  wire [1:0]   s_axi4_awburst,          //                    .awburst
		input  wire         s_axi4_awlock,           //                    .awlock
		input  wire [3:0]   s_axi4_awcache,          //                    .awcache
		input  wire [2:0]   s_axi4_awprot,           //                    .awprot
		input  wire [3:0]   s_axi4_awqos,            //                    .awqos
		input  wire [13:0]  s_axi4_awuser,           //                    .awuser
		output wire         s_axi4_arready,          //                    .arready
		input  wire         s_axi4_arvalid,          //                    .arvalid
		input  wire [8:0]   s_axi4_arid,             //                    .arid
		input  wire [33:0]  s_axi4_araddr,           //                    .araddr
		input  wire [7:0]   s_axi4_arlen,            //                    .arlen
		input  wire [2:0]   s_axi4_arsize,           //                    .arsize
		input  wire [1:0]   s_axi4_arburst,          //                    .arburst
		input  wire         s_axi4_arlock,           //                    .arlock
		input  wire [3:0]   s_axi4_arcache,          //                    .arcache
		input  wire [2:0]   s_axi4_arprot,           //                    .arprot
		input  wire [3:0]   s_axi4_arqos,            //                    .arqos
		input  wire [13:0]  s_axi4_aruser,           //                    .aruser
		output wire         s_axi4_wready,           //                    .wready
		input  wire         s_axi4_wvalid,           //                    .wvalid
		input  wire [511:0] s_axi4_wdata,            //                    .wdata
		input  wire [63:0]  s_axi4_wstrb,            //                    .wstrb
		input  wire         s_axi4_wlast,            //                    .wlast
		input  wire         s_axi4_bready,           //                    .bready
		output wire         s_axi4_bvalid,           //                    .bvalid
		output wire [8:0]   s_axi4_bid,              //                    .bid
		output wire [1:0]   s_axi4_bresp,            //                    .bresp
		output wire         s_axi4_buser,            //                    .buser
		input  wire         s_axi4_rready,           //                    .rready
		output wire         s_axi4_rvalid,           //                    .rvalid
		output wire [8:0]   s_axi4_rid,              //                    .rid
		output wire [1:0]   s_axi4_rresp,            //                    .rresp
		output wire [511:0] s_axi4_rdata,            //                    .rdata
		output wire         s_axi4_rlast,            //                    .rlast
		input  wire         m_avmm_ready,            //              m_avmm.waitrequest_n,          Deasserted by the responder when it is unable to respond to a read or write request
		output wire         m_avmm_read,             //                    .read,                   Read request signal
		output wire         m_avmm_write,            //                    .write,                  Write request signal
		output wire [33:0]  m_avmm_address,          //                    .address,                Word address for the read/write request
		output wire [6:0]   m_avmm_burstcount,       //                    .burstcount,             During the first cycle of a burst, burstcount indicates the number of transfers the read/write burst contains. The minimum burstcount is 1
		output wire [511:0] m_avmm_writedata,        //                    .writedata,              Data signal from the initiator for write transfers
		output wire [63:0]  m_avmm_byteenable,       //                    .byteenable,             Enables specific byte lane(s) during transfers. Each bit in byteenable corresponds to a byte in writedata. The host bit <n> of byteenable indicates whether byte <n> is being written to. During writes, byteenables specify which bytes to write. Other bytes are ignored by the responder.
		input  wire [511:0] m_avmm_readdata,         //                    .readdata,               The readdata provided by the responder in response to a read transfer
		input  wire         m_avmm_readdatavalid,    //                    .readdatavalid,          Asserted by the responder to indicate that the readdata signal contains valid data in response to a previous read request
		output wire         local_cal_success,       //              status.local_cal_success
		output wire         local_cal_fail,          //                    .local_cal_fail
		input  wire         local_cal_success_in,    //           status_in.local_cal_success
		input  wire         local_cal_fail_in,       //                    .local_cal_fail
		output wire         ctrl_auto_precharge_req  // ctrl_auto_precharge.ctrl_auto_precharge_req
	);

	mem_ss_msa_top #(
		.DEVICE_FAMILY       ("Agilex 7"),
		.NUM_USER_POOLS      (1),
		.SCHEDULER_POLICY    ("TXN_WINDOW"),
		.READY_LATENCY       (3),
		.VALID_LATENCY       (0),
		.ROW_ADDR_WIDTH      (17),
		.COL_ADDR_WIDTH      (10),
		.BANK_ADDR_WIDTH     (2),
		.BANK_GROUP_WIDTH    (2),
		.CHIP_ID_WIDTH       (0),
		.CHIP_SELECT_WIDTH   (1),
		.MBL_TRAFFIC_EN      (0),
		.AUTO_PRECHARGE      ("SS_CONTROLLED"),
		.NUM_COPIES          (1),
		.NUM_BANK_FIFOS      (8),
		.SCHEDULER_NUM_READ  (512),
		.SCHEDULER_NUM_WRITE (512),
		.ASYNC_EN            (0),
		.RESP_USE_WSTRB      (1),
		.INIT_ID_WIDTH       (9),
		.INIT_AWADDR_WIDTH   (34),
		.INIT_ARADDR_WIDTH   (34),
		.RESP_ID_WIDTH       (9),
		.RESP_AWADDR_WIDTH   (34),
		.RESP_ARADDR_WIDTH   (34),
		.RESP_WDATA_WIDTH    (512),
		.RESP_USE_WUSER      (0),
		.RESP_WUSER_WIDTH    (1),
		.RESP_RDATA_WIDTH    (512),
		.RESP_USE_RUSER      (0),
		.RESP_RUSER_WIDTH    (1),
		.INIT_WDATA_WIDTH    (512),
		.INIT_USE_WUSER      (0),
		.INIT_WUSER_WIDTH    (32),
		.INIT_RDATA_WIDTH    (512),
		.INIT_USE_RUSER      (0),
		.INIT_RUSER_WIDTH    (32)
	) msa_1 (
		.s_clk                   (s_clk),                   //   input,    width = 1,               s_clk.clk
		.s_reset_n               (s_reset_n),               //   input,    width = 1,             s_reset.reset_n
		.m_clk                   (m_clk),                   //   input,    width = 1,               m_clk.clk
		.m_reset_n               (m_reset_n),               //   input,    width = 1,             m_reset.reset_n
		.s_axi4_awready          (s_axi4_awready),          //  output,    width = 1,              s_axi4.awready
		.s_axi4_awvalid          (s_axi4_awvalid),          //   input,    width = 1,                    .awvalid
		.s_axi4_awid             (s_axi4_awid),             //   input,    width = 9,                    .awid
		.s_axi4_awaddr           (s_axi4_awaddr),           //   input,   width = 34,                    .awaddr
		.s_axi4_awlen            (s_axi4_awlen),            //   input,    width = 8,                    .awlen
		.s_axi4_awsize           (s_axi4_awsize),           //   input,    width = 3,                    .awsize
		.s_axi4_awburst          (s_axi4_awburst),          //   input,    width = 2,                    .awburst
		.s_axi4_awlock           (s_axi4_awlock),           //   input,    width = 1,                    .awlock
		.s_axi4_awcache          (s_axi4_awcache),          //   input,    width = 4,                    .awcache
		.s_axi4_awprot           (s_axi4_awprot),           //   input,    width = 3,                    .awprot
		.s_axi4_awqos            (s_axi4_awqos),            //   input,    width = 4,                    .awqos
		.s_axi4_awuser           (s_axi4_awuser),           //   input,   width = 14,                    .awuser
		.s_axi4_arready          (s_axi4_arready),          //  output,    width = 1,                    .arready
		.s_axi4_arvalid          (s_axi4_arvalid),          //   input,    width = 1,                    .arvalid
		.s_axi4_arid             (s_axi4_arid),             //   input,    width = 9,                    .arid
		.s_axi4_araddr           (s_axi4_araddr),           //   input,   width = 34,                    .araddr
		.s_axi4_arlen            (s_axi4_arlen),            //   input,    width = 8,                    .arlen
		.s_axi4_arsize           (s_axi4_arsize),           //   input,    width = 3,                    .arsize
		.s_axi4_arburst          (s_axi4_arburst),          //   input,    width = 2,                    .arburst
		.s_axi4_arlock           (s_axi4_arlock),           //   input,    width = 1,                    .arlock
		.s_axi4_arcache          (s_axi4_arcache),          //   input,    width = 4,                    .arcache
		.s_axi4_arprot           (s_axi4_arprot),           //   input,    width = 3,                    .arprot
		.s_axi4_arqos            (s_axi4_arqos),            //   input,    width = 4,                    .arqos
		.s_axi4_aruser           (s_axi4_aruser),           //   input,   width = 14,                    .aruser
		.s_axi4_wready           (s_axi4_wready),           //  output,    width = 1,                    .wready
		.s_axi4_wvalid           (s_axi4_wvalid),           //   input,    width = 1,                    .wvalid
		.s_axi4_wdata            (s_axi4_wdata),            //   input,  width = 512,                    .wdata
		.s_axi4_wstrb            (s_axi4_wstrb),            //   input,   width = 64,                    .wstrb
		.s_axi4_wlast            (s_axi4_wlast),            //   input,    width = 1,                    .wlast
		.s_axi4_bready           (s_axi4_bready),           //   input,    width = 1,                    .bready
		.s_axi4_bvalid           (s_axi4_bvalid),           //  output,    width = 1,                    .bvalid
		.s_axi4_bid              (s_axi4_bid),              //  output,    width = 9,                    .bid
		.s_axi4_bresp            (s_axi4_bresp),            //  output,    width = 2,                    .bresp
		.s_axi4_buser            (s_axi4_buser),            //  output,    width = 1,                    .buser
		.s_axi4_rready           (s_axi4_rready),           //   input,    width = 1,                    .rready
		.s_axi4_rvalid           (s_axi4_rvalid),           //  output,    width = 1,                    .rvalid
		.s_axi4_rid              (s_axi4_rid),              //  output,    width = 9,                    .rid
		.s_axi4_rresp            (s_axi4_rresp),            //  output,    width = 2,                    .rresp
		.s_axi4_rdata            (s_axi4_rdata),            //  output,  width = 512,                    .rdata
		.s_axi4_rlast            (s_axi4_rlast),            //  output,    width = 1,                    .rlast
		.m_avmm_ready            (m_avmm_ready),            //   input,    width = 1,              m_avmm.waitrequest_n
		.m_avmm_read             (m_avmm_read),             //  output,    width = 1,                    .read
		.m_avmm_write            (m_avmm_write),            //  output,    width = 1,                    .write
		.m_avmm_address          (m_avmm_address),          //  output,   width = 34,                    .address
		.m_avmm_burstcount       (m_avmm_burstcount),       //  output,    width = 7,                    .burstcount
		.m_avmm_writedata        (m_avmm_writedata),        //  output,  width = 512,                    .writedata
		.m_avmm_byteenable       (m_avmm_byteenable),       //  output,   width = 64,                    .byteenable
		.m_avmm_readdata         (m_avmm_readdata),         //   input,  width = 512,                    .readdata
		.m_avmm_readdatavalid    (m_avmm_readdatavalid),    //   input,    width = 1,                    .readdatavalid
		.local_cal_success       (local_cal_success),       //  output,    width = 1,              status.local_cal_success
		.local_cal_fail          (local_cal_fail),          //  output,    width = 1,                    .local_cal_fail
		.local_cal_success_in    (local_cal_success_in),    //   input,    width = 1,           status_in.local_cal_success
		.local_cal_fail_in       (local_cal_fail_in),       //   input,    width = 1,                    .local_cal_fail
		.ctrl_auto_precharge_req (ctrl_auto_precharge_req), //  output,    width = 1, ctrl_auto_precharge.ctrl_auto_precharge_req
		.s_axi4_wuser            (1'b0),                    // (terminated),                                   
		.s_axi4_ruser            (),                        // (terminated),                                   
		.ctrl_user_priority_hi   (),                        // (terminated),                                   
		.ctrl_ecc_user_interrupt (1'b0),                    // (terminated),                                   
		.ctrl_ecc_readdataerror  (1'b0),                    // (terminated),                                   
		.msa_csr_slverr          (),                        // (terminated),                                   
		.msa_csr_decerr          ()                         // (terminated),                                   
	);

endmodule
