// (C) 2001-2026 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// This is an auto-generated file. Do not edit this file.
// altera_sld_host_endpoint.sv

`timescale 1 ns / 1 ns

package altera_sld_host_endpoint_wpackage;

function integer nonzero;
input integer value;
begin
	nonzero = (value > 0) ? value : 1;
end
endfunction

endpackage

module altera_sld_host_endpoint_wrapper
    import altera_sld_host_endpoint_wpackage::nonzero;
#(
    parameter ENABLE_JTAG_IO_SELECTION = 0,
    parameter CONTROL        = "host",
    parameter NAME           = "",
    parameter HOST_PRIORITY  = 0,
    parameter BRIDGE_HOST    = 0,
    parameter USE_TCK_ENA    = 0,
    parameter NEGEDGE_TDO_LATCH = 0,
    parameter TYPE_NAME      = 0,
    parameter INSTANCE_NAME  = 0,
    parameter CLTAP_CONNECTION = 0,
    parameter CLOCK_RATE_CLOCK = 0
) (
    input         tck,
    input         tms,
    input         tdi,
    input         ena,
    input         vir_tdi,
    input         tck_ena,
    output        tdo,
    input         select_this
);

	altera_sld_host_endpoint #(
        .ENABLE_JTAG_IO_SELECTION (ENABLE_JTAG_IO_SELECTION),
        .CONTROL        (CONTROL),
        .NAME           (NAME),
        .HOST_PRIORITY  (HOST_PRIORITY),
        .BRIDGE_HOST    (BRIDGE_HOST),
        .USE_TCK_ENA    (USE_TCK_ENA),
        .NEGEDGE_TDO_LATCH (NEGEDGE_TDO_LATCH),
        .TYPE_NAME      (TYPE_NAME),
        .INSTANCE_NAME  (INSTANCE_NAME),
        .CLTAP_CONNECTION (CLTAP_CONNECTION),
        .CLOCK_RATE_CLOCK (CLOCK_RATE_CLOCK)
) inst (
        .tck            (tck),
        .tms            (tms),
        .tdi            (tdi),
        .ena            (ena),
        .vir_tdi        (vir_tdi),
        .tck_ena        (tck_ena),
        .tdo            (tdo),
        .select_this    (select_this)
	
	);

endmodule

// synthesis translate_off
// Empty module definition to allow simulation compilation.
module altera_sld_host_endpoint
    import altera_sld_host_endpoint_wpackage::nonzero;
#(
    parameter ENABLE_JTAG_IO_SELECTION = 0,
    parameter CONTROL        = "host",
    parameter NAME           = "",
    parameter HOST_PRIORITY  = 0,
    parameter BRIDGE_HOST    = 0,
    parameter USE_TCK_ENA    = 0,
    parameter NEGEDGE_TDO_LATCH = 0,
    parameter TYPE_NAME      = 0,
    parameter INSTANCE_NAME  = 0,
    parameter CLTAP_CONNECTION = 0,
    parameter CLOCK_RATE_CLOCK = 0
) (
    input         tck,
    input         tms,
    input         tdi,
    input         ena,
    input         vir_tdi,
    input         tck_ena,
    output        tdo,
    input         select_this
);
endmodule
// synthesis translate_on

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "gRBYFlNQxYnRTO9KUVrWXlQf7f+VErv2IMqbs4q7wIH1aHGT4/ZAz3XjsUAGUBJ6EI/9L44us+WSxVgH1+YGU5lT0kLbQJo6GJkzmcbhnY+7DnbMunu1lNcJ0m8k3E8VMtxLcwfwt0KweFhjUvOzqTscsa07hwuYMWv6mcDzHNrr2IOOQ4S0QadoTDB1QDMpyOPmEV/RQDXpDuousbhPfVBl/xI/iWXbCEfmfZhTSWie5QMwZvYSEiYitkMSnPPsW7NlLcSor5dJ7J2pbH3pSpBE0wG3QetL3RlDy5s3lUuhnVSgpAR3Yh2iBDTJJ26BlgF/Ew8wJdAPxsE4ry3IWYdVKFw/j7d1lvP6zAQo2Wt8Rq1wyrWPILfMjgivkG/1P1t7zmYopktB5S4O4VL5lfwQHwGz2J7KK1+V9tIIu7e7/QdXK8slmYW9bNPxUik4bSB+lFLSk30tFp3VcMKuny55BBRjS1NNk1eoC+LHDuYcjfkKaj+YMPZ/tMfOpnEBO172Fx7CpMIe8GcwaxBG8Ifhvyrpbzs+QgCB2pQRn2RyTX+vbdzWIg1yN7Bwj1HA9l18lK2FQm/1n2YozHuhqvBel0X1UKhVyMFHKFOb7CasNLNjMtJ64yeB88tTzM69IxkOBwnTlMTgaEObuDyQDBhe+Npsm4hVXJ6LUSYms8FPDLVv2S+UfDwp1BQTvowRdbMQG1q6CZ7mOHbwVPB1Hj+Km0Tws53Qot6XLUVk1xBS4UeoOVENQmwx5RRBtFUGinmaGOk3SMSO+ICk0g+Y7kaNLLI09QLSVTvmDvdPcfSisfEJgc/vbq3HZFITlOZdETLj/0bIogzm97iNifidKgSUo3XU9JwjYWkDsicaWafnktYUInWS0lYPZ8lUeWPVH6HEPhkZ3G4pdPqvoEw8IFvsSKYlpuQ9NwgFpnYHctFjz/N9aPpnnKmEl8r85Pgxy5hT6qjHZtq6j/AVm5AbvR8S9PV8bFdl8D3/XhNaNBesw2s3PBWwvKozOiSfh5SA"
`endif