###############################################################
# Top
###############################################################

PARAM_RUN_COMPOSE_NAME = Generate IPs within Subsystem
PARAM_RUN_COMPOSE_DESC = Generate IPs encapsulated within Subsystem. Enabling this will make GUI clicks take seconds to respond. You can disable this first to speed up GUI clicks, and after parameterization enable this to generate sub-IPs.

###############################################################
# Topology - Memory Interfaces
###############################################################

PARAM_MEM_INTFS_IDX_NAME = #
PARAM_MEM_INTFS_IDX_DESC = Serial number for each memory interface. This number is referenced in the Data Flow table.

PARAM_MEM_INTFS_TYPE_NAME = Type
PARAM_MEM_INTFS_TYPE_DESC = Type of memory interface indicative of the memory storage technology

   RANGE_MEM_INTFS_TYPE_DDR5COMP_NAME = External: DDR5 Component
   RANGE_MEM_INTFS_TYPE_DDR5DIMM_NAME = External: DDR5 DIMM
   RANGE_MEM_INTFS_TYPE_DDR4_NAME = External: DDR4
   RANGE_MEM_INTFS_TYPE_DDR4COMP_NAME = External: DDR4 Component
   RANGE_MEM_INTFS_TYPE_DDR4DIMM_NAME = External: DDR4 DIMM
   RANGE_MEM_INTFS_TYPE_LPDDR5_NAME = External: LPDDR5
   RANGE_MEM_INTFS_TYPE_LPDDR4_NAME = External: LPDDR4
   RANGE_MEM_INTFS_TYPE_HBM2E_NAME = In-package: HBM2E
   RANGE_MEM_INTFS_TYPE_M20K_NAME = On-chip: M20K

PARAM_MEM_INTFS_LOCATION_NAME = Location
PARAM_MEM_INTFS_LOCATION_DESC = Physical location of memory interface

   RANGE_MEM_INTFS_LOCATION_TOP_NAME = North I/O Row
   RANGE_MEM_INTFS_LOCATION_BOT_NAME = South I/O Row
   RANGE_MEM_INTFS_LOCATION_M20K_NAME = M20K Column

###############################################################
# Topology - Application interfaces
###############################################################

PARAM_APP_INTFS_IDX_NAME = #
PARAM_APP_INTFS_IDX_DESC = Serial number for each application interface. This number is referenced in the Data Flow table.

PARAM_APP_INTFS_TYPE_NAME = Type
PARAM_APP_INTFS_TYPE_DESC = Type of application interface facing the user logic

   RANGE_APP_INTFS_TYPE_STORAGE_NAME = Storage
   RANGE_APP_INTFS_TYPE_STORAGE_DESC = Memory-mapped fabric interface wherein memory storage locations are accessed by specifying address and data

   RANGE_APP_INTFS_TYPE_ASSOC_STORAGE_NAME = Associative Storage
   RANGE_APP_INTFS_TYPE_ASSOC_STORAGE_DESC = Streaming fabric interface wherein memory storage locations are accessed by specifying key and value

   RANGE_APP_INTFS_TYPE_HPS_NAME = Storage for HPS
   RANGE_APP_INTFS_TYPE_HPS_DESC = Hardened interface which connects to the Hard Processor System (HPS) IP

###############################################################
# Topology - Data Flow table
###############################################################

PARAM_COLLAPSE_HBM_CHANNELS_NAME = Collapse HBM channels
PARAM_COLLAPSE_HBM_CHANNELS_DESC = Collapse HBM channels for a more compact table layout. Any application interface connected to this collapsed HBM endpoint will connect to all HBM channels. For granular control over individual HBM channels don't collapse the channels.

PARAM_MEM_CONNS_LABELS_NAME = <html>&nbsp;</html>

###############################################################
# Implementation
###############################################################

PARAM_ENABLE_NOC_NAME = Use Network-on-Chip (NoC)
PARAM_ENABLE_NOC_DESC = Allow usage of the Network-on-Chip (NoC) to transport data between application interfaces and memory interfaces.

PARAM_ENABLE_MEM_CSR_INTF_NAME = Expose a sideband interface for memory interface components
PARAM_ENABLE_MEM_CSR_INTF_DESC = The sideband interface allows access to registers and diagnostic information within memory interface components such as the memory controller and calibration processor.

   RANGE_ENABLE_MEM_CSR_INTF_DISABLED_NAME = Disabled
   RANGE_ENABLE_MEM_CSR_INTF_DISABLED_DESC = Disable the sideband interface

   RANGE_ENABLE_MEM_CSR_INTF_ENABLED_NAME = Enabled
   RANGE_ENABLE_MEM_CSR_INTF_ENABLED_DESC = Expose a unified sideband interface for all memory interface components

   RANGE_ENABLE_MEM_CSR_INTF_DEDICATED_BRIDGE_NAME = Dedicated NoC Bridge
   RANGE_ENABLE_MEM_CSR_INTF_DEDICATED_BRIDGE_DESC = Expose a unified sideband interface using a dedicated NoC bridge.

   RANGE_ENABLE_MEM_CSR_INTF_SHARED_BRIDGE_NAME = Shared NoC Bridge
   RANGE_ENABLE_MEM_CSR_INTF_SHARED_BRIDGE_DESC = Expose a unified sideband interface sharing the NoC bridge with application interface #0. Sharing NoC bridges may limit application interface bandwidth but uses fewer NoC resources.

PARAM_ENABLE_MEM_PMON_NAME = Insert performance monitors at memory targets
PARAM_ENABLE_MEM_PMON_DESC = Insert performance monitors at the physical memory interface. If NoC is used, this would be at the boundary between NoC and memory target.

   RANGE_ENABLE_MEM_PMON_DISABLED_NAME = Disabled
   RANGE_ENABLE_MEM_PMON_DISABLED_DESC = No performance monitor will be instantiated

   RANGE_ENABLE_MEM_PMON_EXPORT_NAME = Access via sideband interface
   RANGE_ENABLE_MEM_PMON_EXPORT_DESC = Performance monitor data can be accessed over the sideband interface

   RANGE_ENABLE_MEM_PMON_TOOLKIT_NAME = Access via Toolkit GUI
   RANGE_ENABLE_MEM_PMON_TOOLKIT_DESC = Performance monitor data can be accessed using its Toolkit GUI

PARAM_ENABLE_NOC_PMON_NAME = Insert performance monitors at NoC ports / bridges / initiators
PARAM_ENABLE_NOC_PMON_DESC = Insert performance monitors at the NoC initiator

   RANGE_ENABLE_NOC_PMON_DISABLED_NAME = Disabled
   RANGE_ENABLE_NOC_PMON_DISABLED_DESC = No performance monitor will be instantiated

   RANGE_ENABLE_NOC_PMON_EXPORT_NAME = Access via sideband interface
   RANGE_ENABLE_NOC_PMON_EXPORT_DESC = Performance monitor data can be accessed over the sideband interface

PARAM_ENABLE_APP_PMON_NAME = Insert performance monitors at application interfaces
PARAM_ENABLE_APP_PMON_DESC = Insert performance monitors for all application interfaces. HPS application interface cannot be monitored.

   RANGE_ENABLE_APP_PMON_DISABLED_NAME = Disabled
   RANGE_ENABLE_APP_PMON_DISABLED_DESC = No performance monitor will be instantiated

   RANGE_ENABLE_APP_PMON_EXPORT_NAME = Access via sideband interface
   RANGE_ENABLE_APP_PMON_EXPORT_DESC = Performance monitor data can be accessed over the sideband interface

###############################################################
# Design Example - Filesets
###############################################################

PARAM_EX_DESIGN_HDL_FORMAT_NAME = HDL format
PARAM_EX_DESIGN_HDL_FORMAT_DESC = HDL design files will be generated in the chosen language

   RANGE_EX_DESIGN_HDL_FORMAT_VERILOG_NAME = Verilog
   RANGE_EX_DESIGN_HDL_FORMAT_VHDL_NAME = VHDL

PARAM_EX_DESIGN_GEN_SIM_NAME = Generate design example for simulation
PARAM_EX_DESIGN_GEN_SIM_DESC = '<b>Generate Design Example</b>' button will include a <tt>sim</tt> sub-directory containing the simulation file sets for various simulators. The design example contains the Memory Subsystem IP and a corresponding testbench according to your parameterization.

PARAM_EX_DESIGN_GEN_SYNTH_NAME = Generate design example for synthesis
PARAM_EX_DESIGN_GEN_SYNTH_DESC = '<b>Generate Design Example</b>' button will include a <tt>synth</tt> sub-directory containing the synthesis file set for Quartus. The design example contains the Memory Subsystem IP and a corresponding testbench according to your parameterization. After the design is created, you can run a full compilation and verify timing closure. Optionally, you can specify pin location assignments and test the IP on your board using the programming file created by Quartus compilation.

###############################################################
# Design Example - Hydra
###############################################################

PARAM_EX_DESIGN_HYDRA_HOST_INTF_NAME = Host interface
PARAM_EX_DESIGN_HYDRA_HOST_INTF_DESC = Enabling Test Engine's host interface allows access to Test Engine's Control and Status Registers (CSRs)

   RANGE_EX_DESIGN_HYDRA_HOST_INTF_DISABLED_NAME = Disabled
   RANGE_EX_DESIGN_HYDRA_HOST_INTF_DISABLED_DESC = No host interface

   RANGE_EX_DESIGN_HYDRA_HOST_INTF_EXPORT_NAME = Export
   RANGE_EX_DESIGN_HYDRA_HOST_INTF_EXPORT_DESC = Export an AXI-Lite responder that has access to Test Engine's CSRs

   RANGE_EX_DESIGN_HYDRA_HOST_INTF_REMOTE_JTAG_NAME = Remote machine via JTAG
   RANGE_EX_DESIGN_HYDRA_HOST_INTF_REMOTE_JTAG_DESC = Access Test Engine's CSRs from a remote machine connected via JTAG

