# AHLS qualification AFU — PIM-mode AFU source loading for the IA840F OFS PR slot.
# Copyright (C) 2026. SPDX-License-Identifier: MIT.
# Evidence: N/qualification/ahls-afu-fim-01/report.md
#
# LOADED BY: ofs-common/src/fpga_family/agilex/afu_main.tcl — the
# "afu_with_pim/afu.tcl exists" branch ("Loading PIM-based AFU..."), which
# loads the PIM connector port_afu_instances.sv and then this script. That
# flips the PR slot from the std HE-LPBK/HE-MEM exerciser to this AFU with
# no FIM RTL edits.
#
# FILE SHAPE: copied from the canonical generator
# ofs-common/scripts/common/syn/pim/ofs_pim_and_afu_config.sh lines 123-127,
# which emits exactly two assignments (SEARCH_PATH + SOURCE_TCL_SCRIPT_FILE
# of afu_with_pim/afu/hw/afu.qsf). This file instead sources its entries
# directly (same assignment kinds, absolute paths derived from script
# location), because the qualification AFU tree is assembled under the work
# syn_top directly rather than via afu_synth_setup.
#
# TREE (assembled by the recompile stage, relative to syn_top):
#   afu_with_pim/afu.tcl              <- this file
#   afu_with_pim/afu/hw/afu.qsf       <- MISC_FILE (AFU JSON) registration
#   afu_with_pim/afu/hw/ahls_qual_vec_op.json  (AFU JSON: UUID/clock/interface)
#   afu_with_pim/afu/hw/afu_json_info.vh       (generated by afu_json_mgr)
#   afu_with_pim/afu/hw/ofs_plat_afu.sv        (authored AFU top)
#   afu_with_pim/afu/hw/ahls_binding/          (copy of N/afu/ahls binding lib)
#   afu_with_pim/afu/hw/ahls_ip/qual_vec_op.report.prj/  (AHLS component,
#        150-file SHA-256-verified copy from ahls-compile-01)
#
# The PR AFU JSON (ofs_pr_afu.json replacement) is swapped in syn_top by the
# recompile stage (see report §PR-JSON). pim.tcl (unmodified, WORK12
# baseline) loads the PIM platform tree that provides ofs_plat_if.vh and
# all ofs_plat_* packages/macros used by the binding and this top.

set ahls_afu_dir [file dirname [file normalize [info script]]]
set ahls_hw_dir [file join $ahls_afu_dir afu hw]

# --- 1. AFU identity ------------------------------------------------------
# afu_json_info.vh is generated by afu_json_mgr (installed /usr/bin; packing
# convention verified live: "128'h" + hyphens->underscores) from
# ahls_qual_vec_op.json; it defines `AFU_ACCEL_UUID, which the AFU top feeds
# to ahls_board_binding -> ahls_mmio_aperture DFH words 1-2. Single source of
# truth for the UUID: the JSON. UUID 67bc266a-56f7-440a-bb75-12b5f446d842.
set_global_assignment -name MISC_FILE [file join $ahls_hw_dir ahls_qual_vec_op.json]

# Include path for afu_json_info.vh (sits next to the JSON in hw/).
set_global_assignment -name SEARCH_PATH $ahls_hw_dir

# --- 2. Binding library (reusable, 5 modules) ------------------------------
# Contract: N/afu/ahls/integration-contract.json. Entry module
# ahls_board_binding; mandatory instance parameters AFU_UUID/CSR_BASE_BYTES/
# CSR_SIZE_BYTES are bound in ofs_plat_afu.sv. The five sources are added
# explicitly here (same effect as sourcing ahls_binding_sources.tcl, but with
# the work-tree copy path rather than the N-tree original).
set ahls_binding_dir [file join $ahls_hw_dir ahls_binding]
set_global_assignment -name SYSTEMVERILOG_FILE [file join $ahls_binding_dir rtl ahls_ofs_board_services.sv]
set_global_assignment -name SYSTEMVERILOG_FILE [file join $ahls_binding_dir rtl ahls_avmm_byte_to_line.sv]
set_global_assignment -name SYSTEMVERILOG_FILE [file join $ahls_binding_dir rtl ahls_mmio_aperture.sv]
set_global_assignment -name SYSTEMVERILOG_FILE [file join $ahls_binding_dir rtl ahls_mmio_to_avmm.sv]
set_global_assignment -name SYSTEMVERILOG_FILE [file join $ahls_binding_dir rtl ahls_board_binding.sv]

# --- 3. AHLS-generated component (kernel IDQualVecOp) ---------------------
# qual_vec_op.report.prj (HLS IP Gen 2026.1.0, ahls-compile-01; Quartus 26.1.1
# compatibility proven in ahls-qsys-import-01: identical fileset generated
# rc=0 as qual_test_k0, top RTL byte-identical). The QUARTUS_SYNTH fileset is
# translated to Quartus assignments by gen_ahls_filelist.py (mechanical
# add_fileset_file -> SYSTEMVERILOG_FILE; the same translation qsys-generate
# performed for qual_test_k0.qip) producing ahls_filelist.tcl in the prj dir.
set ahls_prj_dir [file join $ahls_hw_dir ahls_ip qual_vec_op.report.prj]
source [file join $ahls_prj_dir ahls_filelist.tcl]

# acl_parameter_assert.svh is `included by 4 generated files; it lives in
# the component's ip/ directory (SEARCH_PATH so Quartus resolves it).
set_global_assignment -name SEARCH_PATH [file join $ahls_prj_dir ip]

# Generated per-entity assignment (from the component's set_qip_strings):
# AUTO_SHIFT_REGISTER_RECOGNITION OFF for *_NO_SHIFT_REG* (HLS FIFO
# hardening). Harmless under 26.1.1 per the qsys-import run (0 warnings).
set_instance_assignment -entity qual_vec_op_report_di -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*

# --- 4. AFU top ------------------------------------------------------------
# Module name ofs_plat_afu is fixed by platform_afu_top_config.vh
# (`PLATFORM_SHIM_MODULE_NAME ofs_plat_afu); afu_main_pim/port_afu_instances.sv
# instantiates `PLATFORM_SHIM_MODULE_NAME with a single ofs_plat_if port.
set_global_assignment -name SYSTEMVERILOG_FILE [file join $ahls_hw_dir ofs_plat_afu.sv]

# --- 5. Static completeness assertions (fail loudly at project load) -------
# These trigger during quartus_sh project-script evaluation if the assembled
# tree is incomplete — before any synthesis attempt.
foreach ahls_required [list \
        [file join $ahls_hw_dir afu_json_info.vh] \
        [file join $ahls_hw_dir ofs_plat_afu.sv] \
        [file join $ahls_prj_dir qual_vec_op_report_di.sv] \
        [file join $ahls_prj_dir ahls_filelist.tcl] \
        [file join $ahls_binding_dir rtl ahls_board_binding.sv]] {
    if { ![file exists $ahls_required] } {
        error "AHLS AFU integration: missing required file $ahls_required"
    }
}
