#####################################
# Perf opts
#####################################

PARAM_AUTO_PRECHARGE_NAME = Auto-Precharge mode
PARAM_AUTO_PRECHARGE_DESC = Asserting Auto-Precharge on a read or write command instructs the memory controller to automatically close the currently opened row, thereby speeding up a subsequent access to a different row.

   RANGE_AUTO_PRECHARGE_DISABLED_NAME = Disabled
   RANGE_AUTO_PRECHARGE_DISABLED_DESC = Auto-precharge will not be issued

   RANGE_AUTO_PRECHARGE_SS_CONTROLLED_NAME = Issued by MSA
   RANGE_AUTO_PRECHARGE_SS_CONTROLLED_DESC = Memory-Specific Adapter (MSA) tracks opened rows to detect row changes and issue auto-precharge

   RANGE_AUTO_PRECHARGE_USER_CONTROLLED_NAME = Issued by user
   RANGE_AUTO_PRECHARGE_USER_CONTROLLED_DESC = User can assert auto-precharge for read or write commands

PARAM_NUM_COPIES_NAME = Number of copies
PARAM_NUM_COPIES_DESC = Memory is partitioned into replicas that contain identical data. This boosts read throughput but reduces write throughput and reduces available storage capacity.

   RANGE_NUM_COPIES_1_NAME = No copies

PARAM_NUM_BANK_FIFOS_NAME = Number of bank FIFOs
PARAM_NUM_BANK_FIFOS_DESC = Bank FIFOs reorder user traffic to uniformly distribute memory accesses across banks to improve read and write throughput. Using distinct AXI IDs for every AXI transaction improves the effectiveness of this feature.

   RANGE_NUM_BANK_FIFOS_0_NAME = No bank spreading

PARAM_SCHEDULER_NUM_READ_NAME = Schedule read opportunities
PARAM_SCHEDULER_NUM_READ_DESC = Number of reads to issue before issuing writes. Starvation is avoided by issuing writes if sufficient read commands are not available.

PARAM_SCHEDULER_NUM_WRITE_NAME = Schedule write opportunities
PARAM_SCHEDULER_NUM_WRITE_DESC = Number of writes to issue before issuing reads. Starvation is avoided by issuing reads if sufficient write commands are not available.

# RANGE_SCHEDULER_POLICY_NATURAL_NAME = Natural order
# RANGE_SCHEDULER_POLICY_TXN_WINDOW_NAME = Transaction-based window
# RANGE_SCHEDULER_POLICY_CLK_WINDOW_NAME = Clock-based window

#####################################
# AXI interface
#####################################

PARAM_ASYNC_EN_NAME = Enable asynchronous mode
PARAM_ASYNC_EN_DESC = Specifies whether the AXI interface exposed to user logic is clocked by the memory interface clock (Sync), or by a separate user clock (Async)

PARAM_RESP_BUS_PROTOCOL_NAME = Responder bus protocol
PARAM_RESP_BUS_PROTOCOL_DESC = Bus protocol for responder interface that is exposed to user or downstream components

PARAM_RESP_WR_DATA_WIDTH_NAME = Responder write data width
PARAM_RESP_WR_DATA_WIDTH_DESC = Power-of-2 portion of write data will be mapped to WDATA and remaining portion will be mapped to WUSER

PARAM_RESP_RD_DATA_WIDTH_NAME = Responder read data width
PARAM_RESP_RD_DATA_WIDTH_DESC = Power-of-2 portion of write data will be mapped to RDATA and remaining portion will be mapped to RUSER

PARAM_RESP_USE_WSTRB_NAME = Enable WSTRB
PARAM_RESP_USE_WSTRB_DESC = If enabled, DRAM's write data bus inversion (DBI) which provides better signal integrity and write margin is not used. If disabled, WSTRB is still exposed but not used.

PARAM_INIT_BUS_PROTOCOL_NAME = Initiator bus protocol
PARAM_INIT_BUS_PROTOCOL_DESC = Bus protocol for initiator interface that connects to the external memory interface IP

PARAM_INIT_ID_WIDTH_NAME = Initiator ID width
PARAM_INIT_ID_WIDTH_DESC = Initiator port width for AWID, ARID, BID, RID

PARAM_INIT_AWADDR_WIDTH_NAME = Initiator AWADDR width
PARAM_INIT_AWADDR_WIDTH_DESC = Initiator port width for AWADDR

PARAM_INIT_ARADDR_WIDTH_NAME = Initiator ARADDR width
PARAM_INIT_ARADDR_WIDTH_DESC = Initiator port width for ARADDR

PARAM_INIT_WR_DATA_WIDTH_NAME = Initiator write data width
PARAM_INIT_WR_DATA_WIDTH_DESC = Power-of-2 portion of write data will be mapped to WDATA and remaining portion will be mapped to WUSER

PARAM_INIT_RD_DATA_WIDTH_NAME = Initiator read data width
PARAM_INIT_RD_DATA_WIDTH_DESC = Power-of-2 portion of write data will be mapped to RDATA and remaining portion will be mapped to RUSER

