//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_examples_afu01/sources/local_memory/hw/rtl/hello_mem_afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "hello_mem_afu"
`define AFU_ACCEL_NAME0 "hello_mem_afu"
`define AFU_ACCEL_UUID 128'h35f9452b_25c2_434c_93d5_6f8c60db361c
`define AFU_ACCEL_UUID0 128'h35f9452b_25c2_434c_93d5_6f8c60db361c
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
