# TCL File Generated by Component Editor 15.1
# Thu Aug 18 14:04:14 BST 2016
# DO NOT MODIFY


# 
# IRQ_Generator "IRQ_Generator" v1.0
#  2016.08.18.14:04:14
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1
source $env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/common/embedded_ip_hwtcl_common.tcl


# 
# module IRQ_Generator
# 
set_module_property DESCRIPTION ""
set_module_property NAME IRQ_Generator
set_module_property GROUP "Basic Functions"
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME IRQ_Generator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate

# parameter
add_parameter appear_in_device_tree BOOLEAN
set_parameter_property appear_in_device_tree DEFAULT_VALUE {false}
set_parameter_property appear_in_device_tree DISPLAY_NAME {Appear in Device Tree}
set_parameter_property appear_in_device_tree DESCRIPTION {To appear in Device Tree when set to 1}
#set_parameter_property appear_in_device_tree DERIVED {1}
set_parameter_property appear_in_device_tree AFFECTS_GENERATION {1}
set_parameter_property appear_in_device_tree HDL_PARAMETER {0}


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL irq_generator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file irq_generator.v VERILOG PATH irq_generator.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL irq_generator
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file irq_generator.v VERILOG PATH irq_generator.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL irq_generator
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file irq_generator.v VERILOG PATH irq_generator.v


# 
# parameters
# 

#add_display_item {appear in device tree} appear_in_device_tree PARAMETER

# Device tree parameters
#set_module_assignment embeddedsw.dts.vendor "nalla"
#set_module_assignment embeddedsw.dts.name "irqgen"
#set_module_assignment embeddedsw.dts.compatible "nalla,a10ep"

#set appear_in_device_tree [ get_parameter_value  appear_in_device_tree ]; 

#set appear_in_device_tree [ proc_get_boolean_parameter  appear_in_device_tree ]

#set  appear_in_device_tree

#set km_appear_in_device_tree [ proc_get_boolean_parameter  appear_in_device_tree ]

## Device tree conditional parameter
#if { $km_appear_in_device_tree } {
#  set_module_assignment embeddedsw.dts.vendor "nalla"
#  set_module_assignment embeddedsw.dts.name "irqgen"
#  set_module_assignment embeddedsw.dts.compatible "nalla,a10ep"
#} else {
#}

# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point irq_in
# 
add_interface Ext_irq_interface conduit end
set_interface_property Ext_irq_interface associatedClock ""
set_interface_property Ext_irq_interface associatedReset ""
set_interface_property Ext_irq_interface ENABLED true

add_interface_port Ext_irq_interface irq_in irq_in Input 2


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

#-------------------------------------------------------------------------------
# module validation
#-------------------------------------------------------------------------------
proc validate {} {
    set appear_in_device_tree [ proc_get_boolean_parameter  appear_in_device_tree ]
}

#-------------------------------------------------------------------------------
# module elaboration
#-------------------------------------------------------------------------------
proc elaborate {} {
    ## Device tree conditional parameter
    if { [get_parameter_value appear_in_device_tree] == "true" } {
	set_module_assignment embeddedsw.dts.vendor "nalla"
	set_module_assignment embeddedsw.dts.name "irqgen"
	set_module_assignment embeddedsw.dts.compatible "nalla,a10ep"
    } else {
    }
}