// mem_ss_mem_ss_501_qm5zaka.v

// Generated using ACDS version 26.1.1 130

`timescale 1 ps / 1 ps
module mem_ss_mem_ss_501_qm5zaka (
		input  wire         mem0_pll_ref_clk,        // mem0_pll_ref_clk.clk
		input  wire         mem0_oct_rzqin,          //         mem0_oct.oct_rzqin
		output wire [0:0]   mem0_ddr4_ck,            //        mem0_ddr4.mem_ck
		output wire [0:0]   mem0_ddr4_ck_n,          //                 .mem_ck_n
		output wire [16:0]  mem0_ddr4_a,             //                 .mem_a
		output wire [0:0]   mem0_ddr4_act_n,         //                 .mem_act_n
		output wire [1:0]   mem0_ddr4_ba,            //                 .mem_ba
		output wire [1:0]   mem0_ddr4_bg,            //                 .mem_bg
		output wire [0:0]   mem0_ddr4_cke,           //                 .mem_cke
		output wire [0:0]   mem0_ddr4_cs_n,          //                 .mem_cs_n
		output wire [0:0]   mem0_ddr4_odt,           //                 .mem_odt
		output wire [0:0]   mem0_ddr4_reset_n,       //                 .mem_reset_n
		output wire [0:0]   mem0_ddr4_par,           //                 .mem_par
		input  wire [0:0]   mem0_ddr4_alert_n,       //                 .mem_alert_n
		inout  wire [7:0]   mem0_ddr4_dqs,           //                 .mem_dqs
		inout  wire [7:0]   mem0_ddr4_dqs_n,         //                 .mem_dqs_n
		inout  wire [63:0]  mem0_ddr4_dq,            //                 .mem_dq
		inout  wire [7:0]   mem0_ddr4_dbi_n,         //                 .mem_dbi_n
		output wire         mem0_ss_app_usr_clk,     //     mem0_usr_clk.clk
		output wire         mem0_ss_app_usr_reset_n, // mem0_usr_reset_n.reset_n
		input  wire         mem1_pll_ref_clk,        // mem1_pll_ref_clk.clk
		input  wire         mem1_oct_rzqin,          //         mem1_oct.oct_rzqin
		output wire [0:0]   mem1_ddr4_ck,            //        mem1_ddr4.mem_ck
		output wire [0:0]   mem1_ddr4_ck_n,          //                 .mem_ck_n
		output wire [16:0]  mem1_ddr4_a,             //                 .mem_a
		output wire [0:0]   mem1_ddr4_act_n,         //                 .mem_act_n
		output wire [1:0]   mem1_ddr4_ba,            //                 .mem_ba
		output wire [1:0]   mem1_ddr4_bg,            //                 .mem_bg
		output wire [0:0]   mem1_ddr4_cke,           //                 .mem_cke
		output wire [0:0]   mem1_ddr4_cs_n,          //                 .mem_cs_n
		output wire [0:0]   mem1_ddr4_odt,           //                 .mem_odt
		output wire [0:0]   mem1_ddr4_reset_n,       //                 .mem_reset_n
		output wire [0:0]   mem1_ddr4_par,           //                 .mem_par
		input  wire [0:0]   mem1_ddr4_alert_n,       //                 .mem_alert_n
		inout  wire [7:0]   mem1_ddr4_dqs,           //                 .mem_dqs
		inout  wire [7:0]   mem1_ddr4_dqs_n,         //                 .mem_dqs_n
		inout  wire [63:0]  mem1_ddr4_dq,            //                 .mem_dq
		inout  wire [7:0]   mem1_ddr4_dbi_n,         //                 .mem_dbi_n
		output wire         mem1_ss_app_usr_clk,     //     mem1_usr_clk.clk
		output wire         mem1_ss_app_usr_reset_n, // mem1_usr_reset_n.reset_n
		input  wire         app_ss_rst_req,          //  subsystem_reset.app_ss_rst_req
		output wire         ss_app_rst_rdy,          //                 .ss_app_rst_rdy
		input  wire         app_ss_cold_rst_n,       //                 .app_ss_cold_rst_n
		output wire         ss_app_cold_rst_ack_n,   //                 .ss_app_cold_rst_ack_n
		output wire         i0_ss_app_mm_awready,    //        i0_axi_mm.awready
		input  wire         i0_app_ss_mm_awvalid,    //                 .awvalid
		input  wire [8:0]   i0_app_ss_mm_awid,       //                 .awid
		input  wire [33:0]  i0_app_ss_mm_awaddr,     //                 .awaddr
		input  wire [7:0]   i0_app_ss_mm_awlen,      //                 .awlen
		input  wire [2:0]   i0_app_ss_mm_awsize,     //                 .awsize
		input  wire [1:0]   i0_app_ss_mm_awburst,    //                 .awburst
		input  wire         i0_app_ss_mm_awlock,     //                 .awlock
		input  wire [3:0]   i0_app_ss_mm_awcache,    //                 .awcache
		input  wire [2:0]   i0_app_ss_mm_awprot,     //                 .awprot
		input  wire [3:0]   i0_app_ss_mm_awqos,      //                 .awqos
		input  wire [13:0]  i0_app_ss_mm_awuser,     //                 .awuser
		output wire         i0_ss_app_mm_arready,    //                 .arready
		input  wire         i0_app_ss_mm_arvalid,    //                 .arvalid
		input  wire [8:0]   i0_app_ss_mm_arid,       //                 .arid
		input  wire [33:0]  i0_app_ss_mm_araddr,     //                 .araddr
		input  wire [7:0]   i0_app_ss_mm_arlen,      //                 .arlen
		input  wire [2:0]   i0_app_ss_mm_arsize,     //                 .arsize
		input  wire [1:0]   i0_app_ss_mm_arburst,    //                 .arburst
		input  wire         i0_app_ss_mm_arlock,     //                 .arlock
		input  wire [3:0]   i0_app_ss_mm_arcache,    //                 .arcache
		input  wire [2:0]   i0_app_ss_mm_arprot,     //                 .arprot
		input  wire [3:0]   i0_app_ss_mm_arqos,      //                 .arqos
		input  wire [13:0]  i0_app_ss_mm_aruser,     //                 .aruser
		output wire         i0_ss_app_mm_wready,     //                 .wready
		input  wire         i0_app_ss_mm_wvalid,     //                 .wvalid
		input  wire [511:0] i0_app_ss_mm_wdata,      //                 .wdata
		input  wire [63:0]  i0_app_ss_mm_wstrb,      //                 .wstrb
		input  wire         i0_app_ss_mm_wlast,      //                 .wlast
		input  wire         i0_app_ss_mm_bready,     //                 .bready
		output wire         i0_ss_app_mm_bvalid,     //                 .bvalid
		output wire [8:0]   i0_ss_app_mm_bid,        //                 .bid
		output wire [1:0]   i0_ss_app_mm_bresp,      //                 .bresp
		output wire         i0_ss_app_mm_buser,      //                 .buser
		input  wire         i0_app_ss_mm_rready,     //                 .rready
		output wire         i0_ss_app_mm_rvalid,     //                 .rvalid
		output wire [8:0]   i0_ss_app_mm_rid,        //                 .rid
		output wire [1:0]   i0_ss_app_mm_rresp,      //                 .rresp
		output wire [511:0] i0_ss_app_mm_rdata,      //                 .rdata
		output wire         i0_ss_app_mm_rlast,      //                 .rlast
		output wire         mem0_local_cal_success,  //      mem0_status.local_cal_success
		output wire         mem0_local_cal_fail,     //                 .local_cal_fail
		output wire         i1_ss_app_mm_awready,    //        i1_axi_mm.awready
		input  wire         i1_app_ss_mm_awvalid,    //                 .awvalid
		input  wire [8:0]   i1_app_ss_mm_awid,       //                 .awid
		input  wire [33:0]  i1_app_ss_mm_awaddr,     //                 .awaddr
		input  wire [7:0]   i1_app_ss_mm_awlen,      //                 .awlen
		input  wire [2:0]   i1_app_ss_mm_awsize,     //                 .awsize
		input  wire [1:0]   i1_app_ss_mm_awburst,    //                 .awburst
		input  wire         i1_app_ss_mm_awlock,     //                 .awlock
		input  wire [3:0]   i1_app_ss_mm_awcache,    //                 .awcache
		input  wire [2:0]   i1_app_ss_mm_awprot,     //                 .awprot
		input  wire [3:0]   i1_app_ss_mm_awqos,      //                 .awqos
		input  wire [13:0]  i1_app_ss_mm_awuser,     //                 .awuser
		output wire         i1_ss_app_mm_arready,    //                 .arready
		input  wire         i1_app_ss_mm_arvalid,    //                 .arvalid
		input  wire [8:0]   i1_app_ss_mm_arid,       //                 .arid
		input  wire [33:0]  i1_app_ss_mm_araddr,     //                 .araddr
		input  wire [7:0]   i1_app_ss_mm_arlen,      //                 .arlen
		input  wire [2:0]   i1_app_ss_mm_arsize,     //                 .arsize
		input  wire [1:0]   i1_app_ss_mm_arburst,    //                 .arburst
		input  wire         i1_app_ss_mm_arlock,     //                 .arlock
		input  wire [3:0]   i1_app_ss_mm_arcache,    //                 .arcache
		input  wire [2:0]   i1_app_ss_mm_arprot,     //                 .arprot
		input  wire [3:0]   i1_app_ss_mm_arqos,      //                 .arqos
		input  wire [13:0]  i1_app_ss_mm_aruser,     //                 .aruser
		output wire         i1_ss_app_mm_wready,     //                 .wready
		input  wire         i1_app_ss_mm_wvalid,     //                 .wvalid
		input  wire [511:0] i1_app_ss_mm_wdata,      //                 .wdata
		input  wire [63:0]  i1_app_ss_mm_wstrb,      //                 .wstrb
		input  wire         i1_app_ss_mm_wlast,      //                 .wlast
		input  wire         i1_app_ss_mm_bready,     //                 .bready
		output wire         i1_ss_app_mm_bvalid,     //                 .bvalid
		output wire [8:0]   i1_ss_app_mm_bid,        //                 .bid
		output wire [1:0]   i1_ss_app_mm_bresp,      //                 .bresp
		output wire         i1_ss_app_mm_buser,      //                 .buser
		input  wire         i1_app_ss_mm_rready,     //                 .rready
		output wire         i1_ss_app_mm_rvalid,     //                 .rvalid
		output wire [8:0]   i1_ss_app_mm_rid,        //                 .rid
		output wire [1:0]   i1_ss_app_mm_rresp,      //                 .rresp
		output wire [511:0] i1_ss_app_mm_rdata,      //                 .rdata
		output wire         i1_ss_app_mm_rlast,      //                 .rlast
		output wire         mem1_local_cal_success,  //      mem1_status.local_cal_success
		output wire         mem1_local_cal_fail      //                 .local_cal_fail
	);

	wire           emif_cal_bot_emif_calbus_clk_clk;                   // emif_cal_bot:calbus_clk -> [emif_0:calbus_clk, emif_1:calbus_clk]
	wire           emif_0_emif_usr_clk_clk;                            // emif_0:emif_usr_clk -> [emif_0_clk_bridge:in_clk, mm_interconnect_0:emif_0_emif_usr_clk_clk, msa_0:m_clk, msa_0:s_clk, rst_controller:clk]
	wire           emif_1_emif_usr_clk_clk;                            // emif_1:emif_usr_clk -> [emif_1_clk_bridge:in_clk, mm_interconnect_1:emif_1_emif_usr_clk_clk, msa_1:m_clk, msa_1:s_clk, rst_controller_001:clk]
	wire           emif_0_pll_ref_clk_out_clk;                         // emif_0:pll_ref_clk_out -> mem_reset_ctrl:clk
	wire           msa_0_ctrl_auto_precharge_ctrl_auto_precharge_req;  // msa_0:ctrl_auto_precharge_req -> emif_0:ctrl_auto_precharge_req_0
	wire           msa_1_ctrl_auto_precharge_ctrl_auto_precharge_req;  // msa_1:ctrl_auto_precharge_req -> emif_1:ctrl_auto_precharge_req_0
	wire    [31:0] emif_cal_bot_emif_calbus_0_calbus_wdata;            // emif_cal_bot:calbus_wdata_0 -> emif_0:calbus_wdata
	wire    [19:0] emif_cal_bot_emif_calbus_0_calbus_address;          // emif_cal_bot:calbus_address_0 -> emif_0:calbus_address
	wire  [4095:0] emif_0_emif_calbus_calbus_seq_param_tbl;            // emif_0:calbus_seq_param_tbl -> emif_cal_bot:calbus_seq_param_tbl_0
	wire           emif_cal_bot_emif_calbus_0_calbus_read;             // emif_cal_bot:calbus_read_0 -> emif_0:calbus_read
	wire           emif_cal_bot_emif_calbus_0_calbus_write;            // emif_cal_bot:calbus_write_0 -> emif_0:calbus_write
	wire    [31:0] emif_0_emif_calbus_calbus_rdata;                    // emif_0:calbus_rdata -> emif_cal_bot:calbus_rdata_0
	wire    [31:0] emif_cal_bot_emif_calbus_1_calbus_wdata;            // emif_cal_bot:calbus_wdata_1 -> emif_1:calbus_wdata
	wire    [19:0] emif_cal_bot_emif_calbus_1_calbus_address;          // emif_cal_bot:calbus_address_1 -> emif_1:calbus_address
	wire  [4095:0] emif_1_emif_calbus_calbus_seq_param_tbl;            // emif_1:calbus_seq_param_tbl -> emif_cal_bot:calbus_seq_param_tbl_1
	wire           emif_cal_bot_emif_calbus_1_calbus_read;             // emif_cal_bot:calbus_read_1 -> emif_1:calbus_read
	wire           emif_cal_bot_emif_calbus_1_calbus_write;            // emif_cal_bot:calbus_write_1 -> emif_1:calbus_write
	wire    [31:0] emif_1_emif_calbus_calbus_rdata;                    // emif_1:calbus_rdata -> emif_cal_bot:calbus_rdata_1
	wire           mem_reset_ctrl_fm_emif_reset_req_0_local_reset_req; // mem_reset_ctrl:local_reset_req_0 -> emif_0:local_reset_req
	wire           mem_reset_ctrl_fm_emif_reset_req_1_local_reset_req; // mem_reset_ctrl:local_reset_req_1 -> emif_1:local_reset_req
	wire           emif_0_local_reset_status_local_reset_done;         // emif_0:local_reset_done -> mem_reset_ctrl:local_reset_done_0
	wire           emif_1_local_reset_status_local_reset_done;         // emif_1:local_reset_done -> mem_reset_ctrl:local_reset_done_1
	wire           emif_0_pll_locked_pll_locked;                       // emif_0:pll_locked -> mem_reset_ctrl:reset_n
	wire           emif_0_status_local_cal_fail;                       // emif_0:local_cal_fail -> msa_0:local_cal_fail_in
	wire           emif_0_status_local_cal_success;                    // emif_0:local_cal_success -> msa_0:local_cal_success_in
	wire           emif_1_status_local_cal_fail;                       // emif_1:local_cal_fail -> msa_1:local_cal_fail_in
	wire           emif_1_status_local_cal_success;                    // emif_1:local_cal_success -> msa_1:local_cal_success_in
	wire           emif_0_emif_usr_reset_n_reset;                      // emif_0:emif_usr_reset_n -> [emif_0_reset_bridge:in_reset_n, msa_0:m_reset_n, msa_0:s_reset_n, rst_controller:reset_in0]
	wire           emif_1_emif_usr_reset_n_reset;                      // emif_1:emif_usr_reset_n -> [emif_1_reset_bridge:in_reset_n, msa_1:m_reset_n, msa_1:s_reset_n, rst_controller_001:reset_in0]
	wire           msa_0_m_avmm_waitrequest;                           // mm_interconnect_0:msa_0_m_avmm_waitrequest -> msa_0:m_avmm_ready
	wire   [511:0] msa_0_m_avmm_readdata;                              // mm_interconnect_0:msa_0_m_avmm_readdata -> msa_0:m_avmm_readdata
	wire           msa_0_m_avmm_read;                                  // msa_0:m_avmm_read -> mm_interconnect_0:msa_0_m_avmm_read
	wire    [33:0] msa_0_m_avmm_address;                               // msa_0:m_avmm_address -> mm_interconnect_0:msa_0_m_avmm_address
	wire    [63:0] msa_0_m_avmm_byteenable;                            // msa_0:m_avmm_byteenable -> mm_interconnect_0:msa_0_m_avmm_byteenable
	wire           msa_0_m_avmm_readdatavalid;                         // mm_interconnect_0:msa_0_m_avmm_readdatavalid -> msa_0:m_avmm_readdatavalid
	wire           msa_0_m_avmm_write;                                 // msa_0:m_avmm_write -> mm_interconnect_0:msa_0_m_avmm_write
	wire   [511:0] msa_0_m_avmm_writedata;                             // msa_0:m_avmm_writedata -> mm_interconnect_0:msa_0_m_avmm_writedata
	wire     [6:0] msa_0_m_avmm_burstcount;                            // msa_0:m_avmm_burstcount -> mm_interconnect_0:msa_0_m_avmm_burstcount
	wire   [511:0] mm_interconnect_0_emif_0_ctrl_amm_0_readdata;       // emif_0:amm_readdata_0 -> mm_interconnect_0:emif_0_ctrl_amm_0_readdata
	wire           mm_interconnect_0_emif_0_ctrl_amm_0_waitrequest;    // emif_0:amm_ready_0 -> mm_interconnect_0:emif_0_ctrl_amm_0_waitrequest
	wire    [27:0] mm_interconnect_0_emif_0_ctrl_amm_0_address;        // mm_interconnect_0:emif_0_ctrl_amm_0_address -> emif_0:amm_address_0
	wire           mm_interconnect_0_emif_0_ctrl_amm_0_read;           // mm_interconnect_0:emif_0_ctrl_amm_0_read -> emif_0:amm_read_0
	wire    [63:0] mm_interconnect_0_emif_0_ctrl_amm_0_byteenable;     // mm_interconnect_0:emif_0_ctrl_amm_0_byteenable -> emif_0:amm_byteenable_0
	wire           mm_interconnect_0_emif_0_ctrl_amm_0_readdatavalid;  // emif_0:amm_readdatavalid_0 -> mm_interconnect_0:emif_0_ctrl_amm_0_readdatavalid
	wire           mm_interconnect_0_emif_0_ctrl_amm_0_write;          // mm_interconnect_0:emif_0_ctrl_amm_0_write -> emif_0:amm_write_0
	wire   [511:0] mm_interconnect_0_emif_0_ctrl_amm_0_writedata;      // mm_interconnect_0:emif_0_ctrl_amm_0_writedata -> emif_0:amm_writedata_0
	wire     [6:0] mm_interconnect_0_emif_0_ctrl_amm_0_burstcount;     // mm_interconnect_0:emif_0_ctrl_amm_0_burstcount -> emif_0:amm_burstcount_0
	wire           msa_1_m_avmm_waitrequest;                           // mm_interconnect_1:msa_1_m_avmm_waitrequest -> msa_1:m_avmm_ready
	wire   [511:0] msa_1_m_avmm_readdata;                              // mm_interconnect_1:msa_1_m_avmm_readdata -> msa_1:m_avmm_readdata
	wire           msa_1_m_avmm_read;                                  // msa_1:m_avmm_read -> mm_interconnect_1:msa_1_m_avmm_read
	wire    [33:0] msa_1_m_avmm_address;                               // msa_1:m_avmm_address -> mm_interconnect_1:msa_1_m_avmm_address
	wire    [63:0] msa_1_m_avmm_byteenable;                            // msa_1:m_avmm_byteenable -> mm_interconnect_1:msa_1_m_avmm_byteenable
	wire           msa_1_m_avmm_readdatavalid;                         // mm_interconnect_1:msa_1_m_avmm_readdatavalid -> msa_1:m_avmm_readdatavalid
	wire           msa_1_m_avmm_write;                                 // msa_1:m_avmm_write -> mm_interconnect_1:msa_1_m_avmm_write
	wire   [511:0] msa_1_m_avmm_writedata;                             // msa_1:m_avmm_writedata -> mm_interconnect_1:msa_1_m_avmm_writedata
	wire     [6:0] msa_1_m_avmm_burstcount;                            // msa_1:m_avmm_burstcount -> mm_interconnect_1:msa_1_m_avmm_burstcount
	wire   [511:0] mm_interconnect_1_emif_1_ctrl_amm_0_readdata;       // emif_1:amm_readdata_0 -> mm_interconnect_1:emif_1_ctrl_amm_0_readdata
	wire           mm_interconnect_1_emif_1_ctrl_amm_0_waitrequest;    // emif_1:amm_ready_0 -> mm_interconnect_1:emif_1_ctrl_amm_0_waitrequest
	wire    [27:0] mm_interconnect_1_emif_1_ctrl_amm_0_address;        // mm_interconnect_1:emif_1_ctrl_amm_0_address -> emif_1:amm_address_0
	wire           mm_interconnect_1_emif_1_ctrl_amm_0_read;           // mm_interconnect_1:emif_1_ctrl_amm_0_read -> emif_1:amm_read_0
	wire    [63:0] mm_interconnect_1_emif_1_ctrl_amm_0_byteenable;     // mm_interconnect_1:emif_1_ctrl_amm_0_byteenable -> emif_1:amm_byteenable_0
	wire           mm_interconnect_1_emif_1_ctrl_amm_0_readdatavalid;  // emif_1:amm_readdatavalid_0 -> mm_interconnect_1:emif_1_ctrl_amm_0_readdatavalid
	wire           mm_interconnect_1_emif_1_ctrl_amm_0_write;          // mm_interconnect_1:emif_1_ctrl_amm_0_write -> emif_1:amm_write_0
	wire   [511:0] mm_interconnect_1_emif_1_ctrl_amm_0_writedata;      // mm_interconnect_1:emif_1_ctrl_amm_0_writedata -> emif_1:amm_writedata_0
	wire     [6:0] mm_interconnect_1_emif_1_ctrl_amm_0_burstcount;     // mm_interconnect_1:emif_1_ctrl_amm_0_burstcount -> emif_1:amm_burstcount_0
	wire           rst_controller_reset_out_reset;                     // rst_controller:reset_out -> mm_interconnect_0:msa_0_m_avmm_translator_reset_reset_bridge_in_reset_reset
	wire           rst_controller_001_reset_out_reset;                 // rst_controller_001:reset_out -> mm_interconnect_1:msa_1_m_avmm_translator_reset_reset_bridge_in_reset_reset

	mem_ss_mem_ss_501_qm5zaka_emif_0 emif_0 (
		.local_reset_req           (mem_reset_ctrl_fm_emif_reset_req_0_local_reset_req), //   input,     width = 1,       local_reset_req.local_reset_req
		.local_reset_done          (emif_0_local_reset_status_local_reset_done),         //  output,     width = 1,    local_reset_status.local_reset_done
		.pll_ref_clk               (mem0_pll_ref_clk),                                   //   input,     width = 1,           pll_ref_clk.clk
		.pll_ref_clk_out           (emif_0_pll_ref_clk_out_clk),                         //  output,     width = 1,       pll_ref_clk_out.clk
		.pll_locked                (emif_0_pll_locked_pll_locked),                       //  output,     width = 1,            pll_locked.pll_locked
		.oct_rzqin                 (mem0_oct_rzqin),                                     //   input,     width = 1,                   oct.oct_rzqin
		.mem_ck                    (mem0_ddr4_ck),                                       //  output,     width = 1,                   mem.mem_ck
		.mem_ck_n                  (mem0_ddr4_ck_n),                                     //  output,     width = 1,                      .mem_ck_n
		.mem_a                     (mem0_ddr4_a),                                        //  output,    width = 17,                      .mem_a
		.mem_act_n                 (mem0_ddr4_act_n),                                    //  output,     width = 1,                      .mem_act_n
		.mem_ba                    (mem0_ddr4_ba),                                       //  output,     width = 2,                      .mem_ba
		.mem_bg                    (mem0_ddr4_bg),                                       //  output,     width = 2,                      .mem_bg
		.mem_cke                   (mem0_ddr4_cke),                                      //  output,     width = 1,                      .mem_cke
		.mem_cs_n                  (mem0_ddr4_cs_n),                                     //  output,     width = 1,                      .mem_cs_n
		.mem_odt                   (mem0_ddr4_odt),                                      //  output,     width = 1,                      .mem_odt
		.mem_reset_n               (mem0_ddr4_reset_n),                                  //  output,     width = 1,                      .mem_reset_n
		.mem_par                   (mem0_ddr4_par),                                      //  output,     width = 1,                      .mem_par
		.mem_alert_n               (mem0_ddr4_alert_n),                                  //   input,     width = 1,                      .mem_alert_n
		.mem_dqs                   (mem0_ddr4_dqs),                                      //   inout,     width = 8,                      .mem_dqs
		.mem_dqs_n                 (mem0_ddr4_dqs_n),                                    //   inout,     width = 8,                      .mem_dqs_n
		.mem_dq                    (mem0_ddr4_dq),                                       //   inout,    width = 64,                      .mem_dq
		.mem_dbi_n                 (mem0_ddr4_dbi_n),                                    //   inout,     width = 8,                      .mem_dbi_n
		.local_cal_success         (emif_0_status_local_cal_success),                    //  output,     width = 1,                status.local_cal_success
		.local_cal_fail            (emif_0_status_local_cal_fail),                       //  output,     width = 1,                      .local_cal_fail
		.emif_usr_reset_n          (emif_0_emif_usr_reset_n_reset),                      //  output,     width = 1,      emif_usr_reset_n.reset_n
		.emif_usr_clk              (emif_0_emif_usr_clk_clk),                            //  output,     width = 1,          emif_usr_clk.clk
		.amm_ready_0               (mm_interconnect_0_emif_0_ctrl_amm_0_waitrequest),    //  output,     width = 1,            ctrl_amm_0.waitrequest_n
		.amm_read_0                (mm_interconnect_0_emif_0_ctrl_amm_0_read),           //   input,     width = 1,                      .read
		.amm_write_0               (mm_interconnect_0_emif_0_ctrl_amm_0_write),          //   input,     width = 1,                      .write
		.amm_address_0             (mm_interconnect_0_emif_0_ctrl_amm_0_address),        //   input,    width = 28,                      .address
		.amm_readdata_0            (mm_interconnect_0_emif_0_ctrl_amm_0_readdata),       //  output,   width = 512,                      .readdata
		.amm_writedata_0           (mm_interconnect_0_emif_0_ctrl_amm_0_writedata),      //   input,   width = 512,                      .writedata
		.amm_burstcount_0          (mm_interconnect_0_emif_0_ctrl_amm_0_burstcount),     //   input,     width = 7,                      .burstcount
		.amm_byteenable_0          (mm_interconnect_0_emif_0_ctrl_amm_0_byteenable),     //   input,    width = 64,                      .byteenable
		.amm_readdatavalid_0       (mm_interconnect_0_emif_0_ctrl_amm_0_readdatavalid),  //  output,     width = 1,                      .readdatavalid
		.ctrl_auto_precharge_req_0 (msa_0_ctrl_auto_precharge_ctrl_auto_precharge_req),  //   input,     width = 1, ctrl_auto_precharge_0.ctrl_auto_precharge_req
		.calbus_read               (emif_cal_bot_emif_calbus_0_calbus_read),             //   input,     width = 1,           emif_calbus.calbus_read
		.calbus_write              (emif_cal_bot_emif_calbus_0_calbus_write),            //   input,     width = 1,                      .calbus_write
		.calbus_address            (emif_cal_bot_emif_calbus_0_calbus_address),          //   input,    width = 20,                      .calbus_address
		.calbus_wdata              (emif_cal_bot_emif_calbus_0_calbus_wdata),            //   input,    width = 32,                      .calbus_wdata
		.calbus_rdata              (emif_0_emif_calbus_calbus_rdata),                    //  output,    width = 32,                      .calbus_rdata
		.calbus_seq_param_tbl      (emif_0_emif_calbus_calbus_seq_param_tbl),            //  output,  width = 4096,                      .calbus_seq_param_tbl
		.calbus_clk                (emif_cal_bot_emif_calbus_clk_clk)                    //   input,     width = 1,       emif_calbus_clk.clk
	);

	mem_ss_mem_ss_501_qm5zaka_emif_0_clk_bridge emif_0_clk_bridge (
		.in_clk  (emif_0_emif_usr_clk_clk), //   input,  width = 1,  in_clk.clk
		.out_clk (mem0_ss_app_usr_clk)      //  output,  width = 1, out_clk.clk
	);

	mem_ss_mem_ss_501_qm5zaka_emif_0_reset_bridge emif_0_reset_bridge (
		.in_reset_n  (emif_0_emif_usr_reset_n_reset), //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (mem0_ss_app_usr_reset_n)        //  output,  width = 1, out_reset.reset_n
	);

	mem_ss_mem_ss_501_qm5zaka_emif_1 emif_1 (
		.local_reset_req           (mem_reset_ctrl_fm_emif_reset_req_1_local_reset_req), //   input,     width = 1,       local_reset_req.local_reset_req
		.local_reset_done          (emif_1_local_reset_status_local_reset_done),         //  output,     width = 1,    local_reset_status.local_reset_done
		.pll_ref_clk               (mem1_pll_ref_clk),                                   //   input,     width = 1,           pll_ref_clk.clk
		.oct_rzqin                 (mem1_oct_rzqin),                                     //   input,     width = 1,                   oct.oct_rzqin
		.mem_ck                    (mem1_ddr4_ck),                                       //  output,     width = 1,                   mem.mem_ck
		.mem_ck_n                  (mem1_ddr4_ck_n),                                     //  output,     width = 1,                      .mem_ck_n
		.mem_a                     (mem1_ddr4_a),                                        //  output,    width = 17,                      .mem_a
		.mem_act_n                 (mem1_ddr4_act_n),                                    //  output,     width = 1,                      .mem_act_n
		.mem_ba                    (mem1_ddr4_ba),                                       //  output,     width = 2,                      .mem_ba
		.mem_bg                    (mem1_ddr4_bg),                                       //  output,     width = 2,                      .mem_bg
		.mem_cke                   (mem1_ddr4_cke),                                      //  output,     width = 1,                      .mem_cke
		.mem_cs_n                  (mem1_ddr4_cs_n),                                     //  output,     width = 1,                      .mem_cs_n
		.mem_odt                   (mem1_ddr4_odt),                                      //  output,     width = 1,                      .mem_odt
		.mem_reset_n               (mem1_ddr4_reset_n),                                  //  output,     width = 1,                      .mem_reset_n
		.mem_par                   (mem1_ddr4_par),                                      //  output,     width = 1,                      .mem_par
		.mem_alert_n               (mem1_ddr4_alert_n),                                  //   input,     width = 1,                      .mem_alert_n
		.mem_dqs                   (mem1_ddr4_dqs),                                      //   inout,     width = 8,                      .mem_dqs
		.mem_dqs_n                 (mem1_ddr4_dqs_n),                                    //   inout,     width = 8,                      .mem_dqs_n
		.mem_dq                    (mem1_ddr4_dq),                                       //   inout,    width = 64,                      .mem_dq
		.mem_dbi_n                 (mem1_ddr4_dbi_n),                                    //   inout,     width = 8,                      .mem_dbi_n
		.local_cal_success         (emif_1_status_local_cal_success),                    //  output,     width = 1,                status.local_cal_success
		.local_cal_fail            (emif_1_status_local_cal_fail),                       //  output,     width = 1,                      .local_cal_fail
		.emif_usr_reset_n          (emif_1_emif_usr_reset_n_reset),                      //  output,     width = 1,      emif_usr_reset_n.reset_n
		.emif_usr_clk              (emif_1_emif_usr_clk_clk),                            //  output,     width = 1,          emif_usr_clk.clk
		.amm_ready_0               (mm_interconnect_1_emif_1_ctrl_amm_0_waitrequest),    //  output,     width = 1,            ctrl_amm_0.waitrequest_n
		.amm_read_0                (mm_interconnect_1_emif_1_ctrl_amm_0_read),           //   input,     width = 1,                      .read
		.amm_write_0               (mm_interconnect_1_emif_1_ctrl_amm_0_write),          //   input,     width = 1,                      .write
		.amm_address_0             (mm_interconnect_1_emif_1_ctrl_amm_0_address),        //   input,    width = 28,                      .address
		.amm_readdata_0            (mm_interconnect_1_emif_1_ctrl_amm_0_readdata),       //  output,   width = 512,                      .readdata
		.amm_writedata_0           (mm_interconnect_1_emif_1_ctrl_amm_0_writedata),      //   input,   width = 512,                      .writedata
		.amm_burstcount_0          (mm_interconnect_1_emif_1_ctrl_amm_0_burstcount),     //   input,     width = 7,                      .burstcount
		.amm_byteenable_0          (mm_interconnect_1_emif_1_ctrl_amm_0_byteenable),     //   input,    width = 64,                      .byteenable
		.amm_readdatavalid_0       (mm_interconnect_1_emif_1_ctrl_amm_0_readdatavalid),  //  output,     width = 1,                      .readdatavalid
		.ctrl_auto_precharge_req_0 (msa_1_ctrl_auto_precharge_ctrl_auto_precharge_req),  //   input,     width = 1, ctrl_auto_precharge_0.ctrl_auto_precharge_req
		.calbus_read               (emif_cal_bot_emif_calbus_1_calbus_read),             //   input,     width = 1,           emif_calbus.calbus_read
		.calbus_write              (emif_cal_bot_emif_calbus_1_calbus_write),            //   input,     width = 1,                      .calbus_write
		.calbus_address            (emif_cal_bot_emif_calbus_1_calbus_address),          //   input,    width = 20,                      .calbus_address
		.calbus_wdata              (emif_cal_bot_emif_calbus_1_calbus_wdata),            //   input,    width = 32,                      .calbus_wdata
		.calbus_rdata              (emif_1_emif_calbus_calbus_rdata),                    //  output,    width = 32,                      .calbus_rdata
		.calbus_seq_param_tbl      (emif_1_emif_calbus_calbus_seq_param_tbl),            //  output,  width = 4096,                      .calbus_seq_param_tbl
		.calbus_clk                (emif_cal_bot_emif_calbus_clk_clk)                    //   input,     width = 1,       emif_calbus_clk.clk
	);

	mem_ss_mem_ss_501_qm5zaka_emif_1_clk_bridge emif_1_clk_bridge (
		.in_clk  (emif_1_emif_usr_clk_clk), //   input,  width = 1,  in_clk.clk
		.out_clk (mem1_ss_app_usr_clk)      //  output,  width = 1, out_clk.clk
	);

	mem_ss_mem_ss_501_qm5zaka_emif_1_reset_bridge emif_1_reset_bridge (
		.in_reset_n  (emif_1_emif_usr_reset_n_reset), //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (mem1_ss_app_usr_reset_n)        //  output,  width = 1, out_reset.reset_n
	);

	mem_ss_mem_ss_501_qm5zaka_emif_cal_bot emif_cal_bot (
		.calbus_read_0          (emif_cal_bot_emif_calbus_0_calbus_read),    //  output,     width = 1,   emif_calbus_0.calbus_read
		.calbus_write_0         (emif_cal_bot_emif_calbus_0_calbus_write),   //  output,     width = 1,                .calbus_write
		.calbus_address_0       (emif_cal_bot_emif_calbus_0_calbus_address), //  output,    width = 20,                .calbus_address
		.calbus_wdata_0         (emif_cal_bot_emif_calbus_0_calbus_wdata),   //  output,    width = 32,                .calbus_wdata
		.calbus_rdata_0         (emif_0_emif_calbus_calbus_rdata),           //   input,    width = 32,                .calbus_rdata
		.calbus_seq_param_tbl_0 (emif_0_emif_calbus_calbus_seq_param_tbl),   //   input,  width = 4096,                .calbus_seq_param_tbl
		.calbus_read_1          (emif_cal_bot_emif_calbus_1_calbus_read),    //  output,     width = 1,   emif_calbus_1.calbus_read
		.calbus_write_1         (emif_cal_bot_emif_calbus_1_calbus_write),   //  output,     width = 1,                .calbus_write
		.calbus_address_1       (emif_cal_bot_emif_calbus_1_calbus_address), //  output,    width = 20,                .calbus_address
		.calbus_wdata_1         (emif_cal_bot_emif_calbus_1_calbus_wdata),   //  output,    width = 32,                .calbus_wdata
		.calbus_rdata_1         (emif_1_emif_calbus_calbus_rdata),           //   input,    width = 32,                .calbus_rdata
		.calbus_seq_param_tbl_1 (emif_1_emif_calbus_calbus_seq_param_tbl),   //   input,  width = 4096,                .calbus_seq_param_tbl
		.calbus_clk             (emif_cal_bot_emif_calbus_clk_clk)           //  output,     width = 1, emif_calbus_clk.clk
	);

	mem_ss_mem_ss_501_qm5zaka_mem_reset_ctrl mem_reset_ctrl (
		.clk                   (emif_0_pll_ref_clk_out_clk),                         //   input,  width = 1,                    clk.clk
		.reset_n               (emif_0_pll_locked_pll_locked),                       //   input,  width = 1,                  reset.pll_locked
		.app_ss_rst_req        (app_ss_rst_req),                                     //   input,  width = 1,        subsystem_reset.app_ss_rst_req
		.ss_app_rst_rdy        (ss_app_rst_rdy),                                     //  output,  width = 1,                       .ss_app_rst_rdy
		.app_ss_cold_rst_n     (app_ss_cold_rst_n),                                  //   input,  width = 1,                       .app_ss_cold_rst_n
		.ss_app_cold_rst_ack_n (ss_app_cold_rst_ack_n),                              //  output,  width = 1,                       .ss_app_cold_rst_ack_n
		.local_reset_req_0     (mem_reset_ctrl_fm_emif_reset_req_0_local_reset_req), //  output,  width = 1,    fm_emif_reset_req_0.local_reset_req
		.local_reset_done_0    (emif_0_local_reset_status_local_reset_done),         //   input,  width = 1, fm_emif_reset_status_0.local_reset_done
		.local_reset_req_1     (mem_reset_ctrl_fm_emif_reset_req_1_local_reset_req), //  output,  width = 1,    fm_emif_reset_req_1.local_reset_req
		.local_reset_done_1    (emif_1_local_reset_status_local_reset_done)          //   input,  width = 1, fm_emif_reset_status_1.local_reset_done
	);

	mem_ss_mem_ss_501_qm5zaka_msa_0 msa_0 (
		.s_clk                   (emif_0_emif_usr_clk_clk),                           //   input,    width = 1,               s_clk.clk
		.s_reset_n               (emif_0_emif_usr_reset_n_reset),                     //   input,    width = 1,             s_reset.reset_n
		.m_clk                   (emif_0_emif_usr_clk_clk),                           //   input,    width = 1,               m_clk.clk
		.m_reset_n               (emif_0_emif_usr_reset_n_reset),                     //   input,    width = 1,             m_reset.reset_n
		.s_axi4_awready          (i0_ss_app_mm_awready),                              //  output,    width = 1,              s_axi4.awready
		.s_axi4_awvalid          (i0_app_ss_mm_awvalid),                              //   input,    width = 1,                    .awvalid
		.s_axi4_awid             (i0_app_ss_mm_awid),                                 //   input,    width = 9,                    .awid
		.s_axi4_awaddr           (i0_app_ss_mm_awaddr),                               //   input,   width = 34,                    .awaddr
		.s_axi4_awlen            (i0_app_ss_mm_awlen),                                //   input,    width = 8,                    .awlen
		.s_axi4_awsize           (i0_app_ss_mm_awsize),                               //   input,    width = 3,                    .awsize
		.s_axi4_awburst          (i0_app_ss_mm_awburst),                              //   input,    width = 2,                    .awburst
		.s_axi4_awlock           (i0_app_ss_mm_awlock),                               //   input,    width = 1,                    .awlock
		.s_axi4_awcache          (i0_app_ss_mm_awcache),                              //   input,    width = 4,                    .awcache
		.s_axi4_awprot           (i0_app_ss_mm_awprot),                               //   input,    width = 3,                    .awprot
		.s_axi4_awqos            (i0_app_ss_mm_awqos),                                //   input,    width = 4,                    .awqos
		.s_axi4_awuser           (i0_app_ss_mm_awuser),                               //   input,   width = 14,                    .awuser
		.s_axi4_arready          (i0_ss_app_mm_arready),                              //  output,    width = 1,                    .arready
		.s_axi4_arvalid          (i0_app_ss_mm_arvalid),                              //   input,    width = 1,                    .arvalid
		.s_axi4_arid             (i0_app_ss_mm_arid),                                 //   input,    width = 9,                    .arid
		.s_axi4_araddr           (i0_app_ss_mm_araddr),                               //   input,   width = 34,                    .araddr
		.s_axi4_arlen            (i0_app_ss_mm_arlen),                                //   input,    width = 8,                    .arlen
		.s_axi4_arsize           (i0_app_ss_mm_arsize),                               //   input,    width = 3,                    .arsize
		.s_axi4_arburst          (i0_app_ss_mm_arburst),                              //   input,    width = 2,                    .arburst
		.s_axi4_arlock           (i0_app_ss_mm_arlock),                               //   input,    width = 1,                    .arlock
		.s_axi4_arcache          (i0_app_ss_mm_arcache),                              //   input,    width = 4,                    .arcache
		.s_axi4_arprot           (i0_app_ss_mm_arprot),                               //   input,    width = 3,                    .arprot
		.s_axi4_arqos            (i0_app_ss_mm_arqos),                                //   input,    width = 4,                    .arqos
		.s_axi4_aruser           (i0_app_ss_mm_aruser),                               //   input,   width = 14,                    .aruser
		.s_axi4_wready           (i0_ss_app_mm_wready),                               //  output,    width = 1,                    .wready
		.s_axi4_wvalid           (i0_app_ss_mm_wvalid),                               //   input,    width = 1,                    .wvalid
		.s_axi4_wdata            (i0_app_ss_mm_wdata),                                //   input,  width = 512,                    .wdata
		.s_axi4_wstrb            (i0_app_ss_mm_wstrb),                                //   input,   width = 64,                    .wstrb
		.s_axi4_wlast            (i0_app_ss_mm_wlast),                                //   input,    width = 1,                    .wlast
		.s_axi4_bready           (i0_app_ss_mm_bready),                               //   input,    width = 1,                    .bready
		.s_axi4_bvalid           (i0_ss_app_mm_bvalid),                               //  output,    width = 1,                    .bvalid
		.s_axi4_bid              (i0_ss_app_mm_bid),                                  //  output,    width = 9,                    .bid
		.s_axi4_bresp            (i0_ss_app_mm_bresp),                                //  output,    width = 2,                    .bresp
		.s_axi4_buser            (i0_ss_app_mm_buser),                                //  output,    width = 1,                    .buser
		.s_axi4_rready           (i0_app_ss_mm_rready),                               //   input,    width = 1,                    .rready
		.s_axi4_rvalid           (i0_ss_app_mm_rvalid),                               //  output,    width = 1,                    .rvalid
		.s_axi4_rid              (i0_ss_app_mm_rid),                                  //  output,    width = 9,                    .rid
		.s_axi4_rresp            (i0_ss_app_mm_rresp),                                //  output,    width = 2,                    .rresp
		.s_axi4_rdata            (i0_ss_app_mm_rdata),                                //  output,  width = 512,                    .rdata
		.s_axi4_rlast            (i0_ss_app_mm_rlast),                                //  output,    width = 1,                    .rlast
		.m_avmm_ready            (~msa_0_m_avmm_waitrequest),                         //   input,    width = 1,              m_avmm.waitrequest_n
		.m_avmm_read             (msa_0_m_avmm_read),                                 //  output,    width = 1,                    .read
		.m_avmm_write            (msa_0_m_avmm_write),                                //  output,    width = 1,                    .write
		.m_avmm_address          (msa_0_m_avmm_address),                              //  output,   width = 34,                    .address
		.m_avmm_burstcount       (msa_0_m_avmm_burstcount),                           //  output,    width = 7,                    .burstcount
		.m_avmm_writedata        (msa_0_m_avmm_writedata),                            //  output,  width = 512,                    .writedata
		.m_avmm_byteenable       (msa_0_m_avmm_byteenable),                           //  output,   width = 64,                    .byteenable
		.m_avmm_readdata         (msa_0_m_avmm_readdata),                             //   input,  width = 512,                    .readdata
		.m_avmm_readdatavalid    (msa_0_m_avmm_readdatavalid),                        //   input,    width = 1,                    .readdatavalid
		.local_cal_success       (mem0_local_cal_success),                            //  output,    width = 1,              status.local_cal_success
		.local_cal_fail          (mem0_local_cal_fail),                               //  output,    width = 1,                    .local_cal_fail
		.local_cal_success_in    (emif_0_status_local_cal_success),                   //   input,    width = 1,           status_in.local_cal_success
		.local_cal_fail_in       (emif_0_status_local_cal_fail),                      //   input,    width = 1,                    .local_cal_fail
		.ctrl_auto_precharge_req (msa_0_ctrl_auto_precharge_ctrl_auto_precharge_req)  //  output,    width = 1, ctrl_auto_precharge.ctrl_auto_precharge_req
	);

	mem_ss_mem_ss_501_qm5zaka_msa_1 msa_1 (
		.s_clk                   (emif_1_emif_usr_clk_clk),                           //   input,    width = 1,               s_clk.clk
		.s_reset_n               (emif_1_emif_usr_reset_n_reset),                     //   input,    width = 1,             s_reset.reset_n
		.m_clk                   (emif_1_emif_usr_clk_clk),                           //   input,    width = 1,               m_clk.clk
		.m_reset_n               (emif_1_emif_usr_reset_n_reset),                     //   input,    width = 1,             m_reset.reset_n
		.s_axi4_awready          (i1_ss_app_mm_awready),                              //  output,    width = 1,              s_axi4.awready
		.s_axi4_awvalid          (i1_app_ss_mm_awvalid),                              //   input,    width = 1,                    .awvalid
		.s_axi4_awid             (i1_app_ss_mm_awid),                                 //   input,    width = 9,                    .awid
		.s_axi4_awaddr           (i1_app_ss_mm_awaddr),                               //   input,   width = 34,                    .awaddr
		.s_axi4_awlen            (i1_app_ss_mm_awlen),                                //   input,    width = 8,                    .awlen
		.s_axi4_awsize           (i1_app_ss_mm_awsize),                               //   input,    width = 3,                    .awsize
		.s_axi4_awburst          (i1_app_ss_mm_awburst),                              //   input,    width = 2,                    .awburst
		.s_axi4_awlock           (i1_app_ss_mm_awlock),                               //   input,    width = 1,                    .awlock
		.s_axi4_awcache          (i1_app_ss_mm_awcache),                              //   input,    width = 4,                    .awcache
		.s_axi4_awprot           (i1_app_ss_mm_awprot),                               //   input,    width = 3,                    .awprot
		.s_axi4_awqos            (i1_app_ss_mm_awqos),                                //   input,    width = 4,                    .awqos
		.s_axi4_awuser           (i1_app_ss_mm_awuser),                               //   input,   width = 14,                    .awuser
		.s_axi4_arready          (i1_ss_app_mm_arready),                              //  output,    width = 1,                    .arready
		.s_axi4_arvalid          (i1_app_ss_mm_arvalid),                              //   input,    width = 1,                    .arvalid
		.s_axi4_arid             (i1_app_ss_mm_arid),                                 //   input,    width = 9,                    .arid
		.s_axi4_araddr           (i1_app_ss_mm_araddr),                               //   input,   width = 34,                    .araddr
		.s_axi4_arlen            (i1_app_ss_mm_arlen),                                //   input,    width = 8,                    .arlen
		.s_axi4_arsize           (i1_app_ss_mm_arsize),                               //   input,    width = 3,                    .arsize
		.s_axi4_arburst          (i1_app_ss_mm_arburst),                              //   input,    width = 2,                    .arburst
		.s_axi4_arlock           (i1_app_ss_mm_arlock),                               //   input,    width = 1,                    .arlock
		.s_axi4_arcache          (i1_app_ss_mm_arcache),                              //   input,    width = 4,                    .arcache
		.s_axi4_arprot           (i1_app_ss_mm_arprot),                               //   input,    width = 3,                    .arprot
		.s_axi4_arqos            (i1_app_ss_mm_arqos),                                //   input,    width = 4,                    .arqos
		.s_axi4_aruser           (i1_app_ss_mm_aruser),                               //   input,   width = 14,                    .aruser
		.s_axi4_wready           (i1_ss_app_mm_wready),                               //  output,    width = 1,                    .wready
		.s_axi4_wvalid           (i1_app_ss_mm_wvalid),                               //   input,    width = 1,                    .wvalid
		.s_axi4_wdata            (i1_app_ss_mm_wdata),                                //   input,  width = 512,                    .wdata
		.s_axi4_wstrb            (i1_app_ss_mm_wstrb),                                //   input,   width = 64,                    .wstrb
		.s_axi4_wlast            (i1_app_ss_mm_wlast),                                //   input,    width = 1,                    .wlast
		.s_axi4_bready           (i1_app_ss_mm_bready),                               //   input,    width = 1,                    .bready
		.s_axi4_bvalid           (i1_ss_app_mm_bvalid),                               //  output,    width = 1,                    .bvalid
		.s_axi4_bid              (i1_ss_app_mm_bid),                                  //  output,    width = 9,                    .bid
		.s_axi4_bresp            (i1_ss_app_mm_bresp),                                //  output,    width = 2,                    .bresp
		.s_axi4_buser            (i1_ss_app_mm_buser),                                //  output,    width = 1,                    .buser
		.s_axi4_rready           (i1_app_ss_mm_rready),                               //   input,    width = 1,                    .rready
		.s_axi4_rvalid           (i1_ss_app_mm_rvalid),                               //  output,    width = 1,                    .rvalid
		.s_axi4_rid              (i1_ss_app_mm_rid),                                  //  output,    width = 9,                    .rid
		.s_axi4_rresp            (i1_ss_app_mm_rresp),                                //  output,    width = 2,                    .rresp
		.s_axi4_rdata            (i1_ss_app_mm_rdata),                                //  output,  width = 512,                    .rdata
		.s_axi4_rlast            (i1_ss_app_mm_rlast),                                //  output,    width = 1,                    .rlast
		.m_avmm_ready            (~msa_1_m_avmm_waitrequest),                         //   input,    width = 1,              m_avmm.waitrequest_n
		.m_avmm_read             (msa_1_m_avmm_read),                                 //  output,    width = 1,                    .read
		.m_avmm_write            (msa_1_m_avmm_write),                                //  output,    width = 1,                    .write
		.m_avmm_address          (msa_1_m_avmm_address),                              //  output,   width = 34,                    .address
		.m_avmm_burstcount       (msa_1_m_avmm_burstcount),                           //  output,    width = 7,                    .burstcount
		.m_avmm_writedata        (msa_1_m_avmm_writedata),                            //  output,  width = 512,                    .writedata
		.m_avmm_byteenable       (msa_1_m_avmm_byteenable),                           //  output,   width = 64,                    .byteenable
		.m_avmm_readdata         (msa_1_m_avmm_readdata),                             //   input,  width = 512,                    .readdata
		.m_avmm_readdatavalid    (msa_1_m_avmm_readdatavalid),                        //   input,    width = 1,                    .readdatavalid
		.local_cal_success       (mem1_local_cal_success),                            //  output,    width = 1,              status.local_cal_success
		.local_cal_fail          (mem1_local_cal_fail),                               //  output,    width = 1,                    .local_cal_fail
		.local_cal_success_in    (emif_1_status_local_cal_success),                   //   input,    width = 1,           status_in.local_cal_success
		.local_cal_fail_in       (emif_1_status_local_cal_fail),                      //   input,    width = 1,                    .local_cal_fail
		.ctrl_auto_precharge_req (msa_1_ctrl_auto_precharge_ctrl_auto_precharge_req)  //  output,    width = 1, ctrl_auto_precharge.ctrl_auto_precharge_req
	);

	mem_ss_mem_ss_501_qm5zaka_altera_mm_interconnect_1920_hzxas2a mm_interconnect_0 (
		.msa_0_m_avmm_address                                      (msa_0_m_avmm_address),                              //   input,   width = 34,                                        msa_0_m_avmm.address
		.msa_0_m_avmm_waitrequest                                  (msa_0_m_avmm_waitrequest),                          //  output,    width = 1,                                                    .waitrequest
		.msa_0_m_avmm_burstcount                                   (msa_0_m_avmm_burstcount),                           //   input,    width = 7,                                                    .burstcount
		.msa_0_m_avmm_byteenable                                   (msa_0_m_avmm_byteenable),                           //   input,   width = 64,                                                    .byteenable
		.msa_0_m_avmm_read                                         (msa_0_m_avmm_read),                                 //   input,    width = 1,                                                    .read
		.msa_0_m_avmm_readdata                                     (msa_0_m_avmm_readdata),                             //  output,  width = 512,                                                    .readdata
		.msa_0_m_avmm_readdatavalid                                (msa_0_m_avmm_readdatavalid),                        //  output,    width = 1,                                                    .readdatavalid
		.msa_0_m_avmm_write                                        (msa_0_m_avmm_write),                                //   input,    width = 1,                                                    .write
		.msa_0_m_avmm_writedata                                    (msa_0_m_avmm_writedata),                            //   input,  width = 512,                                                    .writedata
		.emif_0_ctrl_amm_0_address                                 (mm_interconnect_0_emif_0_ctrl_amm_0_address),       //  output,   width = 28,                                   emif_0_ctrl_amm_0.address
		.emif_0_ctrl_amm_0_write                                   (mm_interconnect_0_emif_0_ctrl_amm_0_write),         //  output,    width = 1,                                                    .write
		.emif_0_ctrl_amm_0_read                                    (mm_interconnect_0_emif_0_ctrl_amm_0_read),          //  output,    width = 1,                                                    .read
		.emif_0_ctrl_amm_0_readdata                                (mm_interconnect_0_emif_0_ctrl_amm_0_readdata),      //   input,  width = 512,                                                    .readdata
		.emif_0_ctrl_amm_0_writedata                               (mm_interconnect_0_emif_0_ctrl_amm_0_writedata),     //  output,  width = 512,                                                    .writedata
		.emif_0_ctrl_amm_0_burstcount                              (mm_interconnect_0_emif_0_ctrl_amm_0_burstcount),    //  output,    width = 7,                                                    .burstcount
		.emif_0_ctrl_amm_0_byteenable                              (mm_interconnect_0_emif_0_ctrl_amm_0_byteenable),    //  output,   width = 64,                                                    .byteenable
		.emif_0_ctrl_amm_0_readdatavalid                           (mm_interconnect_0_emif_0_ctrl_amm_0_readdatavalid), //   input,    width = 1,                                                    .readdatavalid
		.emif_0_ctrl_amm_0_waitrequest                             (~mm_interconnect_0_emif_0_ctrl_amm_0_waitrequest),  //   input,    width = 1,                                                    .waitrequest
		.msa_0_m_avmm_translator_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                    //   input,    width = 1, msa_0_m_avmm_translator_reset_reset_bridge_in_reset.reset
		.emif_0_emif_usr_clk_clk                                   (emif_0_emif_usr_clk_clk)                            //   input,    width = 1,                                 emif_0_emif_usr_clk.clk
	);

	mem_ss_mem_ss_501_qm5zaka_altera_mm_interconnect_1920_ahgugxq mm_interconnect_1 (
		.msa_1_m_avmm_address                                      (msa_1_m_avmm_address),                              //   input,   width = 34,                                        msa_1_m_avmm.address
		.msa_1_m_avmm_waitrequest                                  (msa_1_m_avmm_waitrequest),                          //  output,    width = 1,                                                    .waitrequest
		.msa_1_m_avmm_burstcount                                   (msa_1_m_avmm_burstcount),                           //   input,    width = 7,                                                    .burstcount
		.msa_1_m_avmm_byteenable                                   (msa_1_m_avmm_byteenable),                           //   input,   width = 64,                                                    .byteenable
		.msa_1_m_avmm_read                                         (msa_1_m_avmm_read),                                 //   input,    width = 1,                                                    .read
		.msa_1_m_avmm_readdata                                     (msa_1_m_avmm_readdata),                             //  output,  width = 512,                                                    .readdata
		.msa_1_m_avmm_readdatavalid                                (msa_1_m_avmm_readdatavalid),                        //  output,    width = 1,                                                    .readdatavalid
		.msa_1_m_avmm_write                                        (msa_1_m_avmm_write),                                //   input,    width = 1,                                                    .write
		.msa_1_m_avmm_writedata                                    (msa_1_m_avmm_writedata),                            //   input,  width = 512,                                                    .writedata
		.emif_1_ctrl_amm_0_address                                 (mm_interconnect_1_emif_1_ctrl_amm_0_address),       //  output,   width = 28,                                   emif_1_ctrl_amm_0.address
		.emif_1_ctrl_amm_0_write                                   (mm_interconnect_1_emif_1_ctrl_amm_0_write),         //  output,    width = 1,                                                    .write
		.emif_1_ctrl_amm_0_read                                    (mm_interconnect_1_emif_1_ctrl_amm_0_read),          //  output,    width = 1,                                                    .read
		.emif_1_ctrl_amm_0_readdata                                (mm_interconnect_1_emif_1_ctrl_amm_0_readdata),      //   input,  width = 512,                                                    .readdata
		.emif_1_ctrl_amm_0_writedata                               (mm_interconnect_1_emif_1_ctrl_amm_0_writedata),     //  output,  width = 512,                                                    .writedata
		.emif_1_ctrl_amm_0_burstcount                              (mm_interconnect_1_emif_1_ctrl_amm_0_burstcount),    //  output,    width = 7,                                                    .burstcount
		.emif_1_ctrl_amm_0_byteenable                              (mm_interconnect_1_emif_1_ctrl_amm_0_byteenable),    //  output,   width = 64,                                                    .byteenable
		.emif_1_ctrl_amm_0_readdatavalid                           (mm_interconnect_1_emif_1_ctrl_amm_0_readdatavalid), //   input,    width = 1,                                                    .readdatavalid
		.emif_1_ctrl_amm_0_waitrequest                             (~mm_interconnect_1_emif_1_ctrl_amm_0_waitrequest),  //   input,    width = 1,                                                    .waitrequest
		.msa_1_m_avmm_translator_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                //   input,    width = 1, msa_1_m_avmm_translator_reset_reset_bridge_in_reset.reset
		.emif_1_emif_usr_clk_clk                                   (emif_1_emif_usr_clk_clk)                            //   input,    width = 1,                                 emif_1_emif_usr_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~emif_0_emif_usr_reset_n_reset), //   input,  width = 1, reset_in0.reset
		.clk            (emif_0_emif_usr_clk_clk),        //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~emif_1_emif_usr_reset_n_reset),     //   input,  width = 1, reset_in0.reset
		.clk            (emif_1_emif_usr_clk_clk),            //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

endmodule
