# TCL File Generated by Component Editor 16.0
# Tue Jul 26 12:54:28 BST 2016
# DO NOT MODIFY


# 
# Arbiter "Arbiter" v2.0
#  2016.07.26.12:54:28
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module Arbiter
# 
set_module_property DESCRIPTION ""
set_module_property NAME Arbiter
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Arbiter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL arbiter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file arbiter.vhd VHDL PATH hdl/arbiter_v2.vhd TOP_LEVEL_FILE
add_fileset_file pkg_global.vhd VHDL PATH ../common/rtl/pkg_global.vhd
add_fileset_file arbiter_frr.vhd VHDL PATH ../common/rtl/arbiter_frr.vhd

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL arbiter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file arbiter.vhd VHDL PATH hdl/arbiter_v2.vhd
add_fileset_file pkg_global.vhd VHDL PATH ../common/rtl/pkg_global.vhd
add_fileset_file arbiter_frr.vhd VHDL PATH ../common/rtl/arbiter_frr.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL arbiter
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file arbiter.vhd VHDL PATH hdl/arbiter_v2.vhd
add_fileset_file pkg_global.vhd VHDL PATH ../common/rtl/pkg_global.vhd
add_fileset_file arbiter_frr.vhd VHDL PATH ../common/rtl/arbiter_frr.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point pcie_s0
# 
add_interface pcie_s0 avalon end
set_interface_property pcie_s0 addressUnits WORDS
set_interface_property pcie_s0 associatedClock clock
set_interface_property pcie_s0 associatedReset reset
set_interface_property pcie_s0 bitsPerSymbol 8
set_interface_property pcie_s0 bridgedAddressOffset ""
set_interface_property pcie_s0 bridgesToMaster ""
set_interface_property pcie_s0 burstOnBurstBoundariesOnly false
set_interface_property pcie_s0 burstcountUnits WORDS
set_interface_property pcie_s0 explicitAddressSpan 0
set_interface_property pcie_s0 holdTime 0
set_interface_property pcie_s0 linewrapBursts false
set_interface_property pcie_s0 maximumPendingReadTransactions 0
set_interface_property pcie_s0 maximumPendingWriteTransactions 0
set_interface_property pcie_s0 readLatency 1
set_interface_property pcie_s0 readWaitTime 1
set_interface_property pcie_s0 setupTime 0
set_interface_property pcie_s0 timingUnits Cycles
set_interface_property pcie_s0 transparentBridge false
set_interface_property pcie_s0 writeWaitTime 0
set_interface_property pcie_s0 ENABLED true
set_interface_property pcie_s0 EXPORT_OF ""
set_interface_property pcie_s0 PORT_NAME_MAP ""
set_interface_property pcie_s0 CMSIS_SVD_VARIABLES ""
set_interface_property pcie_s0 SVD_ADDRESS_GROUP ""

add_interface_port pcie_s0 pcie_s0_address address Input 2
add_interface_port pcie_s0 pcie_s0_read read Input 1
add_interface_port pcie_s0 pcie_s0_readdata readdata Output 32
add_interface_port pcie_s0 pcie_s0_write write Input 1
add_interface_port pcie_s0 pcie_s0_writedata writedata Input 32
add_interface_port pcie_s0 pcie_s0_waitrequest waitrequest Output 1
set_interface_assignment pcie_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment pcie_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment pcie_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment pcie_s0 embeddedsw.configuration.isPrintableDevice 0

# 
# connection point bmc_s0
# 
add_interface bmc_s0 avalon end
set_interface_property bmc_s0 addressUnits WORDS
set_interface_property bmc_s0 associatedClock clock
set_interface_property bmc_s0 associatedReset reset
set_interface_property bmc_s0 bitsPerSymbol 8
set_interface_property bmc_s0 bridgedAddressOffset ""
set_interface_property bmc_s0 bridgesToMaster ""
set_interface_property bmc_s0 burstOnBurstBoundariesOnly false
set_interface_property bmc_s0 burstcountUnits WORDS
set_interface_property bmc_s0 explicitAddressSpan 0
set_interface_property bmc_s0 holdTime 0
set_interface_property bmc_s0 linewrapBursts false
set_interface_property bmc_s0 maximumPendingReadTransactions 0
set_interface_property bmc_s0 maximumPendingWriteTransactions 0
set_interface_property bmc_s0 readLatency 1
set_interface_property bmc_s0 readWaitTime 1
set_interface_property bmc_s0 setupTime 0
set_interface_property bmc_s0 timingUnits Cycles
set_interface_property bmc_s0 transparentBridge false
set_interface_property bmc_s0 writeWaitTime 0
set_interface_property bmc_s0 ENABLED true
set_interface_property bmc_s0 EXPORT_OF ""
set_interface_property bmc_s0 PORT_NAME_MAP ""
set_interface_property bmc_s0 CMSIS_SVD_VARIABLES ""
set_interface_property bmc_s0 SVD_ADDRESS_GROUP ""

add_interface_port bmc_s0 bmc_s0_address address Input 2
add_interface_port bmc_s0 bmc_s0_read read Input 1
add_interface_port bmc_s0 bmc_s0_readdata readdata Output 32
add_interface_port bmc_s0 bmc_s0_write write Input 1
add_interface_port bmc_s0 bmc_s0_writedata writedata Input 32
add_interface_port bmc_s0 bmc_s0_waitrequest waitrequest Output 1
set_interface_assignment bmc_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment bmc_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment bmc_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment bmc_s0 embeddedsw.configuration.isPrintableDevice 0

# 
# connection point hps_gp_if
# 
add_interface hps_gp_if conduit end
set_interface_property hps_gp_if associatedClock ""
set_interface_property hps_gp_if associatedReset ""
set_interface_property hps_gp_if ENABLED true
set_interface_property hps_gp_if EXPORT_OF ""
set_interface_property hps_gp_if PORT_NAME_MAP ""
set_interface_property hps_gp_if CMSIS_SVD_VARIABLES ""
set_interface_property hps_gp_if SVD_ADDRESS_GROUP ""

add_interface_port hps_gp_if hps_gp_o gp_out Input 32
add_interface_port hps_gp_if hps_gp_i gp_in Output 32

