//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_ahls_persona_work21_01/setup01/afu_sources/ia840f_ahls_memory.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "ia840f_ahls_memory"
`define AFU_ACCEL_NAME0 "ia840f_ahls_memory"
`define AFU_ACCEL_UUID 128'h673c03a1_cef3_4c82_bf10_b12c247d9718
`define AFU_ACCEL_UUID0 128'h673c03a1_cef3_4c82_bf10_b12c247d9718
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
