##
## Verilog macros read from ofs_top ofs_top
##
## Generated by emit_project_macros.tcl
##

set_global_assignment -name VERILOG_MACRO "INCLUDE_USER_CLK"
set_global_assignment -name VERILOG_MACRO "DDR4_NUM_MEM_GROUPS=2"
set_global_assignment -name VERILOG_MACRO "INCLUDE_IA840F"
set_global_assignment -name VERILOG_MACRO "INCLUDE_DDR4"
set_global_assignment -name VERILOG_MACRO "INCLUDE_PR"
set_global_assignment -name VERILOG_MACRO "DISABLE_HE_HSSI_CRC"
set_global_assignment -name VERILOG_MACRO "INCLUDE_PCIE_SS"
set_global_assignment -name VERILOG_MACRO "INCLUDE_REMOTE_STP"
set_global_assignment -name VERILOG_MACRO "INCLUDE_LOCAL_MEM"
set_global_assignment -name VERILOG_MACRO "SHARED_AFU_MAIN_TO_PORT_AFU_INSTANCES"
set_global_assignment -name VERILOG_MACRO "AFU_MAIN_HAS_PF_VF_MUX"
