//
// Generated by ip_gen_sv_wrapper.tcl
//

`ifndef __MEM_SS_IP_PARAMS_H__
`define __MEM_SS_IP_PARAMS_H__


//
// mem_ss other IP configuration parameters affecting generation
//

`define MEM_SS_PARAM_ENABLE_MEM_CSR_INTF    "DISABLED"
`define MEM_SS_PARAM_ENABLE_MEM_PMON    "DISABLED"
`define MEM_SS_PARAM_EX_DESIGN_GEN_SIM    1
`define MEM_SS_PARAM_EX_DESIGN_GEN_SYNTH    1
`define MEM_SS_PARAM_EX_DESIGN_HDL_FORMAT    "VERILOG"
`define MEM_SS_PARAM_EX_DESIGN_HYDRA_HOST_INTF    "DISABLED"
`define MEM_SS_PARAM_RUN_COMPOSE    1

`endif  // __MEM_SS_IP_PARAMS_H__
