//
// Generated by ip_gen_sv_wrapper.tcl
//

interface mem_ss_i_axi_mm_if;
  wire  clk;
  wire  rst_n;
  logic [33:0] araddr;
  logic [1:0] arburst;
  logic [3:0] arcache;
  logic [8:0] arid;
  logic [7:0] arlen;
  logic arlock;
  logic [2:0] arprot;
  logic [3:0] arqos;
  logic [2:0] arsize;
  logic [13:0] aruser;
  logic arvalid;
  logic [33:0] awaddr;
  logic [1:0] awburst;
  logic [3:0] awcache;
  logic [8:0] awid;
  logic [7:0] awlen;
  logic awlock;
  logic [2:0] awprot;
  logic [3:0] awqos;
  logic [2:0] awsize;
  logic [13:0] awuser;
  logic awvalid;
  logic bready;
  logic rready;
  logic [511:0] wdata;
  logic wlast;
  logic [63:0] wstrb;
  logic wvalid;
  logic arready;
  logic awready;
  logic [8:0] bid;
  logic [1:0] bresp;
  logic buser;
  logic bvalid;
  logic [511:0] rdata;
  logic [8:0] rid;
  logic rlast;
  logic [1:0] rresp;
  logic rvalid;
  logic wready;

  modport subordinate (
    input  araddr, arburst, arcache, arid, arlen, arlock, arprot, arqos, arsize, aruser, arvalid, awaddr, awburst, awcache, awid, awlen, awlock, awprot, awqos, awsize, awuser, awvalid, bready, rready, wdata, wlast, wstrb, wvalid,
    output clk, rst_n, arready, awready, bid, bresp, buser, bvalid, rdata, rid, rlast, rresp, rvalid, wready
  );
  modport manager (
    input  clk, rst_n, arready, awready, bid, bresp, buser, bvalid, rdata, rid, rlast, rresp, rvalid, wready,
    output araddr, arburst, arcache, arid, arlen, arlock, arprot, arqos, arsize, aruser, arvalid, awaddr, awburst, awcache, awid, awlen, awlock, awprot, awqos, awsize, awuser, awvalid, bready, rready, wdata, wlast, wstrb, wvalid
  );
endinterface

interface mem_ss_mem_ddr4_if;
  logic [16:0] a;
  logic act_n;
  logic alert_n;
  logic [1:0] ba;
  logic [1:0] bg;
  logic ck;
  logic ck_n;
  logic cke;
  logic cs_n;
  wire  [7:0] dbi_n;
  wire  [63:0] dq;
  wire  [7:0] dqs;
  wire  [7:0] dqs_n;
  logic odt;
  logic par;
  logic reset_n;

  modport ip (
    input  alert_n,
    output a, act_n, ba, bg, ck, ck_n, cke, cs_n, odt, par, reset_n,
    inout  dbi_n, dq, dqs, dqs_n
  );
  modport app (
    input  a, act_n, ba, bg, ck, ck_n, cke, cs_n, odt, par, reset_n,
    output alert_n,
    inout  dbi_n, dq, dqs, dqs_n
  );
endinterface

interface mem_ss_mem_status_if;
  logic fail;
  logic success;

  modport ip (
    output fail, success
  );
  modport app (
    input  fail, success
  );
endinterface

interface mem_ss_subsystem_reset_if;
  logic app_ss_cold_rst_n;
  logic app_ss_rst_req;
  logic ss_app_cold_rst_ack_n;
  logic ss_app_rst_rdy;

  modport ip (
    input  app_ss_cold_rst_n, app_ss_rst_req,
    output ss_app_cold_rst_ack_n, ss_app_rst_rdy
  );
  modport app (
    input  ss_app_cold_rst_ack_n, ss_app_rst_rdy,
    output app_ss_cold_rst_n, app_ss_rst_req
  );
endinterface

module mem_ss_sv
  import mem_ss_param_pkg::*;
(
  input  wire [NUM_PORTS-1:0] mem_pll_ref_clk,
  input  wire [NUM_PORTS-1:0] mem_oct_rzqin,
  mem_ss_mem_ddr4_if.ip mem_ddr4[NUM_PORTS-1:0],
  output wire [NUM_PORTS-1:0] mem_ss_app_usr_clk,
  output wire [NUM_PORTS-1:0] mem_ss_app_usr_reset_n,
  mem_ss_subsystem_reset_if.ip subsystem_reset,
  mem_ss_i_axi_mm_if.subordinate i_axi_mm[NUM_PORTS-1:0],
  mem_ss_mem_status_if.ip mem_status[NUM_PORTS-1:0]
);

  mem_ss mem_ss (
    .app_ss_cold_rst_n(subsystem_reset.app_ss_cold_rst_n),
    .app_ss_rst_req(subsystem_reset.app_ss_rst_req),
    .i0_app_ss_mm_araddr(i_axi_mm[0].araddr),
    .i0_app_ss_mm_arburst(i_axi_mm[0].arburst),
    .i0_app_ss_mm_arcache(i_axi_mm[0].arcache),
    .i0_app_ss_mm_arid(i_axi_mm[0].arid),
    .i0_app_ss_mm_arlen(i_axi_mm[0].arlen),
    .i0_app_ss_mm_arlock(i_axi_mm[0].arlock),
    .i0_app_ss_mm_arprot(i_axi_mm[0].arprot),
    .i0_app_ss_mm_arqos(i_axi_mm[0].arqos),
    .i0_app_ss_mm_arsize(i_axi_mm[0].arsize),
    .i0_app_ss_mm_aruser(i_axi_mm[0].aruser),
    .i0_app_ss_mm_arvalid(i_axi_mm[0].arvalid),
    .i0_app_ss_mm_awaddr(i_axi_mm[0].awaddr),
    .i0_app_ss_mm_awburst(i_axi_mm[0].awburst),
    .i0_app_ss_mm_awcache(i_axi_mm[0].awcache),
    .i0_app_ss_mm_awid(i_axi_mm[0].awid),
    .i0_app_ss_mm_awlen(i_axi_mm[0].awlen),
    .i0_app_ss_mm_awlock(i_axi_mm[0].awlock),
    .i0_app_ss_mm_awprot(i_axi_mm[0].awprot),
    .i0_app_ss_mm_awqos(i_axi_mm[0].awqos),
    .i0_app_ss_mm_awsize(i_axi_mm[0].awsize),
    .i0_app_ss_mm_awuser(i_axi_mm[0].awuser),
    .i0_app_ss_mm_awvalid(i_axi_mm[0].awvalid),
    .i0_app_ss_mm_bready(i_axi_mm[0].bready),
    .i0_app_ss_mm_rready(i_axi_mm[0].rready),
    .i0_app_ss_mm_wdata(i_axi_mm[0].wdata),
    .i0_app_ss_mm_wlast(i_axi_mm[0].wlast),
    .i0_app_ss_mm_wstrb(i_axi_mm[0].wstrb),
    .i0_app_ss_mm_wvalid(i_axi_mm[0].wvalid),
    .i0_ss_app_mm_arready(i_axi_mm[0].arready),
    .i0_ss_app_mm_awready(i_axi_mm[0].awready),
    .i0_ss_app_mm_bid(i_axi_mm[0].bid),
    .i0_ss_app_mm_bresp(i_axi_mm[0].bresp),
    .i0_ss_app_mm_buser(i_axi_mm[0].buser),
    .i0_ss_app_mm_bvalid(i_axi_mm[0].bvalid),
    .i0_ss_app_mm_rdata(i_axi_mm[0].rdata),
    .i0_ss_app_mm_rid(i_axi_mm[0].rid),
    .i0_ss_app_mm_rlast(i_axi_mm[0].rlast),
    .i0_ss_app_mm_rresp(i_axi_mm[0].rresp),
    .i0_ss_app_mm_rvalid(i_axi_mm[0].rvalid),
    .i0_ss_app_mm_wready(i_axi_mm[0].wready),
    .i1_app_ss_mm_araddr(i_axi_mm[1].araddr),
    .i1_app_ss_mm_arburst(i_axi_mm[1].arburst),
    .i1_app_ss_mm_arcache(i_axi_mm[1].arcache),
    .i1_app_ss_mm_arid(i_axi_mm[1].arid),
    .i1_app_ss_mm_arlen(i_axi_mm[1].arlen),
    .i1_app_ss_mm_arlock(i_axi_mm[1].arlock),
    .i1_app_ss_mm_arprot(i_axi_mm[1].arprot),
    .i1_app_ss_mm_arqos(i_axi_mm[1].arqos),
    .i1_app_ss_mm_arsize(i_axi_mm[1].arsize),
    .i1_app_ss_mm_aruser(i_axi_mm[1].aruser),
    .i1_app_ss_mm_arvalid(i_axi_mm[1].arvalid),
    .i1_app_ss_mm_awaddr(i_axi_mm[1].awaddr),
    .i1_app_ss_mm_awburst(i_axi_mm[1].awburst),
    .i1_app_ss_mm_awcache(i_axi_mm[1].awcache),
    .i1_app_ss_mm_awid(i_axi_mm[1].awid),
    .i1_app_ss_mm_awlen(i_axi_mm[1].awlen),
    .i1_app_ss_mm_awlock(i_axi_mm[1].awlock),
    .i1_app_ss_mm_awprot(i_axi_mm[1].awprot),
    .i1_app_ss_mm_awqos(i_axi_mm[1].awqos),
    .i1_app_ss_mm_awsize(i_axi_mm[1].awsize),
    .i1_app_ss_mm_awuser(i_axi_mm[1].awuser),
    .i1_app_ss_mm_awvalid(i_axi_mm[1].awvalid),
    .i1_app_ss_mm_bready(i_axi_mm[1].bready),
    .i1_app_ss_mm_rready(i_axi_mm[1].rready),
    .i1_app_ss_mm_wdata(i_axi_mm[1].wdata),
    .i1_app_ss_mm_wlast(i_axi_mm[1].wlast),
    .i1_app_ss_mm_wstrb(i_axi_mm[1].wstrb),
    .i1_app_ss_mm_wvalid(i_axi_mm[1].wvalid),
    .i1_ss_app_mm_arready(i_axi_mm[1].arready),
    .i1_ss_app_mm_awready(i_axi_mm[1].awready),
    .i1_ss_app_mm_bid(i_axi_mm[1].bid),
    .i1_ss_app_mm_bresp(i_axi_mm[1].bresp),
    .i1_ss_app_mm_buser(i_axi_mm[1].buser),
    .i1_ss_app_mm_bvalid(i_axi_mm[1].bvalid),
    .i1_ss_app_mm_rdata(i_axi_mm[1].rdata),
    .i1_ss_app_mm_rid(i_axi_mm[1].rid),
    .i1_ss_app_mm_rlast(i_axi_mm[1].rlast),
    .i1_ss_app_mm_rresp(i_axi_mm[1].rresp),
    .i1_ss_app_mm_rvalid(i_axi_mm[1].rvalid),
    .i1_ss_app_mm_wready(i_axi_mm[1].wready),
    .mem0_ddr4_a(mem_ddr4[0].a),
    .mem0_ddr4_act_n(mem_ddr4[0].act_n),
    .mem0_ddr4_alert_n(mem_ddr4[0].alert_n),
    .mem0_ddr4_ba(mem_ddr4[0].ba),
    .mem0_ddr4_bg(mem_ddr4[0].bg),
    .mem0_ddr4_ck(mem_ddr4[0].ck),
    .mem0_ddr4_ck_n(mem_ddr4[0].ck_n),
    .mem0_ddr4_cke(mem_ddr4[0].cke),
    .mem0_ddr4_cs_n(mem_ddr4[0].cs_n),
    .mem0_ddr4_dbi_n(mem_ddr4[0].dbi_n),
    .mem0_ddr4_dq(mem_ddr4[0].dq),
    .mem0_ddr4_dqs(mem_ddr4[0].dqs),
    .mem0_ddr4_dqs_n(mem_ddr4[0].dqs_n),
    .mem0_ddr4_odt(mem_ddr4[0].odt),
    .mem0_ddr4_par(mem_ddr4[0].par),
    .mem0_ddr4_reset_n(mem_ddr4[0].reset_n),
    .mem0_local_cal_fail(mem_status[0].fail),
    .mem0_local_cal_success(mem_status[0].success),
    .mem0_oct_rzqin(mem_oct_rzqin[0]),
    .mem0_pll_ref_clk(mem_pll_ref_clk[0]),
    .mem0_ss_app_usr_clk(mem_ss_app_usr_clk[0]),
    .mem0_ss_app_usr_reset_n(mem_ss_app_usr_reset_n[0]),
    .mem1_ddr4_a(mem_ddr4[1].a),
    .mem1_ddr4_act_n(mem_ddr4[1].act_n),
    .mem1_ddr4_alert_n(mem_ddr4[1].alert_n),
    .mem1_ddr4_ba(mem_ddr4[1].ba),
    .mem1_ddr4_bg(mem_ddr4[1].bg),
    .mem1_ddr4_ck(mem_ddr4[1].ck),
    .mem1_ddr4_ck_n(mem_ddr4[1].ck_n),
    .mem1_ddr4_cke(mem_ddr4[1].cke),
    .mem1_ddr4_cs_n(mem_ddr4[1].cs_n),
    .mem1_ddr4_dbi_n(mem_ddr4[1].dbi_n),
    .mem1_ddr4_dq(mem_ddr4[1].dq),
    .mem1_ddr4_dqs(mem_ddr4[1].dqs),
    .mem1_ddr4_dqs_n(mem_ddr4[1].dqs_n),
    .mem1_ddr4_odt(mem_ddr4[1].odt),
    .mem1_ddr4_par(mem_ddr4[1].par),
    .mem1_ddr4_reset_n(mem_ddr4[1].reset_n),
    .mem1_local_cal_fail(mem_status[1].fail),
    .mem1_local_cal_success(mem_status[1].success),
    .mem1_oct_rzqin(mem_oct_rzqin[1]),
    .mem1_pll_ref_clk(mem_pll_ref_clk[1]),
    .mem1_ss_app_usr_clk(mem_ss_app_usr_clk[1]),
    .mem1_ss_app_usr_reset_n(mem_ss_app_usr_reset_n[1]),
    .ss_app_cold_rst_ack_n(subsystem_reset.ss_app_cold_rst_ack_n),
    .ss_app_rst_rdy(subsystem_reset.ss_app_rst_rdy)
  );

  assign i_axi_mm[0].clk = mem_ss_app_usr_clk[0];
  assign i_axi_mm[0].rst_n = mem_ss_app_usr_reset_n[0];
  assign i_axi_mm[1].clk = mem_ss_app_usr_clk[1];
  assign i_axi_mm[1].rst_n = mem_ss_app_usr_reset_n[1];

endmodule
