// scjio_agilex_intel_soft_core_jtag_io_10_nlyl3tq.v

// This file was auto-generated from intel_soft_core_jtag_io_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module scjio_agilex_intel_soft_core_jtag_io_10_nlyl3tq #(
		parameter CONTROL          = "host",
		parameter NAME             = "soft_jtag",
		parameter HOST_PRIORITY    = 200,
		parameter USE_TCK_ENA      = 1,
		parameter CLOCK_RATE_CLOCK = 0
	) (
		input  wire  jtag_clock_clk,       //   jtag_clock.clk,    Clock Input
		input  wire  jtag_signals_tms,     // jtag_signals.tms
		input  wire  jtag_signals_tdi,     //             .tdi
		output wire  jtag_signals_tdo,     //             .tdo
		input  wire  jtag_signals_tck_ena  //             .tck_ena
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (NAME != "soft_jtag")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					name_check ( .error(1'b1) );
		end
		if (HOST_PRIORITY != 200)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					host_priority_check ( .error(1'b1) );
		end
		if (USE_TCK_ENA != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					use_tck_ena_check ( .error(1'b1) );
		end
		if (CLOCK_RATE_CLOCK != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					clock_rate_clock_check ( .error(1'b1) );
		end
	endgenerate

	altera_sld_host_endpoint_wrapper #(
		.ENABLE_JTAG_IO_SELECTION (0),
		.CONTROL                  ("hubctrl"),
		.NAME                     ("soft_jtag"),
		.HOST_PRIORITY            (200),
		.BRIDGE_HOST              (0),
		.USE_TCK_ENA              (1),
		.NEGEDGE_TDO_LATCH        (0),
		.TYPE_NAME                (0),
		.INSTANCE_NAME            (0),
		.CLOCK_RATE_CLOCK         (0)
	) ep (
		.tck         (jtag_clock_clk),       //   input,  width = 1, clock.clk
		.tms         (jtag_signals_tms),     //   input,  width = 1,  node.tms
		.tdi         (jtag_signals_tdi),     //   input,  width = 1,      .tdi
		.tdo         (jtag_signals_tdo),     //  output,  width = 1,      .tdo
		.tck_ena     (jtag_signals_tck_ena), //   input,  width = 1,      .tck_ena
		.ena         (1'b0),                 // (terminated),                   
		.vir_tdi     (1'b0),                 // (terminated),                   
		.select_this (1'b0)                  // (terminated),                   
	);

endmodule
