// Copyright (C) 2023 Intel Corporation.
// SPDX-License-Identifier: MIT

//
// Description
//-----------------------------------------------------------------------------
//
// Common package for memory interface parameters. 
//
//-----------------------------------------------------------------------------

`ifndef __OFS_FIM_MEM_IF_PKG__
`define __OFS_FIM_MEM_IF_PKG__

// IP configuration database, generated by OFS script ofs_ip_cfg_db.tcl after
// IP generation.
`include "ofs_ip_cfg_db.vh"

package ofs_fim_mem_if_pkg;

   // FIM MEMORY PARAMS
   
   // Local memory interface bus width parameters:
   //
   // If no Memory Subsystem is present in the design or a type of memory interface isn't present in the subsystem component
   // then fallback values are selected for the parameters below.
   // The fallback values do not provide a functional mapping to IP interfaces. They are only defined for compilation
   // units included within common design files.


// The name of the AXI-MM AFU interface to EMIF varies depending on the underlying
// memory subsystem IP, but the general form of the interface is consistent. Macros
// describing the AXI-MM interface are generated by the SV wrapper script
// ip_gen_sv_wrapper.tcl. Code below searches for the board-specific subsystem and
// interface names and then invokes GEN_AXI_MEM_PARAMS.
`define GEN_AXI_MEM_PARAMS(SS_NAME, IFC_NAME) \
   // Number of AXI-MM channels to EMIF. The value may be lower than the number of DIMMs \
   // when some memory is mapped for use by HPS. \
   localparam NUM_MEM_CHANNELS        = ```SS_NAME``_PORT_``IFC_NAME``_IS_VEC; \
   \
   // AW \
   localparam AXI_MEM_AWID_WIDTH      = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_AWID; \
   localparam AXI_MEM_AWADDR_WIDTH    = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_AWADDR; \
 `ifdef IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_AWUSER \
   localparam AXI_MEM_AWUSER_WIDTH    = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_AWUSER; \
 `else \
   localparam AXI_MEM_AWUSER_WIDTH    = 1; \
 `endif \
   // W \
   localparam AXI_MEM_WDATA_WIDTH     = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_WDATA; \
 `ifdef IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_WUSER \
   localparam AXI_MEM_WUSER_WIDTH     = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_WUSER; \
 `else \
   localparam AXI_MEM_WUSER_WIDTH     = 1; \
 `endif \
   // B \
   localparam AXI_MEM_BID_WIDTH       = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_BID; \
 `ifdef IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_BUSER \
   localparam AXI_MEM_BUSER_WIDTH     = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_BUSER; \
  `else \
   localparam AXI_MEM_BUSER_WIDTH     = 1; \
 `endif \
   // AR \
   localparam AXI_MEM_ARID_WIDTH      = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_ARID; \
   localparam AXI_MEM_ARADDR_WIDTH    = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_ARADDR; \
 `ifdef IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_ARUSER \
   localparam AXI_MEM_ARUSER_WIDTH    = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_ARUSER; \
 `else \
   localparam AXI_MEM_ARUSER_WIDTH    = 1; \
 `endif \
   // R \
   localparam AXI_MEM_RDATA_WIDTH     = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_RDATA; \
   localparam AXI_MEM_RID_WIDTH       = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_RID; \
 `ifdef IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_RUSER \
   localparam AXI_MEM_RUSER_WIDTH     = `IFC_``SS_NAME``_``IFC_NAME``_IF_WIDTH_RUSER; \
 `else \
   localparam AXI_MEM_RUSER_WIDTH     = 1; \
 `endif \


//
// Figure out which memory subsystem is present in the design and set the parameters
// accordingly.
//
`ifdef MEM_SS_PORT_I_AXI_MM_IS_VEC

   // Memory subsystem (Agilex 7)
   `GEN_AXI_MEM_PARAMS(MEM_SS, I_AXI_MM)
   // Total number of all DDR4 channels (DIMMs) in the system
   localparam NUM_DDR4_CHANNELS = `MEM_SS_PORT_MEM_PLL_REF_CLK_IS_VEC;

   `ifdef MEM_SS_PORT_MEM_DDR4_IS_VEC
      localparam NUM_GROUP_0_DDR4_CHANNELS = `MEM_SS_PORT_MEM_DDR4_IS_VEC;
   `endif
   `ifdef MEM_SS_PORT_MEM_G1_DDR4_IS_VEC
      localparam NUM_GROUP_1_DDR4_CHANNELS = `MEM_SS_PORT_MEM_G1_DDR4_IS_VEC;
   `endif

`elsif AGX5_DDR4_SS_PORT_LOCAL_MEM_IS_VEC

   // QSYS project (Agilex 5 has no built-in memory subsystem)
   `GEN_AXI_MEM_PARAMS(AGX5_DDR4_SS, LOCAL_MEM)
   // Total number of all DDR4 channels (DIMMs) in the system
   localparam NUM_DDR4_CHANNELS = `AGX5_DDR4_SS_PORT_MEM_DDR4_MEM_REF_CLK_IS_VEC;

   `ifdef AGX5_DDR4_SS_PORT_MEM_DDR4_IS_VEC
      localparam NUM_GROUP_0_DDR4_CHANNELS = `AGX5_DDR4_SS_PORT_MEM_DDR4_IS_VEC;
   `endif
   `ifdef AGX5_DDR4_SS_PORT_MEM_G1_DDR4_IS_VEC
      localparam NUM_GROUP_1_DDR4_CHANNELS = `AGX5_DDR4_SS_PORT_MEM_G1_DDR4_IS_VEC;
   `endif

`elsif HBM_SS_PORT_I_APP_IS_VEC

   `GEN_AXI_MEM_PARAMS(HBM_SS, I_APP)
   // Not real -- defined to avoid compilation errors
   localparam NUM_DDR4_CHANNELS = 1;

`else
   // Defaults when local memory subsystem is not present
   localparam NUM_MEM_CHANNELS        = 1;
   localparam AXI_MEM_AWID_WIDTH      = 1;
   localparam AXI_MEM_AWADDR_WIDTH    = 32;
   localparam AXI_MEM_AWUSER_WIDTH    = 1;
   localparam AXI_MEM_WDATA_WIDTH     = 512;
   localparam AXI_MEM_WUSER_WIDTH     = 1;
   localparam AXI_MEM_BID_WIDTH       = 1;
   localparam AXI_MEM_BUSER_WIDTH     = 1;
   localparam AXI_MEM_ARID_WIDTH      = 1;
   localparam AXI_MEM_ARADDR_WIDTH    = 32;
   localparam AXI_MEM_ARUSER_WIDTH    = 1;
   localparam AXI_MEM_RDATA_WIDTH     = 512;
   localparam AXI_MEM_RID_WIDTH       = 1;
   localparam AXI_MEM_RUSER_WIDTH     = 1;

   localparam NUM_DDR4_CHANNELS       = 1;
`endif

`ifdef INCLUDE_HBM
   // Max request size for NOC with 64B bus
   localparam AXI_MEM_BURST_LEN_WIDTH = 6;
`else
   // This is defined by the AXI standard
   localparam AXI_MEM_BURST_LEN_WIDTH = 8;
`endif

`ifdef INCLUDE_HBM
   localparam NUM_HBM_DEVICES = `HBM_SS_PORT_HBM_UIB_CLK_CLK_IS_VEC;
   // TODO: Temporary
   localparam PER_HBM_ADDR_WIDTH = 34;  // 33 = 8GB; 34 = 16GB
`else
   localparam NUM_HBM_DEVICES = 0;
   localparam PER_HBM_ADDR_WIDTH = 0;
`endif

endpackage : ofs_fim_mem_if_pkg

`endif //  `ifndef __OFS_FIM_MEM_IF_PKG__
