// qual_test_clk_1x.v

// Generated using ACDS version 26.1.1 130

`timescale 1 ps / 1 ps
module qual_test_clk_1x (
		input  wire  in_clk,  //  in_clk.clk, Clock Input
		output wire  out_clk  // out_clk.clk, Clock Output
	);

	assign out_clk = in_clk;

endmodule
