# Copyright 2023 Intel Corporation
# SPDX-License-Identifier: MIT

namespace eval ::ofs_ip_cfg_db {
    set this_script_dir [file dirname [info script]]

    if { ! [info exists ip_db] } {
        # ip_db is the primary database of IP that will be processed.
        # Values will be added in project .tcl files next to IP imports.
        # Keys are the paths of the IP files. Values are a 2 entry list.
        # The first list entry is the name of the subsystem in OFS's
        # configuration space (e.g. "pcie_ss"). The second is the name
        # of the IP-specific Tcl file that will be run to extract the
        # parameters.
        #
        # The IP-specific Tcl script may either be a full path or the
        # name of a script in the same directory as this script.
        #
        # For example:
        #  dict set ::ofs_ip_cfg_db::ip_db $::env(BUILD_ROOT_REL)/ipss/pcie/qip/pcie_ss.ip [list pcie_ss pcie_ss_get_cfg.tcl]
        #
        set ip_db [dict create]
    }

    # Process IP defined in ip_db and generate configuration header files.
    # This procedure is invoked by a post-module hook in the FIM build after
    # quartus_ipgenerate.
    proc generate {} {
        ::ofs_ip_cfg_db::create_db

        set project [get_current_project]
        set revision [get_current_revision]

        # Emit a wrapper header file that includes all generated header files
        set wrapper_fn [open ofs_ip_cfg_db/ofs_ip_cfg_db.vh w]
        puts $wrapper_fn "//"
        puts $wrapper_fn "// Generated by OFS script ofs_ip_cfg_db.tcl"
        puts $wrapper_fn "//\n"
        puts $wrapper_fn "// Include all generated configuration files"

        # Emit a Tcl file to extend the include search path for header files generated
        # by ip_gen_sv_wrapper.tcl. This is a temporary measure until the functionality
        # of ip_gen_sv_wrapper is part of PD itself.
        set tcl_inc_fn [open ofs_ip_cfg_db/ip_gen_sv_wrapper_inc.tcl w]
        puts $tcl_inc_fn "##"
        puts $tcl_inc_fn "## Generated by OFS script ofs_ip_cfg_db.tcl"
        puts $tcl_inc_fn "##\n"
        puts $tcl_inc_fn "# Search paths for include files generated by ip_gen_sv_wrapper.tcl"

        # For each IP to process
        foreach ip_file [dict keys $::ofs_ip_cfg_db::ip_db] {
            set v [dict get $::ofs_ip_cfg_db::ip_db $ip_file]

            # Extract the name to give the IP in OFS configuration space
            set ip_name [lindex $v 0]
            # Extract the path to the script
            set ip_script [lindex $v 1]
            if { $ip_script != "" && ! [file exists $ip_script] } {
                # Script isn't a full path. Look in the script directory. (The same
                # directory as this ofs_ip_cfg_db.tcl script.)
                set p [file join $::ofs_ip_cfg_db::this_script_dir $ip_script]
                if { ! [file exists $p] } {
                    post_message -type error "OFS IP script $ip_script not found for $ip_file"
                    exit 1
                }
                set ip_script $p
            }

            # Generate a SystemVerilog wrapper around the IP
            gen_sv_wrapper $project $revision $ip_file $ip_name $wrapper_fn $tcl_inc_fn

            # Run the OFS-specific script to map more complex state from the IP to Verilog macros. If
            # the script is not provided only the default parameters extracted by ip_gen_sv_wrapper.tcl
            # will be used.
            if {$ip_script != ""} {
                set tgt_fname ofs_ip_cfg_${ip_name}.vh
                puts $wrapper_fn "`include \"${tgt_fname}\""

                if { [file exists ofs_ip_cfg_db/${tgt_fname}] &&
                     [file mtime ofs_ip_cfg_db/${tgt_fname}] > [file mtime ${ip_file}] } {
                    post_message "ofs_ip_cfg_db/${tgt_fname} is already up to date."
                    continue
                }

                set cmd "source ${ip_script}; emit_ip_cfg ofs_ip_cfg_db/${tgt_fname} [string toupper ${ip_name}]"
                set args [list --quartus-project=${project} --rev=${revision} --system-file=${ip_file} --cmd=${cmd}]
                post_message "Generating ofs_ip_cfg_db/${tgt_fname} with: qsys-script" -submsgs $args
                run_qsys_script args
            }
        }

        close $wrapper_fn
        close $tcl_inc_fn
    }

    # Generate a SystemVerilog wrapper around the IP and extract HWTCL parameters to Verilog macros.
    proc gen_sv_wrapper {project revision ip_file ip_name wrapper_fn tcl_inc_fn} {
        set ip_basename [file tail [file rootname $ip_file]]
        set ip_path [file dirname $ip_file]
        set ip_wrapper_dir "${ip_path}/sv_wrapper"
        file mkdir ${ip_wrapper_dir}
        set ip_sv_wrapper "${ip_wrapper_dir}/${ip_basename}_sv.sv"

        puts $tcl_inc_fn "set_global_assignment -name SEARCH_PATH \"${ip_wrapper_dir}\""

        puts $tcl_inc_fn "set_global_assignment -name SYSTEMVERILOG_FILE \"${ip_wrapper_dir}/${ip_basename}_param_pkg.sv\""
        puts $tcl_inc_fn "set_global_assignment -name SYSTEMVERILOG_FILE \"${ip_sv_wrapper}\""

        puts $wrapper_fn "`include \"${ip_basename}_if_info.vh\"    // In [regsub ^\[./\]* ${ip_wrapper_dir} {}]"
        puts $wrapper_fn "`include \"${ip_basename}_ip_params.vh\""

        # Don't regenerate files when the generated file exists and is younger
        # than the IP file.
        if { [file exists ${ip_sv_wrapper}] && [file size ${ip_sv_wrapper}] > 0 &&
             [file mtime ${ip_sv_wrapper}] > [file mtime ${ip_file}] } {
            post_message "${ip_sv_wrapper} is already up to date."
            return
        }

        # Generate a SystemVerilog wrapper around the IP
        set cmd "source $::env(BUILD_ROOT_REL)/ofs-common/scripts/common/syn/ip_get_cfg/ip_gen_sv_wrapper.tcl; gen_sv_wrapper ${ip_wrapper_dir}"
        set args [list --quartus-project=${project} --rev=${revision}]
        if {[lsearch [get_all_assignment_names] IP_SEARCH_PATHS] != -1} {
            # Project has IP_SEARCH_PATHS. Pass them to qsys-script.
            set paths ""
            foreach_in_collection p [get_all_global_assignments -name IP_SEARCH_PATHS] {
                set paths "${paths}[lindex $p 2],"
            }
            if {$paths != ""} {
                # qsys-script expects a comma-separated list of paths. Dollar at the
                # end adds default system paths.
                lappend args "--search-path=[regsub -all {;} $paths {,}]\$"
            }
        }
        lappend args --system-file=${ip_file} --cmd=${cmd}
        post_message "Generating ${ip_sv_wrapper} with: qsys-script" -submsgs $args
        puts $args
        run_qsys_script args
    }

    # qsys-script writes info messages to stderr, which confuses Tcl into
    # thinking there is a problem. Force stderr to stdout and just use the
    # exit code.
    proc run_qsys_script {args_ref} {
        upvar 1 $args_ref args
        if { [catch {exec qsys-script {*}${args} 2>@1} output] } {
            post_message $output
            post_message -type error "Error executing: qsys-script"
            exit 1
        } else {
            # Clean up the output of qsys-script. It prints a message every time
            # get_instance_* is called. Drop them.
            regsub -all {\n[^\n]*Info: (get_|send_message)[^\n]*} $output "" output
            regsub -all {Info: Info:} $output "Info:" output
            post_message $output
        }
    }

    # Create ofs_ip_cfg_db under the project if it doesn't exist
    proc create_db {} {
        if { ! [file exists ofs_ip_cfg_db] } {
            file mkdir ofs_ip_cfg_db

            # Create an empty wrapper .vh file that will be populated later
            close [open ofs_ip_cfg_db/ofs_ip_cfg_db.vh w]
            close [open ofs_ip_cfg_db/ip_gen_sv_wrapper_inc.tcl w]

            # Create README file
            set of [open ofs_ip_cfg_db/README w]
            puts $of "This directory is generated by the OFS common script ofs_ip_cfg_db.tcl."
            puts $of "It contains parameters extracted from IP. The extraction runs as a"
            puts $of "post-module hook after ipgenerate."
            puts $of ""
            puts $of "The names of IP files to parse are added by projects to the"
            puts $of "::ofs_ip_cfg_db::ip_db Tcl dictionary, defined and managed in"
            puts $of "ofs_ip_cfg_db.tcl."
            close $of
        }
    }
}

# Initialize the IP configuration database and load the generated sources
::ofs_ip_cfg_db::create_db
set_global_assignment -name SOURCE_TCL_SCRIPT_FILE ofs_ip_cfg_db/ip_gen_sv_wrapper_inc.tcl
