//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_examples_afu01/sources/hello_world/hw/rtl/hello_world.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "hello_world"
`define AFU_ACCEL_NAME0 "hello_world"
`define AFU_ACCEL_UUID 128'hc6aa954a_9b91_4a37_abc1_1d9f0709dcc3
`define AFU_ACCEL_UUID0 128'hc6aa954a_9b91_4a37_abc1_1d9f0709dcc3
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
