//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_examples_afu_debug01/sources_cap27/copy_engine/hw/rtl/copy_engine.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "copy_engine"
`define AFU_ACCEL_NAME0 "copy_engine"
`define AFU_ACCEL_UUID 128'h11446c9d_aa42_4085_9b3d_4eef9429a4ad
`define AFU_ACCEL_UUID0 128'h11446c9d_aa42_4085_9b3d_4eef9429a4ad
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
