// qual_test.v

// Generated using ACDS version 26.1.1 130

`timescale 1 ps / 1 ps
module qual_test (
		input  wire        clock_reset_clk,           //          clock_reset.clk
		input  wire        freeze_freeze,             //               freeze.freeze
		output wire [63:0] device_exception_bus_data, // device_exception_bus.data
		output wire        kernel_irqs_irq,           //          kernel_irqs.irq
		input  wire        avs_csr_read,              //              avs_csr.read
		output wire [63:0] avs_csr_readdata,          //                     .readdata
		output wire        avs_csr_readdatavalid,     //                     .readdatavalid
		input  wire        avs_csr_write,             //                     .write
		input  wire [63:0] avs_csr_writedata,         //                     .writedata
		input  wire [4:0]  avs_csr_address,           //                     .address
		input  wire [7:0]  avs_csr_byteenable,        //                     .byteenable
		output wire        avs_csr_waitrequest,       //                     .waitrequest
		input  wire        clock_reset_reset_reset_n  //    clock_reset_reset.reset_n
	);

	wire    clk_1x_out_clk_clk;             // clk_1x:out_clk -> [k0:clock, rst:clk, rst_controller:clk]
	wire    rst_controller_reset_out_reset; // rst_controller:reset_out -> k0:resetn
	wire    rst_out_reset_reset;            // rst:out_reset_n -> rst_controller:reset_in0

	qual_test_clk_1x clk_1x (
		.in_clk  (clock_reset_clk),    //   input,  width = 1,  in_clk.clk
		.out_clk (clk_1x_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	qual_test_k0 k0 (
		.clock                           (clk_1x_out_clk_clk),              //   input,   width = 1,                clock.clk
		.resetn                          (~rst_controller_reset_out_reset), //   input,   width = 1,               resetn.reset_n
		.freeze                          (freeze_freeze),                   //   input,   width = 1,               freeze.freeze
		.device_exception_bus            (device_exception_bus_data),       //  output,  width = 64, device_exception_bus.data
		.kernel_irqs                     (kernel_irqs_irq),                 //  output,   width = 1,          kernel_irqs.irq
		.csr_ring_root_avs_read          (avs_csr_read),                    //   input,   width = 1,    csr_ring_root_avs.read
		.csr_ring_root_avs_readdata      (avs_csr_readdata),                //  output,  width = 64,                     .readdata
		.csr_ring_root_avs_readdatavalid (avs_csr_readdatavalid),           //  output,   width = 1,                     .readdatavalid
		.csr_ring_root_avs_write         (avs_csr_write),                   //   input,   width = 1,                     .write
		.csr_ring_root_avs_writedata     (avs_csr_writedata),               //   input,  width = 64,                     .writedata
		.csr_ring_root_avs_address       (avs_csr_address),                 //   input,   width = 5,                     .address
		.csr_ring_root_avs_byteenable    (avs_csr_byteenable),              //   input,   width = 8,                     .byteenable
		.csr_ring_root_avs_waitrequest   (avs_csr_waitrequest)              //  output,   width = 1,                     .waitrequest
	);

	qual_test_rst rst (
		.clk         (clk_1x_out_clk_clk),        //   input,  width = 1,       clk.clk
		.in_reset_n  (clock_reset_reset_reset_n), //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (rst_out_reset_reset)        //  output,  width = 1, out_reset.reset_n
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~rst_out_reset_reset),           //   input,  width = 1, reset_in0.reset
		.clk            (clk_1x_out_clk_clk),             //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

endmodule
