// qual_test_k0.v

// Generated using ACDS version 26.1.1 130

`timescale 1 ps / 1 ps
module qual_test_k0 (
		input  wire        clock,                           //                clock.clk
		input  wire        resetn,                          //               resetn.reset_n
		input  wire        freeze,                          //               freeze.freeze
		output wire [63:0] device_exception_bus,            // device_exception_bus.data
		output wire        kernel_irqs,                     //          kernel_irqs.irq
		input  wire        csr_ring_root_avs_read,          //    csr_ring_root_avs.read
		output wire [63:0] csr_ring_root_avs_readdata,      //                     .readdata
		output wire        csr_ring_root_avs_readdatavalid, //                     .readdatavalid
		input  wire        csr_ring_root_avs_write,         //                     .write
		input  wire [63:0] csr_ring_root_avs_writedata,     //                     .writedata
		input  wire [4:0]  csr_ring_root_avs_address,       //                     .address
		input  wire [7:0]  csr_ring_root_avs_byteenable,    //                     .byteenable
		output wire        csr_ring_root_avs_waitrequest    //                     .waitrequest
	);

	qual_vec_op_report_di k0 (
		.clock                           (clock),                           //   input,   width = 1,                clock.clk
		.resetn                          (resetn),                          //   input,   width = 1,               resetn.reset_n
		.freeze                          (freeze),                          //   input,   width = 1,               freeze.freeze
		.device_exception_bus            (device_exception_bus),            //  output,  width = 64, device_exception_bus.data
		.kernel_irqs                     (kernel_irqs),                     //  output,   width = 1,          kernel_irqs.irq
		.csr_ring_root_avs_read          (csr_ring_root_avs_read),          //   input,   width = 1,    csr_ring_root_avs.read
		.csr_ring_root_avs_readdata      (csr_ring_root_avs_readdata),      //  output,  width = 64,                     .readdata
		.csr_ring_root_avs_readdatavalid (csr_ring_root_avs_readdatavalid), //  output,   width = 1,                     .readdatavalid
		.csr_ring_root_avs_write         (csr_ring_root_avs_write),         //   input,   width = 1,                     .write
		.csr_ring_root_avs_writedata     (csr_ring_root_avs_writedata),     //   input,  width = 64,                     .writedata
		.csr_ring_root_avs_address       (csr_ring_root_avs_address),       //   input,   width = 5,                     .address
		.csr_ring_root_avs_byteenable    (csr_ring_root_avs_byteenable),    //   input,   width = 8,                     .byteenable
		.csr_ring_root_avs_waitrequest   (csr_ring_root_avs_waitrequest)    //  output,   width = 1,                     .waitrequest
	);

endmodule
