//
// Generated by afu_json_mgr from /home/uwb_student00/ahls/new_BSP/work_examples_afu01/sources_dma_fix73/dma/hw/rtl/dma.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "dma"
`define AFU_ACCEL_NAME0 "dma"
`define AFU_ACCEL_UUID 128'h11446c9d_aa42_4085_9b3d_4eef9429a4ad
`define AFU_ACCEL_UUID0 128'h11446c9d_aa42_4085_9b3d_4eef9429a4ad
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ofs_plat_afu"

`endif // __AFU_JSON_INFO__
