"""Actual STA runner with real inert children and the actual numeric module."""
import contextlib
import copy
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from typing import Any
from unittest.mock import patch

E=Path(__file__).resolve().parent
SOURCE=E/'candidate06/run-sta06.py'
NUMERIC=E/'candidate06/sta_numeric06.py'
OUT=E/'runner-inert13.json'
assert not OUT.exists()
BASE=Path(tempfile.mkdtemp(prefix='persona-sta-runner-',dir=os.environ['TMPDIR']))
POPEN=subprocess.Popen
ROWS=[]

def put(p,s):
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(s)

def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def inv(root):return {str(p.relative_to(root)):{'kind':'file','bytes':p.stat().st_size,'sha256':sha(p)} for p in root.rglob('*') if p.is_file()}
def snap(root):return {str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()}
def load(name,path):
    spec=importlib.util.spec_from_file_location(name,path)
    assert spec and spec.loader
    mod:Any=importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

numeric=load('inert_sta_numeric_source',NUMERIC)
def summaries():
    app=numeric.APPLICATION_CLOCK
    native=[f"Type  : {family} '{app}'\nSlack : 1.000\nTNS   : 0.000\nCorner: Slow vid2 100C Model" for family in numeric.TIMING_FAMILIES]
    native += [f"Type  : {c} Max Skew 'set_max_skew'\nSlack : 0.010" for c in numeric.CORNER_TOKENS]
    native += ["Type  : Net Delay 'set_net_delay'\nSlack : 0.010"]
    main='\n'.join(numeric.HEADER)+'\n\n'+'\n\n'.join(native)+'\n\n'+'\n'.join(numeric.FOOTER)+'\n'
    hook=[f"Type  : {c} {short} '{app}'\nSlack : 1.000\nTNS   : 0.000" for c in numeric.CORNER_TOKENS.values() for short in numeric.HOOK_FAMILIES]
    passed='\n\n'.join(hook)+'\n\n'
    report='INERT REPORT, NOT QUARTUS\n'+''.join('; '+family+' '+c+' ;\n' for family in ('Max Skew Summary','Metastability Summary') for c in numeric.CORNER_TOKENS)
    frequency='# Generated by Platform Interface Manager user_clock_config.tcl\nafu-image/clock-frequency-low:100\nafu-image/clock-frequency-high:200\n'
    return main,passed,hook,report,frequency


def case(mode,clean,numeric_pass=None):
    root=BASE/mode
    root.mkdir()
    mod=load('sta_fixture_'+mode,SOURCE)
    mod.ROOT=root;mod.D=root/'design';mod.P=root/'control';mod.R=root/'run';mod.J=mod.D/'project';mod.Q=root/'INERT_QUARTUS';mod.MANIFEST=mod.P/'admitted.json'
    for p in (mod.D,mod.P,mod.J):p.mkdir(parents=True,exist_ok=True)
    qpf=mod.J/'ofs_top.qpf'
    qtext='QUARTUS_VERSION = "26.1"\nDATE = "INERT"\nPROJECT_REVISION = "ofs_pr_afu"\n'
    put(qpf,qtext)
    critical=mod.D/'selected.sv';put(critical,'INERT SOURCE, NOT HDL\n')
    external=root/'external.sv';put(external,'INERT EXTERNAL, NOT HDL\n')
    archive=root/'archive';original=root/'original-setup';release=root/'release';fitted=root/'original-fit';mapped=root/'original-mapped'
    for p in (archive,original,release,fitted,mapped):put(p/'entry','INERT INPUT\n')
    tool=root/'tool';put(tool,'INERT TOOL, NEVER RUN\n')
    put(mod.P/'runtime/CMakeLists.txt','# INERT\n')
    prepared=mod.P/'prepared.json';put(prepared,'{}\n')
    numericpath=mod.P/'runtime/sta_numeric06.py';put(numericpath,NUMERIC.read_text())
    protected={}
    for n in mod.REQUIRED_PHYSICAL_QDB:
        p=mod.J/n;put(p,'INERT ALREADY FITTED INPUT\n');protected[str(p)]={'kind':'file','bytes':p.stat().st_size,'sha256':sha(p)}
    runtime=mod.D/'runtime-report';put(runtime,'INERT BEFORE REPORT\n')
    criticalmap={str(critical):{'kind':'file','bytes':critical.stat().st_size,'sha256':sha(critical)},str(qpf):{'kind':'file','bytes':qpf.stat().st_size,'sha256':sha(qpf)},**protected}
    results={}
    for key in ('setup','release','simulation','synthesis','fit'):
        p=root/(key+'-result.json');put(p,'{}\n');results[key+'_result_file']=str(p);results[key+'_result_sha256']=sha(p)
    context={'exe':'/INERT_STA_EXE','cwd':str(mod.J),'argv':['ofs_top','-c','ofs_pr_afu','--snapshot=final','--multicorner=on','--do_report_timing','--do_report_cdc_viewer']}
    reports=list(mod.REQUIRED_REPORTS)
    m={**results,'scope':'persona-sta-only','interface_uuid':'INERT_STATIC','afu_uuid':'INERT_AFU',
       'source_root':str(fitted),'source_inventory':inv(fitted),'original_mapped_root':str(mapped),'original_mapped_inventory':inv(mapped),
       'critical_inputs':criticalmap,'protected_snapshot_inputs':protected,
       'runtime_outputs':{'runtime-report':inv(mod.D)['runtime-report']},
       'external_inputs':{str(external):{'kind':'file','bytes':external.stat().st_size,'sha256':sha(external)}},
       'archive_root':str(archive),'archive_inventory':inv(archive),'original_setup_root':str(original),'original_setup_inventory':inv(original),
       'release_root':str(release),'original_release_inventory':inv(release),'tools':{str(tool):{'bytes':tool.stat().st_size,'sha256':sha(tool)}},'opae_tools':{},
       'runner_sha256':sha(SOURCE),'cmake_sha256':sha(mod.P/'runtime/CMakeLists.txt'),'numeric_module_path':str(numericpath),'numeric_module_sha256':sha(numericpath),
       'prepared_metadata_file':str(prepared),'prepared_metadata_sha256':sha(prepared),'prerequisites':{},'contexts':[context],
       'required_reports':reports,'allowed_empty_reports':list(mod.ALLOWED_EMPTY_REPORTS),'required_physical_qdb':list(mod.REQUIRED_PHYSICAL_QDB),
       'qpf_before':{'bytes':qpf.stat().st_size,'sha256':sha(qpf),'text':qtext},'cpus':sorted(os.sched_getaffinity(0)),
       'address_space_limit_bytes':64*1024**3,'log_limit_bytes':1024 if mode=='overflow' else 1048576,
       'deadlines_seconds':{'configure':4,'version':4,'timing':0.5 if mode=='timeout' else 4}}
    actual=[]
    def preflight(_):
        if mode=='unissued':raise AssertionError('INERT unissued')
        return copy.deepcopy(m)
    def popen(argv,**kwargs):
        assert argv[0]=='/usr/bin/cmake'
        target=argv[argv.index('--target')+1] if '--target' in argv else 'configure'
        code='print("INERT stage")'
        if target=='version':code='print("INERT 26.1.1 Build 130 SC Pro Edition")'
        if target=='timing':
            main,passed,hook,report,frequency=summaries();failed=''
            if mode=='numeric_negative':
                main=main.replace('Slack : 1.000','Slack : -0.001',1).replace('TNS   : 0.000','TNS   : -0.001',1)
                passed=passed.replace(hook[0]+'\n\n','',1)
                failed=hook[0].replace('Slack : 1.000','Slack : -0.001').replace('TNS   : 0.000','TNS   : -0.001')+'\n\n'
            if mode=='negative_underflow':main=main.replace('Slack : 1.000','Slack : -1e-9999',1)
            if mode=='numeric_malformed':main=main.replace('Slack : 1.000','Slack : 0.000junk',1)
            if mode=='frequency_malformed':frequency+='afu-image/clock-frequency-low:100\n'
            if mode=='coverage_unresolved':report='INERT REPORT WITHOUT MODEL PANELS\n'
            if mode=='missing_timing_family':main=main.replace("Type  : Hold ","Type  : Unknown ",1)
            outputs={n:'INERT REPORT, NOT QUARTUS\n' for n in reports}
            outputs.update({'output_files/ofs_pr_afu.sta.rpt':report,'output_files/ofs_pr_afu.sta.summary':main,
                            'output_files/timing_report/clocks.sta.pass.summary':passed,'output_files/timing_report/clocks.sta.fail.summary':failed,
                            'output_files/user_clock_freq.txt':frequency,'qdb/inert-analysis-cache':'INERT NEW CACHE\n'})
            if mode=='missing_report':outputs.pop(reports[0])
            if mode=='missing_fail_file':outputs.pop('output_files/timing_report/clocks.sta.fail.summary')
            event={'accepted':True,'manifest_sha256':'a'*64,'native':{'exe':context['exe'],'cwd':context['cwd'],'argv':[context['exe'],*context['argv']]}}
            if mode=='wrong_callback':event['native']['cwd']='/INERT_WRONG'
            code='from pathlib import Path\nimport json\nJ=Path('+repr(str(mod.J))+')\nR=Path('+repr(str(mod.R))+')\nfor n,b in '+repr(outputs)+'.items():\n p=J/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(b)\n'
            if mode!='missing_callback':code+='(R/"gate-events.jsonl").write_text('+repr(json.dumps(event)+'\n')+')\n'
            code+='print("INERT: Quartus Prime Timing Analyzer was successful")\n'
            if mode=='nonzero':code+='raise SystemExit(7)\n'
            if mode=='error':code+='print("Error (suppressible): INERT")\n'
            if mode=='gate_marker':code+='print("IA840F_GATE_REJECTED: INERT")\n'
            if mode=='overflow':code+='print("x"*8192)\n'
            if mode=='timeout':code+='import time;time.sleep(8)\n'
            if mode=='drain_marker':code+='import os,time\npid=os.fork()\nif pid:os._exit(0)\ntime.sleep(0.3)\nprint("IA840F_GATE_REJECTED: INERT",flush=True)\ntime.sleep(8)\n'
            mutate={'critical_drift':critical,'external_drift':external,'archive_drift':archive/'entry','setup_drift':original/'entry','release_drift':release/'entry','tool_drift':tool,
                    'control_drift':prepared,'parser_drift':numericpath,'predecessor_drift':Path(m['setup_result_file']),'fit_result_drift':Path(m['fit_result_file']),
                    'mapped_original_drift':mapped/'entry','fitted_original_drift':fitted/'entry','snapshot_drift':Path(next(iter(protected)))}
            if mode in mutate:code+='Path('+repr(str(mutate[mode]))+').write_text("DRIFT")\n'
            if mode=='missing_physical_input':code+='Path('+repr(next(iter(protected)))+').unlink()\n'
            if mode=='mapped_extra_file':code+='Path('+repr(str(mapped/'extra'))+').write_text("UNREVIEWED")\n'
            if mode=='fitted_extra_file':code+='Path('+repr(str(fitted/'extra'))+').write_text("UNREVIEWED")\n'
            if mode=='qpf_date':code+='Path('+repr(str(qpf))+').write_text('+repr(qtext.replace('DATE = "INERT"','DATE = "INERT LATER"'))+')\n'
            if mode=='qpf_revision':code+='Path('+repr(str(qpf))+').write_text('+repr(qtext.replace('ofs_pr_afu','wrong'))+')\n'
            if mode=='qpf_version':code+='Path('+repr(str(qpf))+').write_text('+repr(qtext.replace('26.1','25.1'))+')\n'
            if mode=='qpf_duplicate':code+='Path('+repr(str(qpf))+').write_text('+repr(qtext+'PROJECT_REVISION = "ofs_pr_afu"\n')+')\n'
            if mode=='qpf_unknown':code+='Path('+repr(str(qpf))+').write_text('+repr(qtext+'UNREVIEWED = "value"\n')+')\n'
            if mode=='runtime_changed':code+='Path('+repr(str(runtime))+').write_text("INERT NATIVE UPDATED REPORT")\n'
            if mode=='runtime_removed':code+='Path('+repr(str(runtime))+').unlink()\n'
        actual.append({'requested':argv,'actual':[sys.executable,'-c',code]})
        return POPEN([sys.executable,'-c',code],**kwargs)
    def command(argv,**kwargs):
        assert argv[0]=='tmux'
        return subprocess.CompletedProcess(argv,0)
    oldpost=mod.postflight
    def post(*args):
        if mode=='postflight_fault':raise RuntimeError('INERT postflight exception')
        return oldpost(*args)
    before=snap(root)
    with patch.object(mod,'preflight',side_effect=preflight),patch.object(mod,'postflight',side_effect=post),patch.object(mod.subprocess,'Popen',side_effect=popen),patch.object(mod.subprocess,'run',side_effect=command),patch.object(sys,'argv',['INERT','a'*64]),patch.dict(os.environ,{'LM_LICENSE_FILE':'INERT','MGLS_LICENSE_FILE':'INERT','SALT_LICENSE_SERVER':'INERT'}),contextlib.redirect_stdout(io.StringIO()):
        if mode=='unissued':
            try:mod.run()
            except AssertionError:pass
            else:raise AssertionError('unissued accepted')
            assert not mod.R.exists() and not actual and snap(root)==before
            ROWS.append({'case':mode,'rejected_before_write':True})
            return
        rc=mod.run();r=json.loads((mod.R/'result.json').read_text())
        assert r['execution_clean'] is clean and (rc==0) is clean,(mode,rc,{k:r.get(k) for k in ('error','postflight_errors','postflight_exception','numeric_parse_valid','numeric_screen_pass')})
        assert r.get('timing_accepted',False) is False
        if numeric_pass is not None:assert r['numeric_screen_pass'] is numeric_pass,(mode,r['numeric_screen_pass'])
        assert all(not c.get('owned_group_live_after') for c in r['commands'])
        if mode=='timeout':assert r['commands'][-1]['effective_rc']==124
        if mode=='drain_marker':assert r['commands'][-1]['gate_rejected'] and not r['commands'][-1]['timeout']
        if mode in ('numeric_negative','negative_underflow'):assert r['numeric_parse_valid'] and not r['numeric_screen_pass'] and r['numerical_screen']['violations']
        if mode=='coverage_unresolved':assert r['numeric_parse_valid'] and r['numerical_screen']['unresolved']
        if mode in ('fitted_original_drift','fitted_extra_file'):assert not r['original_fitted_preserved']
        if mode in ('mapped_original_drift','mapped_extra_file'):assert not r['original_mapped_preserved']
        if mode=='runtime_changed':assert r['runtime_outputs_after']['runtime-report']['before']['sha256']!=r['runtime_outputs_after']['runtime-report']['after']['sha256']
        if mode=='runtime_removed':assert not r['runtime_outputs_after']['runtime-report']['after']['exists']
        after=snap(root);n=len(actual)
        try:mod.run()
        except FileExistsError:pass
        else:raise AssertionError('spent replay accepted')
        assert snap(root)==after and len(actual)==n
    ROWS.append({'case':mode,'expected_execution_clean':clean,'actual_rc':rc,'execution_clean':r['execution_clean'],'numeric_parse_valid':r.get('numeric_parse_valid'),
                 'numeric_screen_pass':r.get('numeric_screen_pass'),'timing_accepted':r.get('timing_accepted',False),'commands':r['commands'],
                 'postflight_errors':r.get('postflight_errors'),'postflight_exception':r.get('postflight_exception'),'diagnostics':r.get('diagnostics'),
                 'actual_inert_commands':actual,'replay_preserved':True})

for mode in ('clean','runtime_changed','runtime_removed'):case(mode,True,True)
for mode in ('numeric_negative','negative_underflow','coverage_unresolved'):case(mode,True,False)
for mode in ('unissued','nonzero','error','gate_marker','missing_callback','wrong_callback','missing_report','missing_fail_file','missing_physical_input',
             'critical_drift','external_drift','archive_drift','setup_drift','release_drift','tool_drift','control_drift','parser_drift','predecessor_drift','fit_result_drift',
             'mapped_original_drift','fitted_original_drift','mapped_extra_file','fitted_extra_file','snapshot_drift','qpf_date','qpf_revision','qpf_version','qpf_duplicate','qpf_unknown',
             'overflow','timeout','drain_marker','postflight_fault','numeric_malformed','frequency_malformed','missing_timing_family'):
    case(mode,False)
OUT.write_text(json.dumps({'success':True,'scope':'actual runner and numeric module with mocked admission/CMake/tmux/callbacks; real inert Python children and synthetic reports, no native STA',
                           'runner_sha256':sha(SOURCE),'numeric_sha256':sha(NUMERIC),'count':len(ROWS),'cases':ROWS,'scratch':str(BASE)},indent=2)+'\n')
print(json.dumps({'success':True,'runner_cases':len(ROWS),'native_tools_executed':False,'output':str(OUT)}))
