"""Retained-format and adversarial STA-screen tests; no native execution."""
import copy
import hashlib
import importlib.util
import json
from pathlib import Path
import re

E = Path(__file__).resolve().parent
SOURCE = E/'candidate06/sta_numeric06.py'
OUT = E/'numeric-inert10.json'
assert not OUT.exists()
spec = importlib.util.spec_from_file_location('sta_numeric_test', SOURCE)
assert spec and spec.loader
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
rows = []


def outcome(name, result, expected, parse_expected=None):
    assert result['screen_pass'] is expected, (name, result['unresolved'], result['violations'])
    if parse_expected is not None:
        assert result['parse_valid'] is parse_expected, (name, result['parse_valid'])
    assert result['timing_accepted'] is False
    for key in ('main', 'hook_pass', 'hook_fail'):
        parsed = result[key]
        assert parsed['line_accounting_complete']
        assert parsed['type_occurrences'] == len(parsed['records'])+len(parsed['invalid_records'])
    rows.append({'case': name, 'expected_screen_pass': expected, 'screen_pass': result['screen_pass'],
                 'parse_valid': result['parse_valid'], 'numeric_pass': result['numeric_pass'],
                 'records': {key: result[key]['type_occurrences'] for key in ('main', 'hook_pass', 'hook_fail')},
                 'invalid_record_count': sum(len(result[key]['invalid_records']) for key in ('main', 'hook_pass', 'hook_fail')),
                 'violations': result['violations'], 'unresolved': result['unresolved']})


panels = ''.join('; '+family+' '+corner+' ;\n' for family in ('Max Skew Summary', 'Metastability Summary') for corner in mod.CORNER_TOKENS)
corners = mod.report_corners(panels.splitlines())
assert not corners['unresolved']
clock = mod.APPLICATION_CLOCK
native_records = [f"Type  : {family} '{clock}'\nSlack : 1.000\nTNS   : 0.000\nCorner: Slow vid2 100C Model" for family in mod.TIMING_FAMILIES]
native_records += [f"Type  : {corner} Max Skew 'set_max_skew'\nSlack : 0.010" for corner in mod.CORNER_TOKENS]
native_records += ["Type  : Net Delay 'set_net_delay'\nSlack : 0.010"]*2
main = '\n'.join(mod.HEADER)+'\n\n'+'\n\n'.join(native_records)+'\n\n'+'\n'.join(mod.FOOTER)+'\n'
hook_records = [f"Type  : {corner} {short} '{clock}'\nSlack : 1.000\nTNS   : 0.000" for corner in mod.CORNER_TOKENS.values() for short in mod.HOOK_FAMILIES]
passed = '\n\n'.join(hook_records)+'\n\n'
frequency = '# Generated by Platform Interface Manager user_clock_config.tcl\nafu-image/clock-frequency-low:100\nafu-image/clock-frequency-high:200\n'
base = {'main': main, 'passed': passed, 'failed': '', 'frequency': frequency, 'corners': corners}


def screen(data):
    return mod.screen(data['main'], data['passed'], data['failed'], data['frequency'], data['corners'])


def trial(name, transform, expected=False, parse_expected=None):
    data = copy.deepcopy(base)
    transform(data)
    outcome(name, screen(data), expected, parse_expected)


outcome('synthetic_complete_positive', screen(base), True, True)
trial('legitimate_identical_constraint_duplicates', lambda d: d.update(main=d['main'].replace(native_records[-1], native_records[-1]+'\n\n'+native_records[-1], 1)), True, True)
trial('frequency_zero_for_unused_user_clocks', lambda d: d.update(frequency=d['frequency'].replace(':100', ':0').replace(':200', ':0')), True, True)
trial('negative_zero_is_exact_zero', lambda d: d.update(main=d['main'].replace('Slack : 1.000', 'Slack : -0.000', 1)), True, True)

for label in ('current26-static-main', 'prior25-persona-main'):
    path = E/'fixtures08'/(label+'.summary')
    parsed = mod.parse_summary(path.read_text(), label, 'main')
    expected_count = json.loads((E/'report-fixture-index08.json').read_text())['fixtures'][label]['record_blocks_observed']
    assert parsed['parse_valid'] and len(parsed['records']) == expected_count
    assert all(mod.exact_number(r['slack']) >= 0 for r in parsed['records'])
    rows.append({'case': 'retained_'+label, 'parse_valid': True, 'record_count': expected_count, 'fixture_sha256': sha(path), 'scope': 'format regression only, no new persona outcome'})
oldmain = (E/'fixtures08/prior25-persona-main.summary').read_text()
oldpass = (E/'fixtures08/prior25-hook-pass.summary').read_text()
oldfail = (E/'fixtures08/prior25-hook-fail.summary').read_text()
outcome('retained_prior_persona_joined_formats', mod.screen(oldmain, oldpass, oldfail, frequency, corners), True, True)

for token in ('NaN', 'Inf', '-Infinity', 'N/A', '--', '', '0.000garbage', '0.000 1', '1e', '+'):
    trial('reject_slack_token_'+repr(token), lambda d, token=token: d.update(main=d['main'].replace('Slack : 1.000', 'Slack : '+token, 1)), False, False)
for token in ('NaN', 'Inf', 'N/A', '--', '', '0.000x'):
    trial('reject_tns_token_'+repr(token), lambda d, token=token: d.update(main=d['main'].replace('TNS   : 0.000', 'TNS   : '+token, 1)), False, False)
for token in ('-0.001', '-1e-9999', '-0.00000000000000000000000000000000000000000001'):
    trial('negative_slack_not_rounded_'+token, lambda d, token=token: d.update(main=d['main'].replace('Slack : 1.000', 'Slack : '+token, 1)), False, True)
for token in ('0.001', '-0.001', '1e-9999', '-1e-9999'):
    trial('nonzero_tns_not_rounded_'+token, lambda d, token=token: d.update(main=d['main'].replace('TNS   : 0.000', 'TNS   : '+token, 1)), False, True)

trial('missing_main_header', lambda d: d.update(main=d['main'].replace('\n'.join(mod.HEADER)+'\n\n', '', 1)), False, False)
trial('empty_main', lambda d: d.update(main=''), False, False)
trial('empty_hook_pass', lambda d: d.update(passed=''), False, False)
trial('trailing_junk_after_footer', lambda d: d.update(main=d['main']+'UNEXPLAINED\n'), False, False)
trial('orphan_between_records', lambda d: d.update(main=d['main'].replace('\n\nType', '\n\nORPHAN\n\nType', 1)), False, False)
trial('missing_clock_tns', lambda d: d.update(main=d['main'].replace('TNS   : 0.000\n', '', 1)), False, False)
trial('missing_clock_corner', lambda d: d.update(main=d['main'].replace('Corner: Slow vid2 100C Model\n', '', 1)), False, False)
trial('duplicate_slack_field', lambda d: d.update(main=d['main'].replace('Slack : 1.000', 'Slack : 1.000\nSlack : 1.000', 1)), False, False)
trial('unknown_record_field', lambda d: d.update(main=d['main'].replace('TNS   : 0.000', 'UNREVIEWED : 0.000', 1)), False, False)
trial('unknown_native_family', lambda d: d.update(main=d['main'].replace('Type  : Setup ', 'Type  : Setups ', 1)), False, False)
trial('type_numeric_extension', lambda d: d.update(main=d['main'].replace('Type  : Setup ', 'Type  : Setup1 ', 1)), False, False)
trial('malformed_type_plus_valid_record', lambda d: d.update(main=d['main'].replace('\n\n'+mod.DASH, '\n\nType BROKEN\nSlack : 0.000\n\n'+mod.DASH, 1)), False, False)
trial('constraint_extra_tns', lambda d: d.update(main=d['main'].replace('Slack : 0.010', 'Slack : 0.010\nTNS : 0.000', 1)), False, False)
trial('constraint_missing_slack', lambda d: d.update(main=d['main'].replace('Slack : 0.010', '', 1)), False, False)
trial('constraint_nan', lambda d: d.update(main=d['main'].replace('Slack : 0.010', 'Slack : NaN', 1)), False, False)
trial('constraint_negative_underflow', lambda d: d.update(main=d['main'].replace('Slack : 0.010', 'Slack : -1e-9999', 1)), False, True)
trial('repeated_domain_not_last_wins', lambda d: d.update(main=d['main'].replace(native_records[0], native_records[0]+'\n\n'+native_records[0], 1)), False, True)
trial('duplicate_hook_key', lambda d: d.update(passed=d['passed']+hook_records[0]+'\n\n'), False, True)
trial('same_hook_key_across_pass_fail', lambda d: d.update(failed=hook_records[0].replace('Slack : 1.000', 'Slack : -0.001')+'\n\n'), False, True)
trial('nonnegative_hook_fail', lambda d: d.update(failed=hook_records[0]+'\n\n'), False, True)
trial('negative_hook_pass', lambda d: d.update(passed=d['passed'].replace('Slack : 1.000', 'Slack : -0.001', 1)), False, True)
trial('malformed_hook_extra_field', lambda d: d.update(passed=d['passed'].replace('TNS   : 0.000', 'TNS   : 0.000\nCorner: EXTRA', 1)), False, False)
trial('unknown_hook_family', lambda d: d.update(passed=d['passed'].replace(' setup ', ' setup_extra ', 1)), False, False)
trial('missing_hook_application_corner_family', lambda d: d.update(passed=d['passed'].replace(hook_records[0]+'\n\n', '', 1)), False, True)
trial('all_hold_family_omitted', lambda d: d.update(main=d['main'].replace(native_records[1]+'\n\n', '', 1)), False, True)
trial('missing_per_model_panels', lambda d: d.update(corners=mod.report_corners([])), False, True)
trial('unknown_actual_corner_label', lambda d: d.update(corners=mod.report_corners(panels.replace('Slow vid2 100C Model', 'Slow UNKNOWN 100C Model').splitlines())), False, True)
trial('corner_panel_sets_disagree', lambda d: d.update(corners=mod.report_corners(panels.replace('; Max Skew Summary Slow vid2 100C Model ;\n', '').splitlines())), False, True)
trial('hook_unknown_corner', lambda d: d.update(passed=d['passed'].replace('2_slow_vid2_100c', 'UNOBSERVED_CORNER', 1)), False, True)
trial('main_corner_not_in_panels', lambda d: d.update(main=d['main'].replace('Corner: Slow vid2 100C Model', 'Corner: Slow OTHER 100C Model', 1)), False, True)
for token in ('NaN', 'Inf', '-1', '100junk', ''):
    trial('frequency_bad_'+repr(token), lambda d, token=token: d.update(frequency=d['frequency'].replace('low:100', 'low:'+token)), False, False)
trial('frequency_missing_high', lambda d: d.update(frequency=d['frequency'].replace('afu-image/clock-frequency-high:200\n', '')), False, False)
trial('frequency_duplicate_low', lambda d: d.update(frequency=d['frequency']+'afu-image/clock-frequency-low:100\n'), False, False)
trial('frequency_extra_record', lambda d: d.update(frequency=d['frequency']+'extra:100\n'), False, False)

# Valid negative analysis: move one hook row into fail with a negative number.
def negative_analysis(d):
    d['main'] = d['main'].replace('Slack : 1.000', 'Slack : -0.001', 1).replace('TNS   : 0.000', 'TNS   : -0.001', 1)
    d['passed'] = d['passed'].replace(hook_records[0]+'\n\n', '', 1)
    d['failed'] = hook_records[0].replace('Slack : 1.000', 'Slack : -0.001').replace('TNS   : 0.000', 'TNS   : -0.001')+'\n\n'
trial('valid_completed_negative_analysis', negative_analysis, False, True)

# A noncritical per-corner population difference is unresolved applicability,
# not a fabricated negative path or an automatic all-domain Cartesian demand.
def noncritical_gap(d):
    extra = "Type  : Setup 'INERT_OTHER_CLOCK'\nSlack : 1.000\nTNS   : 0.000\nCorner: Slow vid2 100C Model"
    d['main'] = d['main'].replace('\n\n'+mod.DASH, '\n\n'+extra+'\n\n'+mod.DASH, 1)
    for token in list(mod.CORNER_TOKENS.values())[1:]:
        d['passed'] += f"Type  : {token} setup 'INERT_OTHER_CLOCK'\nSlack : 1.000\nTNS   : 0.000\n\n"
trial('noncritical_corner_gap_requires_disposition', noncritical_gap, False, True)

result = {'success': True, 'scope': 'native retained-format fixtures and synthetic adversarial records; no native STA or current timing acceptance',
          'module_sha256': sha(SOURCE), 'fixture_index_sha256': sha(E/'report-fixture-index08.json'),
          'count': len(rows), 'cases': rows}
OUT.write_text(json.dumps(result, indent=2)+'\n')
print(json.dumps({'success': True, 'numeric_cases': len(rows), 'output': str(OUT)}))
