// IA840F component-level DMA + generated AHLS fabric integration.
// Uses pinned AI Suite topology and PIM interfaces; no physical PIM mapper here.
// External MMIO must be single-beat; outer-aperture validation remains required.
`include "ofs_plat_if.vh"
module ia840f_ahls_memory_core (
    input wire clock_reset_clk,
    input wire clock_reset_reset_reset_n,
    input wire freeze_freeze,
    output wire [63:0] device_exception_bus_data,
    output wire kernel_irqs_irq,
    input wire [15:0] mmio_control_awid,
    input wire [19:0] mmio_control_awaddr,
    input wire [7:0] mmio_control_awlen,
    input wire [2:0] mmio_control_awsize,
    input wire [1:0] mmio_control_awburst,
    input wire mmio_control_awuser,
    input wire mmio_control_awvalid,
    output wire mmio_control_awready,
    input wire [63:0] mmio_control_wdata,
    input wire [7:0] mmio_control_wstrb,
    input wire mmio_control_wvalid,
    input wire mmio_control_wuser,
    output wire mmio_control_wready,
    output wire [15:0] mmio_control_bid,
    output wire [1:0] mmio_control_bresp,
    output wire mmio_control_buser,
    output wire mmio_control_bvalid,
    input wire mmio_control_bready,
    input wire [15:0] mmio_control_arid,
    input wire [19:0] mmio_control_araddr,
    input wire [7:0] mmio_control_arlen,
    input wire [2:0] mmio_control_arsize,
    input wire [1:0] mmio_control_arburst,
    input wire mmio_control_aruser,
    input wire mmio_control_arvalid,
    output wire mmio_control_arready,
    output wire [15:0] mmio_control_rid,
    output wire [63:0] mmio_control_rdata,
    output wire [1:0] mmio_control_rresp,
    output wire mmio_control_rlast,
    output wire mmio_control_rvalid,
    input wire mmio_control_rready,
    output wire mmio_control_ruser,
    output wire [17:0] bank_out0_awid,
    output wire [33:0] bank_out0_awaddr,
    output wire [7:0] bank_out0_awlen,
    output wire [2:0] bank_out0_awsize,
    output wire [1:0] bank_out0_awburst,
    output wire bank_out0_awlock,
    output wire [3:0] bank_out0_awcache,
    output wire [2:0] bank_out0_awprot,
    output wire [1:0] bank_out0_awuser,
    output wire [3:0] bank_out0_awqos,
    output wire [3:0] bank_out0_awregion,
    output wire bank_out0_awvalid,
    input wire bank_out0_awready,
    output wire [511:0] bank_out0_wdata,
    output wire [63:0] bank_out0_wstrb,
    output wire bank_out0_wlast,
    output wire bank_out0_wvalid,
    output wire [1:0] bank_out0_wuser,
    input wire bank_out0_wready,
    input wire [17:0] bank_out0_bid,
    input wire [1:0] bank_out0_bresp,
    input wire [1:0] bank_out0_buser,
    input wire bank_out0_bvalid,
    output wire bank_out0_bready,
    output wire [17:0] bank_out0_arid,
    output wire [33:0] bank_out0_araddr,
    output wire [7:0] bank_out0_arlen,
    output wire [2:0] bank_out0_arsize,
    output wire [1:0] bank_out0_arburst,
    output wire bank_out0_arlock,
    output wire [3:0] bank_out0_arcache,
    output wire [2:0] bank_out0_arprot,
    output wire [1:0] bank_out0_aruser,
    output wire [3:0] bank_out0_arqos,
    output wire [3:0] bank_out0_arregion,
    output wire bank_out0_arvalid,
    input wire bank_out0_arready,
    input wire [17:0] bank_out0_rid,
    input wire [511:0] bank_out0_rdata,
    input wire [1:0] bank_out0_rresp,
    input wire bank_out0_rlast,
    input wire bank_out0_rvalid,
    output wire bank_out0_rready,
    input wire [1:0] bank_out0_ruser,
    output wire [17:0] bank_out1_awid,
    output wire [33:0] bank_out1_awaddr,
    output wire [7:0] bank_out1_awlen,
    output wire [2:0] bank_out1_awsize,
    output wire [1:0] bank_out1_awburst,
    output wire bank_out1_awlock,
    output wire [3:0] bank_out1_awcache,
    output wire [2:0] bank_out1_awprot,
    output wire [1:0] bank_out1_awuser,
    output wire [3:0] bank_out1_awqos,
    output wire [3:0] bank_out1_awregion,
    output wire bank_out1_awvalid,
    input wire bank_out1_awready,
    output wire [511:0] bank_out1_wdata,
    output wire [63:0] bank_out1_wstrb,
    output wire bank_out1_wlast,
    output wire bank_out1_wvalid,
    output wire [1:0] bank_out1_wuser,
    input wire bank_out1_wready,
    input wire [17:0] bank_out1_bid,
    input wire [1:0] bank_out1_bresp,
    input wire [1:0] bank_out1_buser,
    input wire bank_out1_bvalid,
    output wire bank_out1_bready,
    output wire [17:0] bank_out1_arid,
    output wire [33:0] bank_out1_araddr,
    output wire [7:0] bank_out1_arlen,
    output wire [2:0] bank_out1_arsize,
    output wire [1:0] bank_out1_arburst,
    output wire bank_out1_arlock,
    output wire [3:0] bank_out1_arcache,
    output wire [2:0] bank_out1_arprot,
    output wire [1:0] bank_out1_aruser,
    output wire [3:0] bank_out1_arqos,
    output wire [3:0] bank_out1_arregion,
    output wire bank_out1_arvalid,
    input wire bank_out1_arready,
    input wire [17:0] bank_out1_rid,
    input wire [511:0] bank_out1_rdata,
    input wire [1:0] bank_out1_rresp,
    input wire bank_out1_rlast,
    input wire bank_out1_rvalid,
    output wire bank_out1_rready,
    input wire [1:0] bank_out1_ruser,
    output wire [8:0] host_awid,
    output wire [56:0] host_awaddr,
    output wire [7:0] host_awlen,
    output wire [2:0] host_awsize,
    output wire [1:0] host_awburst,
    output wire host_awlock,
    output wire [3:0] host_awcache,
    output wire [2:0] host_awprot,
    output wire [3:0] host_awuser,
    output wire [3:0] host_awqos,
    output wire [3:0] host_awregion,
    output wire [5:0] host_awatop,
    output wire host_awvalid,
    input wire host_awready,
    output wire [8:0] host_arid,
    output wire [56:0] host_araddr,
    output wire [7:0] host_arlen,
    output wire [2:0] host_arsize,
    output wire [1:0] host_arburst,
    output wire host_arlock,
    output wire [3:0] host_arcache,
    output wire [2:0] host_arprot,
    output wire [3:0] host_aruser,
    output wire [3:0] host_arqos,
    output wire [3:0] host_arregion,
    output wire host_arvalid,
    input wire host_arready,
    output wire [511:0] host_wdata,
    output wire [63:0] host_wstrb,
    output wire host_wlast,
    output wire [3:0] host_wuser,
    output wire host_wvalid,
    input wire host_wready,
    input wire [8:0] host_rid,
    input wire [511:0] host_rdata,
    input wire [1:0] host_rresp,
    input wire host_rlast,
    input wire [3:0] host_ruser,
    input wire host_rvalid,
    output wire host_rready,
    input wire [8:0] host_bid,
    input wire [1:0] host_bresp,
    input wire [3:0] host_buser,
    input wire host_bvalid,
    output wire host_bready
);
    ofs_plat_axi_mem_lite_if #(.ADDR_WIDTH(16), .DATA_WIDTH(64),
        .RID_WIDTH(18), .WID_WIDTH(18), .USER_WIDTH(1)) dma_csr();
    ofs_plat_axi_mem_if #(.ADDR_WIDTH(57), .DATA_WIDTH(512), .BURST_CNT_WIDTH(8),
        .RID_WIDTH(9), .WID_WIDTH(9), .USER_WIDTH(4)) host_mem();
    ofs_plat_axi_mem_if #(`LOCAL_MEM_AXI_MEM_PARAMS_DEFAULT) dma_bank[2]();
    assign dma_csr.clk = clock_reset_clk;
    assign dma_csr.reset_n = clock_reset_reset_reset_n;
    assign dma_csr.instance_number = 0;
    assign host_mem.clk = clock_reset_clk;
    assign host_mem.reset_n = clock_reset_reset_reset_n;
    assign host_mem.instance_number = 1;
    for (genvar b=0; b<2; b++) begin
        assign dma_bank[b].clk = clock_reset_clk;
        assign dma_bank[b].reset_n = clock_reset_reset_reset_n;
        assign dma_bank[b].instance_number = b+2;
    end
    wire dma_csr_single_wlast; // PD single-beat CSR; AXI-Lite has no WLAST.
    assign host_awid = host_mem.aw.id;
    assign host_awaddr = host_mem.aw.addr;
    assign host_awlen = host_mem.aw.len;
    assign host_awsize = host_mem.aw.size;
    assign host_awburst = host_mem.aw.burst;
    assign host_awlock = host_mem.aw.lock;
    assign host_awcache = host_mem.aw.cache;
    assign host_awprot = host_mem.aw.prot;
    assign host_awuser = host_mem.aw.user;
    assign host_awqos = host_mem.aw.qos;
    assign host_awregion = host_mem.aw.region;
    assign host_awatop = host_mem.aw.atop;
    assign host_awvalid = host_mem.awvalid;
    assign host_mem.awready = host_awready;
    assign host_arid = host_mem.ar.id;
    assign host_araddr = host_mem.ar.addr;
    assign host_arlen = host_mem.ar.len;
    assign host_arsize = host_mem.ar.size;
    assign host_arburst = host_mem.ar.burst;
    assign host_arlock = host_mem.ar.lock;
    assign host_arcache = host_mem.ar.cache;
    assign host_arprot = host_mem.ar.prot;
    assign host_aruser = host_mem.ar.user;
    assign host_arqos = host_mem.ar.qos;
    assign host_arregion = host_mem.ar.region;
    assign host_arvalid = host_mem.arvalid;
    assign host_mem.arready = host_arready;
    assign host_wdata = host_mem.w.data;
    assign host_wstrb = host_mem.w.strb;
    assign host_wlast = host_mem.w.last;
    assign host_wuser = host_mem.w.user;
    assign host_wvalid = host_mem.wvalid;
    assign host_mem.wready = host_wready;
    assign host_mem.r.id = host_rid;
    assign host_mem.r.data = host_rdata;
    assign host_mem.r.resp = host_rresp;
    assign host_mem.r.last = host_rlast;
    assign host_mem.r.user = host_ruser;
    assign host_mem.rvalid = host_rvalid;
    assign host_rready = host_mem.rready;
    assign host_mem.b.id = host_bid;
    assign host_mem.b.resp = host_bresp;
    assign host_mem.b.user = host_buser;
    assign host_mem.bvalid = host_bvalid;
    assign host_bready = host_mem.bready;
    ahls_memory_dma_fabric fabric (
        .clock_reset_clk(clock_reset_clk),
        .clock_reset_reset_reset_n(clock_reset_reset_reset_n),
        .freeze_freeze(freeze_freeze),
        .device_exception_bus_data(device_exception_bus_data),
        .kernel_irqs_irq(kernel_irqs_irq),
        .mmio_control_awid(mmio_control_awid),
        .mmio_control_awaddr(mmio_control_awaddr),
        .mmio_control_awlen(mmio_control_awlen),
        .mmio_control_awsize(mmio_control_awsize),
        .mmio_control_awburst(mmio_control_awburst),
        .mmio_control_awuser(mmio_control_awuser),
        .mmio_control_awvalid(mmio_control_awvalid),
        .mmio_control_awready(mmio_control_awready),
        .mmio_control_wdata(mmio_control_wdata),
        .mmio_control_wstrb(mmio_control_wstrb),
        .mmio_control_wvalid(mmio_control_wvalid),
        .mmio_control_wuser(mmio_control_wuser),
        .mmio_control_wready(mmio_control_wready),
        .mmio_control_bid(mmio_control_bid),
        .mmio_control_bresp(mmio_control_bresp),
        .mmio_control_buser(mmio_control_buser),
        .mmio_control_bvalid(mmio_control_bvalid),
        .mmio_control_bready(mmio_control_bready),
        .mmio_control_arid(mmio_control_arid),
        .mmio_control_araddr(mmio_control_araddr),
        .mmio_control_arlen(mmio_control_arlen),
        .mmio_control_arsize(mmio_control_arsize),
        .mmio_control_arburst(mmio_control_arburst),
        .mmio_control_aruser(mmio_control_aruser),
        .mmio_control_arvalid(mmio_control_arvalid),
        .mmio_control_arready(mmio_control_arready),
        .mmio_control_rid(mmio_control_rid),
        .mmio_control_rdata(mmio_control_rdata),
        .mmio_control_rresp(mmio_control_rresp),
        .mmio_control_rlast(mmio_control_rlast),
        .mmio_control_rvalid(mmio_control_rvalid),
        .mmio_control_rready(mmio_control_rready),
        .mmio_control_ruser(mmio_control_ruser),
        .dma_csr_awid(dma_csr.aw.id),
        .dma_csr_awaddr(dma_csr.aw.addr),
        .dma_csr_awsize(dma_csr.aw.size),
        .dma_csr_awprot(dma_csr.aw.prot),
        .dma_csr_awuser(dma_csr.aw.user),
        .dma_csr_awvalid(dma_csr.awvalid),
        .dma_csr_awready(dma_csr.awready),
        .dma_csr_wdata(dma_csr.w.data),
        .dma_csr_wstrb(dma_csr.w.strb),
        .dma_csr_wlast(dma_csr_single_wlast),
        .dma_csr_wvalid(dma_csr.wvalid),
        .dma_csr_wuser(dma_csr.w.user),
        .dma_csr_wready(dma_csr.wready),
        .dma_csr_bid(dma_csr.b.id),
        .dma_csr_bresp(dma_csr.b.resp),
        .dma_csr_buser(dma_csr.b.user),
        .dma_csr_bvalid(dma_csr.bvalid),
        .dma_csr_bready(dma_csr.bready),
        .dma_csr_arid(dma_csr.ar.id),
        .dma_csr_araddr(dma_csr.ar.addr),
        .dma_csr_arsize(dma_csr.ar.size),
        .dma_csr_arprot(dma_csr.ar.prot),
        .dma_csr_aruser(dma_csr.ar.user),
        .dma_csr_arvalid(dma_csr.arvalid),
        .dma_csr_arready(dma_csr.arready),
        .dma_csr_rid(dma_csr.r.id),
        .dma_csr_rdata(dma_csr.r.data),
        .dma_csr_rresp(dma_csr.r.resp),
        .dma_csr_rvalid(dma_csr.rvalid),
        .dma_csr_rready(dma_csr.rready),
        .dma_csr_ruser(dma_csr.r.user),
        .dma_ddr_in0_awid(dma_bank[0].aw.id),
        .dma_ddr_in0_awaddr(dma_bank[0].aw.addr),
        .dma_ddr_in0_awlen(dma_bank[0].aw.len),
        .dma_ddr_in0_awsize(dma_bank[0].aw.size),
        .dma_ddr_in0_awburst(dma_bank[0].aw.burst),
        .dma_ddr_in0_awlock(dma_bank[0].aw.lock),
        .dma_ddr_in0_awcache(dma_bank[0].aw.cache),
        .dma_ddr_in0_awprot(dma_bank[0].aw.prot),
        .dma_ddr_in0_awuser(dma_bank[0].aw.user),
        .dma_ddr_in0_awqos(dma_bank[0].aw.qos),
        .dma_ddr_in0_awregion(dma_bank[0].aw.region),
        .dma_ddr_in0_awvalid(dma_bank[0].awvalid),
        .dma_ddr_in0_awready(dma_bank[0].awready),
        .dma_ddr_in0_wdata(dma_bank[0].w.data),
        .dma_ddr_in0_wstrb(dma_bank[0].w.strb),
        .dma_ddr_in0_wlast(dma_bank[0].w.last),
        .dma_ddr_in0_wvalid(dma_bank[0].wvalid),
        .dma_ddr_in0_wuser(dma_bank[0].w.user),
        .dma_ddr_in0_wready(dma_bank[0].wready),
        .dma_ddr_in0_bid(dma_bank[0].b.id),
        .dma_ddr_in0_bresp(dma_bank[0].b.resp),
        .dma_ddr_in0_buser(dma_bank[0].b.user),
        .dma_ddr_in0_bvalid(dma_bank[0].bvalid),
        .dma_ddr_in0_bready(dma_bank[0].bready),
        .dma_ddr_in0_arid(dma_bank[0].ar.id),
        .dma_ddr_in0_araddr(dma_bank[0].ar.addr),
        .dma_ddr_in0_arlen(dma_bank[0].ar.len),
        .dma_ddr_in0_arsize(dma_bank[0].ar.size),
        .dma_ddr_in0_arburst(dma_bank[0].ar.burst),
        .dma_ddr_in0_arlock(dma_bank[0].ar.lock),
        .dma_ddr_in0_arcache(dma_bank[0].ar.cache),
        .dma_ddr_in0_arprot(dma_bank[0].ar.prot),
        .dma_ddr_in0_aruser(dma_bank[0].ar.user),
        .dma_ddr_in0_arqos(dma_bank[0].ar.qos),
        .dma_ddr_in0_arregion(dma_bank[0].ar.region),
        .dma_ddr_in0_arvalid(dma_bank[0].arvalid),
        .dma_ddr_in0_arready(dma_bank[0].arready),
        .dma_ddr_in0_rid(dma_bank[0].r.id),
        .dma_ddr_in0_rdata(dma_bank[0].r.data),
        .dma_ddr_in0_rresp(dma_bank[0].r.resp),
        .dma_ddr_in0_rlast(dma_bank[0].r.last),
        .dma_ddr_in0_rvalid(dma_bank[0].rvalid),
        .dma_ddr_in0_rready(dma_bank[0].rready),
        .dma_ddr_in0_ruser(dma_bank[0].r.user),
        .bank_out0_awid(bank_out0_awid),
        .bank_out0_awaddr(bank_out0_awaddr),
        .bank_out0_awlen(bank_out0_awlen),
        .bank_out0_awsize(bank_out0_awsize),
        .bank_out0_awburst(bank_out0_awburst),
        .bank_out0_awlock(bank_out0_awlock),
        .bank_out0_awcache(bank_out0_awcache),
        .bank_out0_awprot(bank_out0_awprot),
        .bank_out0_awuser(bank_out0_awuser),
        .bank_out0_awqos(bank_out0_awqos),
        .bank_out0_awregion(bank_out0_awregion),
        .bank_out0_awvalid(bank_out0_awvalid),
        .bank_out0_awready(bank_out0_awready),
        .bank_out0_wdata(bank_out0_wdata),
        .bank_out0_wstrb(bank_out0_wstrb),
        .bank_out0_wlast(bank_out0_wlast),
        .bank_out0_wvalid(bank_out0_wvalid),
        .bank_out0_wuser(bank_out0_wuser),
        .bank_out0_wready(bank_out0_wready),
        .bank_out0_bid(bank_out0_bid),
        .bank_out0_bresp(bank_out0_bresp),
        .bank_out0_buser(bank_out0_buser),
        .bank_out0_bvalid(bank_out0_bvalid),
        .bank_out0_bready(bank_out0_bready),
        .bank_out0_arid(bank_out0_arid),
        .bank_out0_araddr(bank_out0_araddr),
        .bank_out0_arlen(bank_out0_arlen),
        .bank_out0_arsize(bank_out0_arsize),
        .bank_out0_arburst(bank_out0_arburst),
        .bank_out0_arlock(bank_out0_arlock),
        .bank_out0_arcache(bank_out0_arcache),
        .bank_out0_arprot(bank_out0_arprot),
        .bank_out0_aruser(bank_out0_aruser),
        .bank_out0_arqos(bank_out0_arqos),
        .bank_out0_arregion(bank_out0_arregion),
        .bank_out0_arvalid(bank_out0_arvalid),
        .bank_out0_arready(bank_out0_arready),
        .bank_out0_rid(bank_out0_rid),
        .bank_out0_rdata(bank_out0_rdata),
        .bank_out0_rresp(bank_out0_rresp),
        .bank_out0_rlast(bank_out0_rlast),
        .bank_out0_rvalid(bank_out0_rvalid),
        .bank_out0_rready(bank_out0_rready),
        .bank_out0_ruser(bank_out0_ruser),
        .dma_ddr_in1_awid(dma_bank[1].aw.id),
        .dma_ddr_in1_awaddr(dma_bank[1].aw.addr),
        .dma_ddr_in1_awlen(dma_bank[1].aw.len),
        .dma_ddr_in1_awsize(dma_bank[1].aw.size),
        .dma_ddr_in1_awburst(dma_bank[1].aw.burst),
        .dma_ddr_in1_awlock(dma_bank[1].aw.lock),
        .dma_ddr_in1_awcache(dma_bank[1].aw.cache),
        .dma_ddr_in1_awprot(dma_bank[1].aw.prot),
        .dma_ddr_in1_awuser(dma_bank[1].aw.user),
        .dma_ddr_in1_awqos(dma_bank[1].aw.qos),
        .dma_ddr_in1_awregion(dma_bank[1].aw.region),
        .dma_ddr_in1_awvalid(dma_bank[1].awvalid),
        .dma_ddr_in1_awready(dma_bank[1].awready),
        .dma_ddr_in1_wdata(dma_bank[1].w.data),
        .dma_ddr_in1_wstrb(dma_bank[1].w.strb),
        .dma_ddr_in1_wlast(dma_bank[1].w.last),
        .dma_ddr_in1_wvalid(dma_bank[1].wvalid),
        .dma_ddr_in1_wuser(dma_bank[1].w.user),
        .dma_ddr_in1_wready(dma_bank[1].wready),
        .dma_ddr_in1_bid(dma_bank[1].b.id),
        .dma_ddr_in1_bresp(dma_bank[1].b.resp),
        .dma_ddr_in1_buser(dma_bank[1].b.user),
        .dma_ddr_in1_bvalid(dma_bank[1].bvalid),
        .dma_ddr_in1_bready(dma_bank[1].bready),
        .dma_ddr_in1_arid(dma_bank[1].ar.id),
        .dma_ddr_in1_araddr(dma_bank[1].ar.addr),
        .dma_ddr_in1_arlen(dma_bank[1].ar.len),
        .dma_ddr_in1_arsize(dma_bank[1].ar.size),
        .dma_ddr_in1_arburst(dma_bank[1].ar.burst),
        .dma_ddr_in1_arlock(dma_bank[1].ar.lock),
        .dma_ddr_in1_arcache(dma_bank[1].ar.cache),
        .dma_ddr_in1_arprot(dma_bank[1].ar.prot),
        .dma_ddr_in1_aruser(dma_bank[1].ar.user),
        .dma_ddr_in1_arqos(dma_bank[1].ar.qos),
        .dma_ddr_in1_arregion(dma_bank[1].ar.region),
        .dma_ddr_in1_arvalid(dma_bank[1].arvalid),
        .dma_ddr_in1_arready(dma_bank[1].arready),
        .dma_ddr_in1_rid(dma_bank[1].r.id),
        .dma_ddr_in1_rdata(dma_bank[1].r.data),
        .dma_ddr_in1_rresp(dma_bank[1].r.resp),
        .dma_ddr_in1_rlast(dma_bank[1].r.last),
        .dma_ddr_in1_rvalid(dma_bank[1].rvalid),
        .dma_ddr_in1_rready(dma_bank[1].rready),
        .dma_ddr_in1_ruser(dma_bank[1].r.user),
        .bank_out1_awid(bank_out1_awid),
        .bank_out1_awaddr(bank_out1_awaddr),
        .bank_out1_awlen(bank_out1_awlen),
        .bank_out1_awsize(bank_out1_awsize),
        .bank_out1_awburst(bank_out1_awburst),
        .bank_out1_awlock(bank_out1_awlock),
        .bank_out1_awcache(bank_out1_awcache),
        .bank_out1_awprot(bank_out1_awprot),
        .bank_out1_awuser(bank_out1_awuser),
        .bank_out1_awqos(bank_out1_awqos),
        .bank_out1_awregion(bank_out1_awregion),
        .bank_out1_awvalid(bank_out1_awvalid),
        .bank_out1_awready(bank_out1_awready),
        .bank_out1_wdata(bank_out1_wdata),
        .bank_out1_wstrb(bank_out1_wstrb),
        .bank_out1_wlast(bank_out1_wlast),
        .bank_out1_wvalid(bank_out1_wvalid),
        .bank_out1_wuser(bank_out1_wuser),
        .bank_out1_wready(bank_out1_wready),
        .bank_out1_bid(bank_out1_bid),
        .bank_out1_bresp(bank_out1_bresp),
        .bank_out1_buser(bank_out1_buser),
        .bank_out1_bvalid(bank_out1_bvalid),
        .bank_out1_bready(bank_out1_bready),
        .bank_out1_arid(bank_out1_arid),
        .bank_out1_araddr(bank_out1_araddr),
        .bank_out1_arlen(bank_out1_arlen),
        .bank_out1_arsize(bank_out1_arsize),
        .bank_out1_arburst(bank_out1_arburst),
        .bank_out1_arlock(bank_out1_arlock),
        .bank_out1_arcache(bank_out1_arcache),
        .bank_out1_arprot(bank_out1_arprot),
        .bank_out1_aruser(bank_out1_aruser),
        .bank_out1_arqos(bank_out1_arqos),
        .bank_out1_arregion(bank_out1_arregion),
        .bank_out1_arvalid(bank_out1_arvalid),
        .bank_out1_arready(bank_out1_arready),
        .bank_out1_rid(bank_out1_rid),
        .bank_out1_rdata(bank_out1_rdata),
        .bank_out1_rresp(bank_out1_rresp),
        .bank_out1_rlast(bank_out1_rlast),
        .bank_out1_rvalid(bank_out1_rvalid),
        .bank_out1_rready(bank_out1_rready),
        .bank_out1_ruser(bank_out1_ruser)
    );
    // No ID/USER slicing at the generated-fabric boundary.
    dma_top #(.NUM_LOCAL_MEM_BANKS(2), .DDR_BANK_ADDR_W(34), .HOST_ADDR_W(57)) dma (
        .mmio64_to_afu(dma_csr), .host_mem(host_mem), .ddr_mem(dma_bank));
endmodule
