--------------------------------------------------------------------
--
--  Copyright (C) 2025  Altera Corporation. All rights reserved.
--
--  Your use of Altera Corporation's design tools, logic functions  
--  and other software and tools, and its AMPP partner logic  
--  functions, and any output files from any of the foregoing  
--  (including device programming or simulation files), and any  
--  associated documentation or information are expressly subject  
--  to the terms and conditions of the Altera Program License  
--  Subscription Agreement, Altera MegaCore Function License  
--  Agreement, or other applicable license agreement, including,  
--  without limitation, that your use is for the sole purpose of  
--  programming logic devices manufactured by Altera and sold by  
--  Altera or its authorized distributors.  Please refer to the  
--  applicable agreement for further details. 
--  
-- This is an auto-generated file. Do not edit this file.
--
--  25.1.0 Build 129 03/26/2025 SC Pro Edition
--
--------------------------------------------------------------------

-- START_FILE_HEADER --------------------------------------------------
--
-- Filename    : altera_sld_host_endpoint.vhd
--
-- Description : 
-- 
-- Limitation  : This component will not be functional until Quartus synthesis
--               has connected it up.
--
-- Copyright (c) Altera Corporation 2024
-- All rights reserved
--
-- END_FILE_HEADER --------------------------------------------------

---START_PACKAGE_HEADER-------------------------------------------------
--
-- Package Name    :  
--
-- Description     :  
--
-- Authors         :  
--
---END_PACKAGE_HEADER-------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

package altera_sld_host_endpoint_package is

	function log2 (value : in natural) return natural;

	function nonzero (value : in natural) return natural;

	function ifcond (cond : in boolean; value : in natural) return natural;

end package altera_sld_host_endpoint_package;

package body altera_sld_host_endpoint_package is

	function log2 (value : in natural) return natural is
		variable value_int : natural := 0;
		variable ret       : natural := 0;
	begin
		value_int := value - 1;
		ret := 0;
		bit_shift_loop:
		while (value_int > 0) loop
			value_int := value_int / 2;
			ret := ret + 1;
		end loop;
		if (ret = 0) then
			ret := 1;
		end if;
		return ret;
	end function log2;

	function nonzero (value : in natural) return natural is
	begin
		if (value = 0) then
			return 1;
		end if;
		return value;
	end function nonzero;

	function ifcond (cond : in boolean; value : in natural) return natural is
	begin
		if (not cond) then
			return 0;
		end if;
		return value;
	end function ifcond;

end package body altera_sld_host_endpoint_package;

-- LIBRARY USED-----------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
use work.altera_sld_host_endpoint_package.all;

---START_ENTITY_HEADER-------------------------------------------------
--
-- Entity Name     : altera_sld_host_endpoint
--
-- Description     : 
--
-- Limitation      : The implementation uses Quartus magic to connect it
--                   to an actual component in a different partition which
--                   does the real work.
--
-- Results Expected: None
--
---END_ENTITY_HEADER-------------------------------------------------

entity altera_sld_host_endpoint is
    generic
    ( 
        ENABLE_JTAG_IO_SELECTION : natural := 0;
        CONTROL        : string  := "host";
        NAME           : string  := " ";
        HOST_PRIORITY  : natural := 0;
        BRIDGE_HOST    : natural := 0;
        USE_TCK_ENA    : natural := 0;
        NEGEDGE_TDO_LATCH : natural := 0;
        TYPE_NAME      : natural := 0;
        INSTANCE_NAME  : natural := 0;
        CLOCK_RATE_CLOCK : natural := 0
    );

	port
	(
		-- Signals to be connected up by the user
        tck            : in  std_logic;
        tms            : in  std_logic;
        tdi            : in  std_logic;
        ena            : in  std_logic := '0';
        vir_tdi        : in  std_logic := '0';
        tck_ena        : in  std_logic := '0';
        tdo            : out std_logic;
        select_this    : in  std_logic := '0'
    );

end altera_sld_host_endpoint;

architecture rtl of altera_sld_host_endpoint is

	component altera_fabric_endpoint is
		generic
		(
			SLD_ENDPOINT_TYPE        : natural := 0;
			SEND_WIDTH               : natural := 4;
			RECEIVE_WIDTH            : natural := 4;
			NUM_CLOCKS               : natural := 0;			
			SETTINGS                 : string := ""
		);
		port
		(
			send           : in std_logic_vector((ifcond(SEND_WIDTH = 0, 1) + SEND_WIDTH) - 1 downto 0);  -- Sent from endpoint
			receive        : out std_logic_vector((ifcond(RECEIVE_WIDTH = 0, 1) + RECEIVE_WIDTH) - 1 downto 0) := (others => '0') -- Received by endpoint
		);
	end component altera_fabric_endpoint;

    constant TCK_BASE            : natural := 0;
    constant TMS_BASE            : natural := 1;
    constant TDI_BASE            : natural := 2;
    constant ENA_BASE            : natural := 3;
    constant VIR_TDI_BASE        : natural := 3 + ifcond(BRIDGE_HOST /= 0, 1);
    constant TCK_ENA_BASE        : natural := VIR_TDI_BASE + ifcond(BRIDGE_HOST /= 0, 1);
    constant TDO_BASE            : natural := 0;
    constant SELECT_THIS_BASE    : natural := TCK_ENA_BASE + ifcond(USE_TCK_ENA /= 0, 1);
    constant SEND_WIDTH          : natural := SELECT_THIS_BASE + ifcond(ENABLE_JTAG_IO_SELECTION /= 0, 1);
    constant RECEIVE_WIDTH       : natural := 1;
    constant NUM_CLOCKS          : natural := 1;

    constant SETTINGS      : string := "{fabric sld dir host enable_jtag_io_selection " & integer'image(ENABLE_JTAG_IO_SELECTION) & 
                " control {" & CONTROL & "} name {" & NAME & "} host_priority " & integer'image(HOST_PRIORITY) & 
                " bridge_host " & integer'image(BRIDGE_HOST) & " use_tck_ena " & integer'image(USE_TCK_ENA) & 
                " negedge_tdo_latch " & integer'image(NEGEDGE_TDO_LATCH) & " type_name " & integer'image(TYPE_NAME) & 
                " instance_name " & integer'image(INSTANCE_NAME) & 
                " clock_rate_clock " & integer'image(CLOCK_RATE_CLOCK) & " psig 5850bc6d}";

	signal send : std_logic_vector((ifcond(SEND_WIDTH = 0, 1) + SEND_WIDTH) - 1 downto 0);
	signal receive : std_logic_vector((ifcond(RECEIVE_WIDTH = 0, 1) + RECEIVE_WIDTH) - 1 downto 0);

begin
    send(TCK_BASE) <= tck;
    send(TMS_BASE) <= tms;
    send(TDI_BASE) <= tdi;

present_s1: if BRIDGE_HOST /= 0 generate
    send(ENA_BASE) <= ena;
    send(VIR_TDI_BASE) <= vir_tdi;
end generate;

present_s2: if USE_TCK_ENA /= 0 generate
    send(TCK_ENA_BASE) <= tck_ena;
end generate;

present_s3: if ENABLE_JTAG_IO_SELECTION /= 0 generate
    send(SELECT_THIS_BASE) <= select_this;
end generate;

default_send: if SEND_WIDTH = 0 generate
	send(0) <= '0';
end generate;

	ep : altera_fabric_endpoint
		generic map
		(
			SLD_ENDPOINT_TYPE => 0,
			SEND_WIDTH => SEND_WIDTH,
			RECEIVE_WIDTH => RECEIVE_WIDTH,
			NUM_CLOCKS => NUM_CLOCKS,			
			SETTINGS => SETTINGS
		)
		port map
		(
			send      => send,
			receive   => receive
		);

    tdo <= receive(TDO_BASE);

end rtl;

